/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    ['bus-stop001']: THREE.Mesh
    ['bus-stop001_1']: THREE.Mesh
    ['bus-stop001_2']: THREE.Mesh
    ['bus-stop001_3']: THREE.Mesh
    ['bus-stop001']: THREE.Mesh
    ['bus-stop001_1']: THREE.Mesh
    ['bus-stop001_2']: THREE.Mesh
    ['bus-stop001_3']: THREE.Mesh
    ['bus-stop001']: THREE.Mesh
    ['bus-stop001_1']: THREE.Mesh
    ['bus-stop001_2']: THREE.Mesh
    ['bus-stop001_3']: THREE.Mesh
    ['bus-stop001']: THREE.Mesh
    ['bus-stop001_1']: THREE.Mesh
    ['bus-stop001_2']: THREE.Mesh
    ['bus-stop001_3']: THREE.Mesh
    ['bus-passenger-base_1']: THREE.Mesh
    ['bus-passenger-base_2']: THREE.Mesh
    ['bus-passenger-base_3']: THREE.Mesh
    ['bus-passenger-base_4']: THREE.Mesh
    ['bus-passenger-base_5']: THREE.Mesh
    ['bus-passenger-base_6']: THREE.Mesh
    ['bus-passenger-base_7']: THREE.Mesh
    ['bus-passenger-base_8']: THREE.Mesh
    ['bus-passenger-wheel_BL_1']: THREE.Mesh
    ['bus-passenger-wheel_BL_2']: THREE.Mesh
    ['bus-passenger-wheel_BR_1']: THREE.Mesh
    ['bus-passenger-wheel_BR_2']: THREE.Mesh
    ['bus-passenger-wheel_FL_1']: THREE.Mesh
    ['bus-passenger-wheel_FL_2']: THREE.Mesh
    ['bus-passenger-wheel_FR_1']: THREE.Mesh
    ['bus-passenger-wheel_FR_2']: THREE.Mesh
  }
  materials: {
    ['20 GREY.001']: THREE.MeshPhysicalMaterial
    ['23 GREY-WHITE.006']: THREE.MeshPhysicalMaterial
    ['64 GLASS.001']: THREE.MeshPhysicalMaterial
    ['10 BROWN-DARK.002']: THREE.MeshPhysicalMaterial
    ['23 GREY-WHITE.007']: THREE.MeshPhysicalMaterial
    ['64 GLASS.013']: THREE.MeshPhysicalMaterial
    ['20 GREY.015']: THREE.MeshPhysicalMaterial
    ['57 BLACK.003']: THREE.MeshPhysicalMaterial
    ['17 GREY-DARKEST']: THREE.MeshPhysicalMaterial
    ['59 EMISSION-WHITE.001']: THREE.MeshStandardMaterial
    ['42 BLUE-DARK.002']: THREE.MeshPhysicalMaterial
    ['60 EMISSION-RED.003']: THREE.MeshStandardMaterial
  }
}

export function BusStops(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/bus-stops.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="bus-stop004" position={[14.849, 2.667, 65.228]} scale={1.499}>
          <mesh
            name="bus-stop001"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001'].geometry}
            material={materials['20 GREY.001']}
          />
          <mesh
            name="bus-stop001_1"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_1'].geometry}
            material={materials['23 GREY-WHITE.006']}
          />
          <mesh
            name="bus-stop001_2"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_2'].geometry}
            material={materials['64 GLASS.001']}
          />
          <mesh
            name="bus-stop001_3"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_3'].geometry}
            material={materials['10 BROWN-DARK.002']}
          />
        </group>
        <group
          name="bus-stop005"
          position={[114.037, 2.667, 30.253]}
          rotation={[0, 1.571, 0]}
          scale={1.499}>
          <mesh
            name="bus-stop001"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001'].geometry}
            material={materials['20 GREY.001']}
          />
          <mesh
            name="bus-stop001_1"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_1'].geometry}
            material={materials['23 GREY-WHITE.006']}
          />
          <mesh
            name="bus-stop001_2"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_2'].geometry}
            material={materials['64 GLASS.001']}
          />
          <mesh
            name="bus-stop001_3"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_3'].geometry}
            material={materials['10 BROWN-DARK.002']}
          />
        </group>
        <group name="bus-stop006" position={[-50.916, 2.667, -22.164]} scale={1.499}>
          <mesh
            name="bus-stop001"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001'].geometry}
            material={materials['20 GREY.001']}
          />
          <mesh
            name="bus-stop001_1"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_1'].geometry}
            material={materials['23 GREY-WHITE.006']}
          />
          <mesh
            name="bus-stop001_2"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_2'].geometry}
            material={materials['64 GLASS.001']}
          />
          <mesh
            name="bus-stop001_3"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_3'].geometry}
            material={materials['10 BROWN-DARK.002']}
          />
        </group>
        <group
          name="bus-stop007"
          position={[36.447, 2.667, -5.241]}
          rotation={[0, -1.571, 0]}
          scale={1.499}>
          <mesh
            name="bus-stop001"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001'].geometry}
            material={materials['20 GREY.001']}
          />
          <mesh
            name="bus-stop001_1"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_1'].geometry}
            material={materials['23 GREY-WHITE.006']}
          />
          <mesh
            name="bus-stop001_2"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_2'].geometry}
            material={materials['64 GLASS.001']}
          />
          <mesh
            name="bus-stop001_3"
            castShadow
            receiveShadow
            geometry={nodes['bus-stop001_3'].geometry}
            material={materials['10 BROWN-DARK.002']}
          />
        </group>
        <group name="bus-passenger" position={[118.751, 2.467, 28.139]}>
          <group name="bus-passenger-base">
            <mesh
              name="bus-passenger-base_1"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-base_1'].geometry}
              material={materials['23 GREY-WHITE.007']}
            />
            <mesh
              name="bus-passenger-base_2"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-base_2'].geometry}
              material={materials['64 GLASS.013']}
            />
            <mesh
              name="bus-passenger-base_3"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-base_3'].geometry}
              material={materials['20 GREY.015']}
            />
            <mesh
              name="bus-passenger-base_4"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-base_4'].geometry}
              material={materials['57 BLACK.003']}
            />
            <mesh
              name="bus-passenger-base_5"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-base_5'].geometry}
              material={materials['17 GREY-DARKEST']}
            />
            <mesh
              name="bus-passenger-base_6"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-base_6'].geometry}
              material={materials['59 EMISSION-WHITE.001']}
            />
            <mesh
              name="bus-passenger-base_7"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-base_7'].geometry}
              material={materials['42 BLUE-DARK.002']}
            />
            <mesh
              name="bus-passenger-base_8"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-base_8'].geometry}
              material={materials['60 EMISSION-RED.003']}
            />
          </group>
          <group name="bus-passenger-wheel_BL" position={[1.043, 0.535, -2.536]}>
            <mesh
              name="bus-passenger-wheel_BL_1"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-wheel_BL_1'].geometry}
              material={materials['17 GREY-DARKEST']}
            />
            <mesh
              name="bus-passenger-wheel_BL_2"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-wheel_BL_2'].geometry}
              material={materials['20 GREY.015']}
            />
          </group>
          <group name="bus-passenger-wheel_BR" position={[-1.043, 0.535, -2.536]}>
            <mesh
              name="bus-passenger-wheel_BR_1"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-wheel_BR_1'].geometry}
              material={materials['17 GREY-DARKEST']}
            />
            <mesh
              name="bus-passenger-wheel_BR_2"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-wheel_BR_2'].geometry}
              material={materials['20 GREY.015']}
            />
          </group>
          <group name="bus-passenger-wheel_FL" position={[1.043, 0.535, 3.303]}>
            <mesh
              name="bus-passenger-wheel_FL_1"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-wheel_FL_1'].geometry}
              material={materials['17 GREY-DARKEST']}
            />
            <mesh
              name="bus-passenger-wheel_FL_2"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-wheel_FL_2'].geometry}
              material={materials['20 GREY.015']}
            />
          </group>
          <group name="bus-passenger-wheel_FR" position={[-1.043, 0.535, 3.303]}>
            <mesh
              name="bus-passenger-wheel_FR_1"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-wheel_FR_1'].geometry}
              material={materials['17 GREY-DARKEST']}
            />
            <mesh
              name="bus-passenger-wheel_FR_2"
              castShadow
              receiveShadow
              geometry={nodes['bus-passenger-wheel_FR_2'].geometry}
              material={materials['20 GREY.015']}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/bus-stops.glb')
