/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { MeshGLTFModel } from '@/experience/types/modelTypes';
import { createSharedAtlasMaterial } from '@/experience/utils/materialUtils';
import { useGLTF } from '@react-three/drei';
import { ThreeElements } from '@react-three/fiber';

export function Billboard(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/billboard.glb') as unknown as MeshGLTFModel;
  const LowpolyMaterial = createSharedAtlasMaterial(materials);
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, Math.PI / 2, 0]} scale={0.028}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Main_1.geometry}
          material={materials.lambert3SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Main_2.geometry}
          material={materials['billboard-graphic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Main_3.geometry}
          material={materials.Light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Main_4.geometry}
          material={LowpolyMaterial}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Base.geometry}
        material={LowpolyMaterial}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.028}
      />
    </group>
  );
}

useGLTF.preload('/models/billboard.glb');
