/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeElements } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    ["cloud-triangle"]: THREE.Mesh;
    ["cloud-small"]: THREE.Mesh;
    ["cloud-simple"]: THREE.Mesh;
    ["cloud-long"]: THREE.Mesh;
    ["cloud-fluffy"]: THREE.Mesh;
    ["cloud-big"]: THREE.Mesh;
  };
  materials: {
    ["59 EMISSION-WHITE"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/clouds_group.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="cloud-triangle"
          geometry={nodes["cloud-triangle"].geometry}
          material={materials["59 EMISSION-WHITE"]}
          position={[26.438, 0.103, 0.274]}
        />
        <mesh
          name="cloud-small"
          geometry={nodes["cloud-small"].geometry}
          material={materials["59 EMISSION-WHITE"]}
          position={[1.438, 0.103, 0.274]}
        />
        <mesh
          name="cloud-simple"
          geometry={nodes["cloud-simple"].geometry}
          material={materials["59 EMISSION-WHITE"]}
          position={[6.438, 0.103, 0.274]}
        />
        <mesh
          name="cloud-long"
          geometry={nodes["cloud-long"].geometry}
          material={materials["59 EMISSION-WHITE"]}
          position={[-11.318, 0.103, 0.274]}
        />
        <mesh
          name="cloud-fluffy"
          geometry={nodes["cloud-fluffy"].geometry}
          material={materials["59 EMISSION-WHITE"]}
          position={[36.438, 0.103, 0.274]}
        />
        <mesh
          name="cloud-big"
          geometry={nodes["cloud-big"].geometry}
          material={materials["59 EMISSION-WHITE"]}
          position={[16.438, 0.103, 0.274]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/clouds_group.glb");
