/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vehicles_excavator.glb -o experience/sceneCollections/construction/models/Excavator.tsx -r public -t -k -K -T 
Files: public/models/vehicles_excavator.glb [48.48KB] > /Users/milesroxas/SITES/Client/sanity-3d/experience/sceneCollections/construction/models/vehicles_excavator-transformed.glb [12.12KB] (75%)
*/

import * as THREE from 'three'
import React, { useRef  } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    ['excavator-arm-base']: THREE.Mesh
    ['excavator-base_1']: THREE.Mesh
    ['excavator-base_2']: THREE.Mesh
    ['excavator-base_3']: THREE.Mesh
    excavator: THREE.InstancedMesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
  }
}

const MODEL_PATH = '/models/vehicles_excavator-transformed.glb'

export function Excavator(props: ThreeElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF(MODEL_PATH) as GLTFResult

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="excavator-arm-base" geometry={nodes['excavator-arm-base'].geometry} material={materials.PaletteMaterial001} position={[122.853, 6.702, -73.19]} rotation={[-2.356, 0, -Math.PI]} />
        <group name="excavator-base" position={[122.36, 4.875, -70.488]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh name="excavator-base_1" geometry={nodes['excavator-base_1'].geometry} material={materials.PaletteMaterial002} />
          <mesh name="excavator-base_2" geometry={nodes['excavator-base_2'].geometry} material={materials.PaletteMaterial003} />
          <mesh name="excavator-base_3" geometry={nodes['excavator-base_3'].geometry} material={materials.PaletteMaterial004} />
        </group>
        <instancedMesh args={[nodes.excavator.geometry, materials.PaletteMaterial001, 2]} name="excavator" instanceMatrix={nodes.excavator.instanceMatrix} position={[122.853, 2.906, -70.507]} rotation={[Math.PI, 0, Math.PI]} />
      </group>
    </group>
  )
}

// Preload the model
useGLTF.preload(MODEL_PATH)
