/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    ['rug-circle_1']: THREE.Mesh
    ['rug-circle_2']: THREE.Mesh
    ['scifi-pot-low-palm']: THREE.Mesh
    ['scifi-pot-low-palm_1']: THREE.Mesh
    ['scifi-pot-low-palm_2']: THREE.Mesh
    ['scifi-pot-low-palm_3']: THREE.Mesh
    ['scifi-pot-low-palm_4']: THREE.Mesh
    ['scifi-pot-low-palm_5']: THREE.Mesh
    ['scifi-pot-low-palm_6']: THREE.Mesh
    ['scifi-pot-low-palm_7']: THREE.Mesh
    ['scifi-pot-low-palm_8']: THREE.Mesh
    ['scifi-pot-low-palm_9']: THREE.Mesh
    ['tent-party002']: THREE.Mesh
    ['tent-party002_1']: THREE.Mesh
    ['tent-party008_1']: THREE.Mesh
    ['tent-party008_2']: THREE.Mesh
    ['tent-party006']: THREE.Mesh
    ['tent-party006_1']: THREE.Mesh
    ['tent-party004']: THREE.Mesh
    ['tent-party004_1']: THREE.Mesh
    ['tent-party001']: THREE.Mesh
    ['tent-party001_1']: THREE.Mesh
    ['tent-party']: THREE.Mesh
    ['tent-party_1']: THREE.Mesh
    ['building-cinema_1']: THREE.Mesh
    ['building-cinema_2']: THREE.Mesh
    ['building-cinema_3']: THREE.Mesh
    ['building-cinema_4']: THREE.Mesh
    ['building-cinema_5']: THREE.Mesh
    ['building-cinema_6']: THREE.Mesh
    ['building-cinema_7']: THREE.Mesh
    ['building-cinema_8']: THREE.Mesh
    ['balloons-bunch_1']: THREE.Mesh
    ['balloons-bunch_2']: THREE.Mesh
    ['balloons-bunch_3']: THREE.Mesh
    ['bench-garden']: THREE.Mesh
    ['bench-garden002']: THREE.Mesh
    ['bench-wood_1']: THREE.Mesh
    ['bench-wood_2']: THREE.Mesh
    ['bench-wood_1']: THREE.Mesh
    ['bench-wood_2']: THREE.Mesh
    ['board-wire-papers']: THREE.Mesh
    ['board-wire-papers_1']: THREE.Mesh
    ['board-wire-papers_2']: THREE.Mesh
    ['board-wire-papers_3']: THREE.Mesh
    ['board-wire-papers_4']: THREE.Mesh
    ['board-wire-papers_5']: THREE.Mesh
    ['board-wire-papers']: THREE.Mesh
    ['board-wire-papers_1']: THREE.Mesh
    ['board-wire-papers_2']: THREE.Mesh
    ['board-wire-papers_3']: THREE.Mesh
    ['board-wire-papers_4']: THREE.Mesh
    ['board-wire-papers_5']: THREE.Mesh
    ['board-wire-papers']: THREE.Mesh
    ['board-wire-papers_1']: THREE.Mesh
    ['board-wire-papers_2']: THREE.Mesh
    ['board-wire-papers_3']: THREE.Mesh
    ['board-wire-papers_4']: THREE.Mesh
    ['board-wire-papers_5']: THREE.Mesh
    ['board-wire-papers']: THREE.Mesh
    ['board-wire-papers_1']: THREE.Mesh
    ['board-wire-papers_2']: THREE.Mesh
    ['board-wire-papers_3']: THREE.Mesh
    ['board-wire-papers_4']: THREE.Mesh
    ['board-wire-papers_5']: THREE.Mesh
    ['board-wire-papers']: THREE.Mesh
    ['board-wire-papers_1']: THREE.Mesh
    ['board-wire-papers_2']: THREE.Mesh
    ['board-wire-papers_3']: THREE.Mesh
    ['board-wire-papers_4']: THREE.Mesh
    ['board-wire-papers_5']: THREE.Mesh
    ['board-wire-papers001']: THREE.Mesh
    ['board-wire-papers001_1']: THREE.Mesh
    ['board-wire-papers001_2']: THREE.Mesh
    ['board-wire-papers001_3']: THREE.Mesh
    ['board-wire-papers001_4']: THREE.Mesh
    ['board-wire-papers001_5']: THREE.Mesh
    ['board-wire-papers']: THREE.Mesh
    ['board-wire-papers_1']: THREE.Mesh
    ['board-wire-papers_2']: THREE.Mesh
    ['board-wire-papers_3']: THREE.Mesh
    ['board-wire-papers_4']: THREE.Mesh
    ['board-wire-papers_5']: THREE.Mesh
    ['board-wire-papers001']: THREE.Mesh
    ['board-wire-papers001_1']: THREE.Mesh
    ['board-wire-papers001_2']: THREE.Mesh
    ['board-wire-papers001_3']: THREE.Mesh
    ['board-wire-papers001_4']: THREE.Mesh
    ['board-wire-papers001_5']: THREE.Mesh
    ['board-wire-papers']: THREE.Mesh
    ['board-wire-papers_1']: THREE.Mesh
    ['board-wire-papers_2']: THREE.Mesh
    ['board-wire-papers_3']: THREE.Mesh
    ['board-wire-papers_4']: THREE.Mesh
    ['board-wire-papers_5']: THREE.Mesh
    ['board-wire-papers001']: THREE.Mesh
    ['board-wire-papers001_1']: THREE.Mesh
    ['board-wire-papers001_2']: THREE.Mesh
    ['board-wire-papers001_3']: THREE.Mesh
    ['board-wire-papers001_4']: THREE.Mesh
    ['board-wire-papers001_5']: THREE.Mesh
    ['board-wire-papers001']: THREE.Mesh
    ['board-wire-papers001_1']: THREE.Mesh
    ['board-wire-papers001_2']: THREE.Mesh
    ['board-wire-papers001_3']: THREE.Mesh
    ['board-wire-papers001_4']: THREE.Mesh
    ['board-wire-papers001_5']: THREE.Mesh
    ['board-wire-papers']: THREE.Mesh
    ['board-wire-papers_1']: THREE.Mesh
    ['board-wire-papers_2']: THREE.Mesh
    ['board-wire-papers_3']: THREE.Mesh
    ['board-wire-papers_4']: THREE.Mesh
    ['board-wire-papers_5']: THREE.Mesh
    ['board-wire-papers001']: THREE.Mesh
    ['board-wire-papers001_1']: THREE.Mesh
    ['board-wire-papers001_2']: THREE.Mesh
    ['board-wire-papers001_3']: THREE.Mesh
    ['board-wire-papers001_4']: THREE.Mesh
    ['board-wire-papers001_5']: THREE.Mesh
    ['board-wire-papers']: THREE.Mesh
    ['board-wire-papers_1']: THREE.Mesh
    ['board-wire-papers_2']: THREE.Mesh
    ['board-wire-papers_3']: THREE.Mesh
    ['board-wire-papers_4']: THREE.Mesh
    ['board-wire-papers_5']: THREE.Mesh
    ['box-cabinet-open_1']: THREE.Mesh
    ['box-cabinet-open_2']: THREE.Mesh
    ['box-cabinet-open_1']: THREE.Mesh
    ['box-cabinet-open_2']: THREE.Mesh
    ['box-cabinet-open_1']: THREE.Mesh
    ['box-cabinet-open_2']: THREE.Mesh
    ['box-cabinet-open_1']: THREE.Mesh
    ['box-cabinet-open_2']: THREE.Mesh
    ['box-cabinet-open_1']: THREE.Mesh
    ['box-cabinet-open_2']: THREE.Mesh
    ['box-cabinet-open_1']: THREE.Mesh
    ['box-cabinet-open_2']: THREE.Mesh
    ['box-cabinet-open_1']: THREE.Mesh
    ['box-cabinet-open_2']: THREE.Mesh
    ['fence-shrub']: THREE.Mesh
    ['fence-shrub001']: THREE.Mesh
    ['fence-shrub002']: THREE.Mesh
    ['fence-shrub003']: THREE.Mesh
    ['fence-shrub004']: THREE.Mesh
    ['fence-shrub005']: THREE.Mesh
    ['fence-shrub006']: THREE.Mesh
    ['fence-shrub007']: THREE.Mesh
    ['fence-shrub008']: THREE.Mesh
    ['fence-shrub009']: THREE.Mesh
    ['fence-shrub010']: THREE.Mesh
    ['fence-shrub011']: THREE.Mesh
    ['fence-shrub012']: THREE.Mesh
    ['fence-shrub013']: THREE.Mesh
    fountain001: THREE.Mesh
    fountain001_1: THREE.Mesh
    fountain001_2: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['souvenir-stall_1']: THREE.Mesh
    ['souvenir-stall_2']: THREE.Mesh
    ['souvenir-stall_3']: THREE.Mesh
    ['souvenir-stall_4']: THREE.Mesh
    ['souvenir-stall_5']: THREE.Mesh
    ['souvenir-stall_6']: THREE.Mesh
    ['souvenir-stall_7']: THREE.Mesh
    ['souvenir-stall_8']: THREE.Mesh
    ['souvenir-stall_9']: THREE.Mesh
    ['souvenir-stall001_1']: THREE.Mesh
    ['souvenir-stall001_2']: THREE.Mesh
    ['souvenir-stall001_3']: THREE.Mesh
    ['souvenir-stall001_4']: THREE.Mesh
    ['souvenir-stall001_5']: THREE.Mesh
    ['souvenir-stall001_6']: THREE.Mesh
    ['souvenir-stall001_7']: THREE.Mesh
    ['souvenir-stall002_1']: THREE.Mesh
    ['souvenir-stall002_2']: THREE.Mesh
    ['souvenir-stall002_3']: THREE.Mesh
    ['souvenir-stall002_4']: THREE.Mesh
    ['souvenir-stall002_5']: THREE.Mesh
    ['souvenir-stall002_6']: THREE.Mesh
    ['souvenir-stall002_7']: THREE.Mesh
    ['stand-cotton-big']: THREE.Mesh
    ['stand-cotton-big_1']: THREE.Mesh
    ['stand-cotton-big_2']: THREE.Mesh
    ['stand-cotton-big_3']: THREE.Mesh
    ['stand-cotton-big_4']: THREE.Mesh
    ['stand-cotton-big_5']: THREE.Mesh
    ['stand-ice-cream_1']: THREE.Mesh
    ['stand-ice-cream_2']: THREE.Mesh
    ['stand-ice-cream_3']: THREE.Mesh
    ['stand-ice-cream_4']: THREE.Mesh
    ['stand-ice-cream_5']: THREE.Mesh
    ['stand-ice-cream_6']: THREE.Mesh
    ['stand-ice-cream_7']: THREE.Mesh
    ['stand-ice-cream_8']: THREE.Mesh
    ['stand-ice-cream_9']: THREE.Mesh
    ['airport-terminal_1']: THREE.Mesh
    ['airport-terminal_2']: THREE.Mesh
    ['airport-terminal_3']: THREE.Mesh
    ['airport-terminal_4']: THREE.Mesh
    ['airport-terminal_5']: THREE.Mesh
    ['tent-party009']: THREE.Mesh
    ['tent-party009_1']: THREE.Mesh
    ['tent-party005']: THREE.Mesh
    ['tent-party005_1']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
    ['board-wire-papers001']: THREE.Mesh
    ['board-wire-papers001_1']: THREE.Mesh
    ['board-wire-papers001_2']: THREE.Mesh
    ['board-wire-papers001_3']: THREE.Mesh
    ['board-wire-papers001_4']: THREE.Mesh
    ['board-wire-papers001_5']: THREE.Mesh
    ['light-string-color-big-2m-christmas']: THREE.Mesh
    ['light-string-color-big-2m-christmas_1']: THREE.Mesh
  }
  materials: {
    ['21 GREY LIGHT.001']: THREE.MeshPhysicalMaterial
    ['20 GREY.002']: THREE.MeshPhysicalMaterial
    ['BROWN-MEDIUM']: THREE.MeshPhysicalMaterial
    ['18 GREY-DARK.001']: THREE.MeshPhysicalMaterial
    ['26 RED-DARK']: THREE.MeshPhysicalMaterial
    ['28 ORANGE']: THREE.MeshPhysicalMaterial
    ['36 GREEN']: THREE.MeshPhysicalMaterial
    ['42 BLUE-DARK.001']: THREE.MeshPhysicalMaterial
    ['51 PINK-MEDIUM']: THREE.MeshPhysicalMaterial
    ['55 EMISSION-PURPLE']: THREE.MeshStandardMaterial
    ['62 EMISSION-YELLOW']: THREE.MeshStandardMaterial
    ['42 BLUE-DARK']: THREE.MeshPhysicalMaterial
    ['20 GREY.014']: THREE.MeshPhysicalMaterial
    ['36 GREEN.002']: THREE.MeshPhysicalMaterial
    ['43 BLUE-MEDIUM']: THREE.MeshPhysicalMaterial
    ['50 PINK-DARK']: THREE.MeshPhysicalMaterial
    ['44 BLUE']: THREE.MeshPhysicalMaterial
    ['17 GREY-DARKEST.009']: THREE.MeshPhysicalMaterial
    white: THREE.MeshStandardMaterial
    ['15 BROWN-WHITE']: THREE.MeshPhysicalMaterial
    ['25 RED-DARKEST']: THREE.MeshPhysicalMaterial
    ['13 BROWN-LIGHT']: THREE.MeshPhysicalMaterial
    spotlight: THREE.MeshPhysicalMaterial
    ['20 GREY.001']: THREE.MeshPhysicalMaterial
    ['26 RED-DARK.002']: THREE.MeshPhysicalMaterial
    ['58 WHITE.002']: THREE.MeshPhysicalMaterial
    ['34 GREEN-DARK']: THREE.MeshPhysicalMaterial
    ['12 BROWN.002']: THREE.MeshPhysicalMaterial
    ['11 BROWN-MEDIUM']: THREE.MeshPhysicalMaterial
    ['17 GREY-DARKEST.003']: THREE.MeshPhysicalMaterial
    ['27 RED']: THREE.MeshPhysicalMaterial
    ['44 BLUE.001']: THREE.MeshPhysicalMaterial
    ['53 PINK-LIGHT']: THREE.MeshStandardMaterial
    ['13 BROWN-LIGHT.001']: THREE.MeshPhysicalMaterial
    ['36 GREEN.001']: THREE.MeshPhysicalMaterial
    ['48 TRANSPARENT-BLUE.002']: THREE.MeshPhysicalMaterial
    ['61 EMISSION-ORANGE.005']: THREE.MeshStandardMaterial
    ['23 GREY-WHITE.006']: THREE.MeshPhysicalMaterial
    ['30 YELLOW.001']: THREE.MeshPhysicalMaterial
    ['43 BLUE-MEDIUM.002']: THREE.MeshPhysicalMaterial
    ['50 PINK-DARK.001']: THREE.MeshPhysicalMaterial
    ['45 BLUE-LIGHT']: THREE.MeshPhysicalMaterial
    ['56 TRANSPARENT-WHITE']: THREE.MeshPhysicalMaterial
    ['58 WHITE.003']: THREE.MeshPhysicalMaterial
    ['64 GLASS.002']: THREE.MeshPhysicalMaterial
    ['20 GREY.002']: THREE.MeshPhysicalMaterial
    ['17 GREY-DARKEST.009']: THREE.MeshPhysicalMaterial
    ['15 BROWN-WHITE']: THREE.MeshPhysicalMaterial
  }
}

export function EventsBuildings(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/events_bldgs.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="rug-circle"
          position={[36.512, 2.667, -66.496]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={3.336}>
          <mesh
            name="rug-circle_1"
            castShadow
            receiveShadow
            geometry={nodes['rug-circle_1'].geometry}
            material={materials['21 GREY LIGHT.001']}
          />
          <mesh
            name="rug-circle_2"
            castShadow
            receiveShadow
            geometry={nodes['rug-circle_2'].geometry}
            material={materials['20 GREY.002']}
          />
        </group>
        <group name="scifi-pot-low-palm001" position={[36.594, 2.667, -66.523]}>
          <mesh
            name="scifi-pot-low-palm"
            castShadow
            receiveShadow
            geometry={nodes['scifi-pot-low-palm'].geometry}
            material={materials['BROWN-MEDIUM']}
          />
          <mesh
            name="scifi-pot-low-palm_1"
            castShadow
            receiveShadow
            geometry={nodes['scifi-pot-low-palm_1'].geometry}
            material={materials['18 GREY-DARK.001']}
          />
          <mesh
            name="scifi-pot-low-palm_2"
            castShadow
            receiveShadow
            geometry={nodes['scifi-pot-low-palm_2'].geometry}
            material={materials['21 GREY LIGHT.001']}
          />
          <mesh
            name="scifi-pot-low-palm_3"
            castShadow
            receiveShadow
            geometry={nodes['scifi-pot-low-palm_3'].geometry}
            material={materials['26 RED-DARK']}
          />
          <mesh
            name="scifi-pot-low-palm_4"
            castShadow
            receiveShadow
            geometry={nodes['scifi-pot-low-palm_4'].geometry}
            material={materials['28 ORANGE']}
          />
          <mesh
            name="scifi-pot-low-palm_5"
            castShadow
            receiveShadow
            geometry={nodes['scifi-pot-low-palm_5'].geometry}
            material={materials['36 GREEN']}
          />
          <mesh
            name="scifi-pot-low-palm_6"
            castShadow
            receiveShadow
            geometry={nodes['scifi-pot-low-palm_6'].geometry}
            material={materials['42 BLUE-DARK.001']}
          />
          <mesh
            name="scifi-pot-low-palm_7"
            castShadow
            receiveShadow
            geometry={nodes['scifi-pot-low-palm_7'].geometry}
            material={materials['51 PINK-MEDIUM']}
          />
          <mesh
            name="scifi-pot-low-palm_8"
            castShadow
            receiveShadow
            geometry={nodes['scifi-pot-low-palm_8'].geometry}
            material={materials['55 EMISSION-PURPLE']}
          />
          <mesh
            name="scifi-pot-low-palm_9"
            castShadow
            receiveShadow
            geometry={nodes['scifi-pot-low-palm_9'].geometry}
            material={materials['62 EMISSION-YELLOW']}
          />
        </group>
        <group
          name="tent-party016"
          position={[28.419, 2.674, -53.387]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.282}>
          <mesh
            name="tent-party002"
            castShadow
            receiveShadow
            geometry={nodes['tent-party002'].geometry}
            material={materials['42 BLUE-DARK']}
          />
          <mesh
            name="tent-party002_1"
            castShadow
            receiveShadow
            geometry={nodes['tent-party002_1'].geometry}
            material={materials['20 GREY.014']}
          />
        </group>
        <group
          name="tent-party018"
          position={[44.061, 2.674, -36.804]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.282}>
          <mesh
            name="tent-party008_1"
            castShadow
            receiveShadow
            geometry={nodes['tent-party008_1'].geometry}
            material={materials['36 GREEN.002']}
          />
          <mesh
            name="tent-party008_2"
            castShadow
            receiveShadow
            geometry={nodes['tent-party008_2'].geometry}
            material={materials['20 GREY.014']}
          />
        </group>
        <group
          name="tent-party020"
          position={[44.061, 2.674, -53.387]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.282}>
          <mesh
            name="tent-party006"
            castShadow
            receiveShadow
            geometry={nodes['tent-party006'].geometry}
            material={materials['42 BLUE-DARK']}
          />
          <mesh
            name="tent-party006_1"
            castShadow
            receiveShadow
            geometry={nodes['tent-party006_1'].geometry}
            material={materials['20 GREY.014']}
          />
        </group>
        <group
          name="tent-party021"
          position={[44.061, 2.674, -45.448]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.282}>
          <mesh
            name="tent-party004"
            castShadow
            receiveShadow
            geometry={nodes['tent-party004'].geometry}
            material={materials['43 BLUE-MEDIUM']}
          />
          <mesh
            name="tent-party004_1"
            castShadow
            receiveShadow
            geometry={nodes['tent-party004_1'].geometry}
            material={materials['20 GREY.014']}
          />
        </group>
        <group
          name="tent-party024"
          position={[36.243, 2.674, -53.387]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.282}>
          <mesh
            name="tent-party001"
            castShadow
            receiveShadow
            geometry={nodes['tent-party001'].geometry}
            material={materials['50 PINK-DARK']}
          />
          <mesh
            name="tent-party001_1"
            castShadow
            receiveShadow
            geometry={nodes['tent-party001_1'].geometry}
            material={materials['20 GREY.014']}
          />
        </group>
        <group
          name="tent-party025"
          position={[36.243, 2.674, -45.448]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.282}>
          <mesh
            name="tent-party"
            castShadow
            receiveShadow
            geometry={nodes['tent-party'].geometry}
            material={materials['44 BLUE']}
          />
          <mesh
            name="tent-party_1"
            castShadow
            receiveShadow
            geometry={nodes['tent-party_1'].geometry}
            material={materials['20 GREY.014']}
          />
        </group>
        <group name="building-cinema" position={[36.853, 2.667, -84.024]}>
          <mesh
            name="building-cinema_1"
            castShadow
            receiveShadow
            geometry={nodes['building-cinema_1'].geometry}
            material={materials['17 GREY-DARKEST.009']}
          />
          <mesh
            name="building-cinema_2"
            castShadow
            receiveShadow
            geometry={nodes['building-cinema_2'].geometry}
            material={materials['62 EMISSION-YELLOW']}
          />
          <mesh
            name="building-cinema_3"
            castShadow
            receiveShadow
            geometry={nodes['building-cinema_3'].geometry}
            material={materials['21 GREY LIGHT.001']}
          />
          <mesh
            name="building-cinema_4"
            castShadow
            receiveShadow
            geometry={nodes['building-cinema_4'].geometry}
            material={materials.white}
          />
          <mesh
            name="building-cinema_5"
            castShadow
            receiveShadow
            geometry={nodes['building-cinema_5'].geometry}
            material={materials['15 BROWN-WHITE']}
          />
          <mesh
            name="building-cinema_6"
            castShadow
            receiveShadow
            geometry={nodes['building-cinema_6'].geometry}
            material={materials['25 RED-DARKEST']}
          />
          <mesh
            name="building-cinema_7"
            castShadow
            receiveShadow
            geometry={nodes['building-cinema_7'].geometry}
            material={materials['13 BROWN-LIGHT']}
          />
          <mesh
            name="building-cinema_8"
            castShadow
            receiveShadow
            geometry={nodes['building-cinema_8'].geometry}
            material={materials.spotlight}
          />
        </group>
        <group
          name="balloons-bunch"
          position={[36.243, 6.464, -45.405]}
          rotation={[0, 1.571, 0]}
          scale={2.592}>
          <mesh
            name="balloons-bunch_1"
            castShadow
            receiveShadow
            geometry={nodes['balloons-bunch_1'].geometry}
            material={materials['20 GREY.001']}
          />
          <mesh
            name="balloons-bunch_2"
            castShadow
            receiveShadow
            geometry={nodes['balloons-bunch_2'].geometry}
            material={materials['26 RED-DARK.002']}
          />
          <mesh
            name="balloons-bunch_3"
            castShadow
            receiveShadow
            geometry={nodes['balloons-bunch_3'].geometry}
            material={materials['58 WHITE.002']}
          />
        </group>
        <mesh
          name="bench-garden"
          castShadow
          receiveShadow
          geometry={nodes['bench-garden'].geometry}
          material={materials['34 GREEN-DARK']}
          position={[38.147, 2.667, -42.64]}
          scale={1.371}
        />
        <mesh
          name="bench-garden002"
          castShadow
          receiveShadow
          geometry={nodes['bench-garden002'].geometry}
          material={materials['34 GREEN-DARK']}
          position={[34.555, 2.667, -42.64]}
          scale={1.371}
        />
        <group
          name="bench-wood"
          position={[27.135, 2.667, -70.939]}
          rotation={[0, 0.832, 0]}
          scale={1.168}>
          <mesh
            name="bench-wood_1"
            castShadow
            receiveShadow
            geometry={nodes['bench-wood_1'].geometry}
            material={materials['12 BROWN.002']}
          />
          <mesh
            name="bench-wood_2"
            castShadow
            receiveShadow
            geometry={nodes['bench-wood_2'].geometry}
            material={materials['11 BROWN-MEDIUM']}
          />
        </group>
        <group
          name="bench-wood001"
          position={[45.8, 2.667, -70.939]}
          rotation={[0, -0.748, 0]}
          scale={1.168}>
          <mesh
            name="bench-wood_1"
            castShadow
            receiveShadow
            geometry={nodes['bench-wood_1'].geometry}
            material={materials['12 BROWN.002']}
          />
          <mesh
            name="bench-wood_2"
            castShadow
            receiveShadow
            geometry={nodes['bench-wood_2'].geometry}
            material={materials['11 BROWN-MEDIUM']}
          />
        </group>
        <group name="board-wire-papers002" position={[27.597, 4.038, -34.996]} scale={2.989}>
          <mesh
            name="board-wire-papers"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group name="board-wire-papers004" position={[27.597, 4.038, -43.786]} scale={2.989}>
          <mesh
            name="board-wire-papers"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group name="board-wire-papers006" position={[27.597, 4.038, -51.68]} scale={2.989}>
          <mesh
            name="board-wire-papers"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="board-wire-papers007"
          position={[45.821, 4.038, -35.983]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="board-wire-papers008"
          position={[26.594, 4.038, -52.55]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="board-wire-papers009"
          position={[26.594, 4.038, -54.372]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers001"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers001_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers001_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers001_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers001_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers001_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="board-wire-papers010"
          position={[26.594, 4.038, -44.588]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="board-wire-papers011"
          position={[26.594, 4.038, -46.41]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers001"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers001_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers001_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers001_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers001_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers001_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="board-wire-papers012"
          position={[26.594, 4.038, -35.843]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="board-wire-papers013"
          position={[26.594, 4.038, -37.665]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers001"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers001_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers001_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers001_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers001_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers001_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="board-wire-papers016"
          position={[45.821, 4.038, -37.805]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers001"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers001_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers001_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers001_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers001_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers001_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="board-wire-papers017"
          position={[45.821, 4.038, -44.642]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="board-wire-papers018"
          position={[45.821, 4.038, -46.465]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers001"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers001_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers001_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers001_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers001_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers001_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="board-wire-papers019"
          position={[45.821, 4.038, -52.521]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group
          name="box-cabinet-open"
          position={[46.971, 2.667, -32.698]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={4.344}>
          <mesh
            name="box-cabinet-open_1"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_1'].geometry}
            material={materials['13 BROWN-LIGHT.001']}
          />
          <mesh
            name="box-cabinet-open_2"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_2'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
        </group>
        <group
          name="box-cabinet-open001"
          position={[46.971, 2.667, -40.816]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={4.344}>
          <mesh
            name="box-cabinet-open_1"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_1'].geometry}
            material={materials['13 BROWN-LIGHT.001']}
          />
          <mesh
            name="box-cabinet-open_2"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_2'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
        </group>
        <group
          name="box-cabinet-open002"
          position={[46.971, 2.667, -49.055]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={4.344}>
          <mesh
            name="box-cabinet-open_1"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_1'].geometry}
            material={materials['13 BROWN-LIGHT.001']}
          />
          <mesh
            name="box-cabinet-open_2"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_2'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
        </group>
        <group
          name="box-cabinet-open003"
          position={[25.526, 2.667, -32.698]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={4.344}>
          <mesh
            name="box-cabinet-open_1"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_1'].geometry}
            material={materials['13 BROWN-LIGHT.001']}
          />
          <mesh
            name="box-cabinet-open_2"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_2'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
        </group>
        <group
          name="box-cabinet-open004"
          position={[25.526, 2.667, -40.816]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={4.344}>
          <mesh
            name="box-cabinet-open_1"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_1'].geometry}
            material={materials['13 BROWN-LIGHT.001']}
          />
          <mesh
            name="box-cabinet-open_2"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_2'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
        </group>
        <group
          name="box-cabinet-open005"
          position={[25.526, 2.667, -49.055]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={4.344}>
          <mesh
            name="box-cabinet-open_1"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_1'].geometry}
            material={materials['13 BROWN-LIGHT.001']}
          />
          <mesh
            name="box-cabinet-open_2"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_2'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
        </group>
        <group
          name="box-cabinet-open006"
          position={[29.884, 2.667, -28.253]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={4.344}>
          <mesh
            name="box-cabinet-open_1"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_1'].geometry}
            material={materials['13 BROWN-LIGHT.001']}
          />
          <mesh
            name="box-cabinet-open_2"
            castShadow
            receiveShadow
            geometry={nodes['box-cabinet-open_2'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
        </group>
        <mesh
          name="fence-shrub"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub'].geometry}
          material={materials['36 GREEN.001']}
          position={[25.545, 2.667, -47.147]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub001"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub001'].geometry}
          material={materials['36 GREEN.001']}
          position={[25.545, 2.667, -44.915]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub002"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub002'].geometry}
          material={materials['36 GREEN.001']}
          position={[25.545, 2.667, -42.719]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub003"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub003'].geometry}
          material={materials['36 GREEN.001']}
          position={[25.545, 2.667, -38.936]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub004"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub004'].geometry}
          material={materials['36 GREEN.001']}
          position={[25.545, 2.667, -36.704]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub005"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub005'].geometry}
          material={materials['36 GREEN.001']}
          position={[25.545, 2.667, -34.508]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub006"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub006'].geometry}
          material={materials['36 GREEN.001']}
          position={[46.943, 2.667, -47.147]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub007"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub007'].geometry}
          material={materials['36 GREEN.001']}
          position={[46.943, 2.667, -44.915]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub008"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub008'].geometry}
          material={materials['36 GREEN.001']}
          position={[46.943, 2.667, -42.719]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub009"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub009'].geometry}
          material={materials['36 GREEN.001']}
          position={[46.943, 2.667, -38.936]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub010"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub010'].geometry}
          material={materials['36 GREEN.001']}
          position={[46.943, 2.667, -36.704]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub011"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub011'].geometry}
          material={materials['36 GREEN.001']}
          position={[46.943, 2.667, -34.508]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="fence-shrub012"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub012'].geometry}
          material={materials['36 GREEN.001']}
          position={[33.715, 2.667, -28.449]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="fence-shrub013"
          castShadow
          receiveShadow
          geometry={nodes['fence-shrub013'].geometry}
          material={materials['36 GREEN.001']}
          position={[31.605, 2.667, -28.449]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <group name="fountain002" position={[36.333, 2.667, -39.694]} scale={0.798}>
          <mesh
            name="fountain001"
            castShadow
            receiveShadow
            geometry={nodes.fountain001.geometry}
            material={materials['20 GREY.001']}
          />
          <mesh
            name="fountain001_1"
            castShadow
            receiveShadow
            geometry={nodes.fountain001_1.geometry}
            material={materials['48 TRANSPARENT-BLUE.002']}
          />
          <mesh
            name="fountain001_2"
            castShadow
            receiveShadow
            geometry={nodes.fountain001_2.geometry}
            material={materials['58 WHITE.002']}
          />
        </group>
        <group name="lights-string002" position={[37.375, 5.294, -34.881]} scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group name="lights-string003" position={[29.419, 5.294, -34.881]} scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group name="lights-string006" position={[37.375, 5.294, -51.462]} scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group name="lights-string007" position={[29.419, 5.294, -51.462]} scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group
          name="lights-string008"
          position={[26.717, 5.294, -52.196]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group
          name="souvenir-stall"
          position={[36.263, 2.667, -34.605]}
          rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            name="souvenir-stall_1"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall_1'].geometry}
            material={materials['12 BROWN.002']}
          />
          <mesh
            name="souvenir-stall_2"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall_2'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="souvenir-stall_3"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall_3'].geometry}
            material={materials['20 GREY.001']}
          />
          <mesh
            name="souvenir-stall_4"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall_4'].geometry}
            material={materials['23 GREY-WHITE.006']}
          />
          <mesh
            name="souvenir-stall_5"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall_5'].geometry}
            material={materials['30 YELLOW.001']}
          />
          <mesh
            name="souvenir-stall_6"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall_6'].geometry}
            material={materials['43 BLUE-MEDIUM.002']}
          />
          <mesh
            name="souvenir-stall_7"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall_7'].geometry}
            material={materials['50 PINK-DARK.001']}
          />
          <mesh
            name="souvenir-stall_8"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall_8'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="souvenir-stall_9"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall_9'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group
          name="souvenir-stall001"
          position={[46.989, 2.667, -29.487]}
          rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            name="souvenir-stall001_1"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall001_1'].geometry}
            material={materials['12 BROWN.002']}
          />
          <mesh
            name="souvenir-stall001_2"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall001_2'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="souvenir-stall001_3"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall001_3'].geometry}
            material={materials['20 GREY.001']}
          />
          <mesh
            name="souvenir-stall001_4"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall001_4'].geometry}
            material={materials['30 YELLOW.001']}
          />
          <mesh
            name="souvenir-stall001_5"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall001_5'].geometry}
            material={materials['43 BLUE-MEDIUM.002']}
          />
          <mesh
            name="souvenir-stall001_6"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall001_6'].geometry}
            material={materials['36 GREEN']}
          />
          <mesh
            name="souvenir-stall001_7"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall001_7'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group name="souvenir-stall002" position={[36.452, 2.667, -27.971]}>
          <mesh
            name="souvenir-stall002_1"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall002_1'].geometry}
            material={materials['12 BROWN.002']}
          />
          <mesh
            name="souvenir-stall002_2"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall002_2'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="souvenir-stall002_3"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall002_3'].geometry}
            material={materials['20 GREY.001']}
          />
          <mesh
            name="souvenir-stall002_4"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall002_4'].geometry}
            material={materials['30 YELLOW.001']}
          />
          <mesh
            name="souvenir-stall002_5"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall002_5'].geometry}
            material={materials['43 BLUE-MEDIUM.002']}
          />
          <mesh
            name="souvenir-stall002_6"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall002_6'].geometry}
            material={materials['42 BLUE-DARK.001']}
          />
          <mesh
            name="souvenir-stall002_7"
            castShadow
            receiveShadow
            geometry={nodes['souvenir-stall002_7'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group
          name="stand-cotton-big001"
          position={[24.137, 2.715, -51.721]}
          rotation={[-Math.PI, 0.804, -Math.PI]}
          scale={1.217}>
          <mesh
            name="stand-cotton-big"
            castShadow
            receiveShadow
            geometry={nodes['stand-cotton-big'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="stand-cotton-big_1"
            castShadow
            receiveShadow
            geometry={nodes['stand-cotton-big_1'].geometry}
            material={materials['20 GREY.001']}
          />
          <mesh
            name="stand-cotton-big_2"
            castShadow
            receiveShadow
            geometry={nodes['stand-cotton-big_2'].geometry}
            material={materials['23 GREY-WHITE.006']}
          />
          <mesh
            name="stand-cotton-big_3"
            castShadow
            receiveShadow
            geometry={nodes['stand-cotton-big_3'].geometry}
            material={materials['30 YELLOW.001']}
          />
          <mesh
            name="stand-cotton-big_4"
            castShadow
            receiveShadow
            geometry={nodes['stand-cotton-big_4'].geometry}
            material={materials['45 BLUE-LIGHT']}
          />
          <mesh
            name="stand-cotton-big_5"
            castShadow
            receiveShadow
            geometry={nodes['stand-cotton-big_5'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
        </group>
        <group
          name="stand-ice-cream"
          position={[47.687, 2.715, -58.976]}
          rotation={[0, 0.201, 0]}
          scale={1.31}>
          <mesh
            name="stand-ice-cream_1"
            castShadow
            receiveShadow
            geometry={nodes['stand-ice-cream_1'].geometry}
            material={materials['12 BROWN.002']}
          />
          <mesh
            name="stand-ice-cream_2"
            castShadow
            receiveShadow
            geometry={nodes['stand-ice-cream_2'].geometry}
            material={materials['13 BROWN-LIGHT.001']}
          />
          <mesh
            name="stand-ice-cream_3"
            castShadow
            receiveShadow
            geometry={nodes['stand-ice-cream_3'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="stand-ice-cream_4"
            castShadow
            receiveShadow
            geometry={nodes['stand-ice-cream_4'].geometry}
            material={materials['20 GREY.001']}
          />
          <mesh
            name="stand-ice-cream_5"
            castShadow
            receiveShadow
            geometry={nodes['stand-ice-cream_5'].geometry}
            material={materials['23 GREY-WHITE.006']}
          />
          <mesh
            name="stand-ice-cream_6"
            castShadow
            receiveShadow
            geometry={nodes['stand-ice-cream_6'].geometry}
            material={materials['30 YELLOW.001']}
          />
          <mesh
            name="stand-ice-cream_7"
            castShadow
            receiveShadow
            geometry={nodes['stand-ice-cream_7'].geometry}
            material={materials['43 BLUE-MEDIUM.002']}
          />
          <mesh
            name="stand-ice-cream_8"
            castShadow
            receiveShadow
            geometry={nodes['stand-ice-cream_8'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="stand-ice-cream_9"
            castShadow
            receiveShadow
            geometry={nodes['stand-ice-cream_9'].geometry}
            material={materials['56 TRANSPARENT-WHITE']}
          />
        </group>
        <group name="airport-terminal" position={[-15.325, 3.528, -77.23]} scale={0.861}>
          <mesh
            name="airport-terminal_1"
            castShadow
            receiveShadow
            geometry={nodes['airport-terminal_1'].geometry}
            material={materials['58 WHITE.003']}
          />
          <mesh
            name="airport-terminal_2"
            castShadow
            receiveShadow
            geometry={nodes['airport-terminal_2'].geometry}
            material={materials['64 GLASS.002']}
          />
          <mesh
            name="airport-terminal_3"
            castShadow
            receiveShadow
            geometry={nodes['airport-terminal_3'].geometry}
            material={materials['20 GREY.002']}
          />
          <mesh
            name="airport-terminal_4"
            castShadow
            receiveShadow
            geometry={nodes['airport-terminal_4'].geometry}
            material={materials['17 GREY-DARKEST.009']}
          />
          <mesh
            name="airport-terminal_5"
            castShadow
            receiveShadow
            geometry={nodes['airport-terminal_5'].geometry}
            material={materials['15 BROWN-WHITE']}
          />
        </group>
        <group
          name="tent-party008"
          position={[28.419, 2.674, -36.804]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.282}>
          <mesh
            name="tent-party009"
            castShadow
            receiveShadow
            geometry={nodes['tent-party009'].geometry}
            material={materials['42 BLUE-DARK']}
          />
          <mesh
            name="tent-party009_1"
            castShadow
            receiveShadow
            geometry={nodes['tent-party009_1'].geometry}
            material={materials['20 GREY.014']}
          />
        </group>
        <group
          name="tent-party017"
          position={[28.419, 2.674, -45.448]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.282}>
          <mesh
            name="tent-party005"
            castShadow
            receiveShadow
            geometry={nodes['tent-party005'].geometry}
            material={materials['51 PINK-MEDIUM']}
          />
          <mesh
            name="tent-party005_1"
            castShadow
            receiveShadow
            geometry={nodes['tent-party005_1'].geometry}
            material={materials['20 GREY.014']}
          />
        </group>
        <group name="lights-string" position={[36.55, 5.294, -27.067]} scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group name="lights-string004" position={[37.375, 5.294, -43.475]} scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group name="lights-string005" position={[29.419, 5.294, -43.475]} scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group
          name="lights-string009"
          position={[26.717, 5.294, -43.795]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group
          name="lights-string011"
          position={[45.727, 5.294, -52.196]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group
          name="lights-string012"
          position={[45.727, 5.294, -43.795]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group
          name="lights-string013"
          position={[45.727, 5.294, -35.5]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
        <group
          name="board-wire-papers020"
          position={[45.821, 4.038, -54.343]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.989}>
          <mesh
            name="board-wire-papers001"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="board-wire-papers001_1"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_1'].geometry}
            material={materials['27 RED']}
          />
          <mesh
            name="board-wire-papers001_2"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_2'].geometry}
            material={materials['44 BLUE.001']}
          />
          <mesh
            name="board-wire-papers001_3"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_3'].geometry}
            material={materials['53 PINK-LIGHT']}
          />
          <mesh
            name="board-wire-papers001_4"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_4'].geometry}
            material={materials['58 WHITE.002']}
          />
          <mesh
            name="board-wire-papers001_5"
            castShadow
            receiveShadow
            geometry={nodes['board-wire-papers001_5'].geometry}
            material={materials['20 GREY.001']}
          />
        </group>
        <group name="lights-string001" position={[42.185, 5.294, -27.067]} scale={2.816}>
          <mesh
            name="light-string-color-big-2m-christmas"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas'].geometry}
            material={materials['17 GREY-DARKEST.003']}
          />
          <mesh
            name="light-string-color-big-2m-christmas_1"
            castShadow
            receiveShadow
            geometry={nodes['light-string-color-big-2m-christmas_1'].geometry}
            material={materials['61 EMISSION-ORANGE.005']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/events_bldgs.glb')
