/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, memo, Suspense } from "react";
import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";
import type { ThreeElements } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    ["building-restaurant001"]: THREE.Mesh;
    ["building-restaurant001_1"]: THREE.Mesh;
    ["building-restaurant001_2"]: THREE.Mesh;
    ["building-restaurant001_3"]: THREE.Mesh;
    ["building-restaurant001_4"]: THREE.Mesh;
    ["building-restaurant001_5"]: THREE.Mesh;
    ["building-restaurant001_6"]: THREE.Mesh;
    ["building-restaurant001_7"]: THREE.Mesh;
    ["building-restaurant001_8"]: THREE.Mesh;
    ["building-restaurant001_9"]: THREE.Mesh;
    ["building-cafe"]: THREE.Mesh;
    ["building-cafe_1"]: THREE.Mesh;
    ["building-cafe_2"]: THREE.Mesh;
    ["building-cafe_3"]: THREE.Mesh;
    ["building-cafe_4"]: THREE.Mesh;
    ["building-cafe_5"]: THREE.Mesh;
    ["building-cafe_6"]: THREE.Mesh;
    ["building-cafe_7"]: THREE.Mesh;
    ["building-tattoo"]: THREE.Mesh;
    ["building-tattoo_1"]: THREE.Mesh;
    ["building-tattoo_2"]: THREE.Mesh;
    ["building-tattoo_3"]: THREE.Mesh;
    ["building-tattoo_4"]: THREE.Mesh;
    ["building-tattoo_5"]: THREE.Mesh;
    ["building-tattoo_6"]: THREE.Mesh;
    ["building-tattoo_7"]: THREE.Mesh;
    ["building-tattoo_8"]: THREE.Mesh;
    ["building-shop-china"]: THREE.Mesh;
    ["building-shop-china_1"]: THREE.Mesh;
    ["building-shop-china_2"]: THREE.Mesh;
    ["building-shop-china_3"]: THREE.Mesh;
    ["building-shop-china_4"]: THREE.Mesh;
    ["building-shop-china_5"]: THREE.Mesh;
    ["building-shop-china_6"]: THREE.Mesh;
    ["building-shop-china_7"]: THREE.Mesh;
    ["building-shop-china_8"]: THREE.Mesh;
    ["building-shop-china_9"]: THREE.Mesh;
    ["building-mall_1"]: THREE.Mesh;
    ["building-mall_2"]: THREE.Mesh;
    ["building-mall_3"]: THREE.Mesh;
    ["building-mall_4"]: THREE.Mesh;
    ["building-mall_5"]: THREE.Mesh;
    ["building-mall_6"]: THREE.Mesh;
    ["building-mall_7"]: THREE.Mesh;
    ["building-mall_8"]: THREE.Mesh;
  };
  materials: {
    ["17 GREY-DARKEST.007"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK.006"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.007"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.008"]: THREE.MeshPhysicalMaterial;
    ["61 EMISSION-ORANGE.002"]: THREE.MeshStandardMaterial;
    ["21 GREY LIGHT.004"]: THREE.MeshPhysicalMaterial;
    ["58 WHITE.006"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE.004"]: THREE.MeshPhysicalMaterial;
    ["5 SKIN-LIGHT.001"]: THREE.MeshPhysicalMaterial;
    ["9 BROWN-DARKEST.004"]: THREE.MeshPhysicalMaterial;
    ["35 GREEN-MEDIUM.002"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.009"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.002"]: THREE.MeshPhysicalMaterial;
    ["58 WHITE.003"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE"]: THREE.MeshPhysicalMaterial;
    ["10 BROWN-DARK"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.002"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.001"]: THREE.MeshPhysicalMaterial;
    ["5 SKIN-LIGHT"]: THREE.MeshPhysicalMaterial;
    ["10 BROWN-DARK"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.009"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.002"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.001"]: THREE.MeshPhysicalMaterial;
    ["23 GREY-WHITE.001"]: THREE.MeshPhysicalMaterial;
    ["58 WHITE.003"]: THREE.MeshPhysicalMaterial;
    ["61 EMISSION-ORANGE.003"]: THREE.MeshStandardMaterial;
    ["64 GLASS.002"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK"]: THREE.MeshPhysicalMaterial;
    ["30 YELLOW"]: THREE.MeshPhysicalMaterial;
    ["36 GREEN"]: THREE.MeshPhysicalMaterial;
    ["4 SKIN"]: THREE.MeshPhysicalMaterial;
    ["48 TRANSPARENT-BLUE.001"]: THREE.MeshPhysicalMaterial;
  };
};

type ModelFile = {
  _type: "modelFile";
  fileName?: string;
  filePath?: string;
  fileUrl?: string;
};

type ShopsBuildingsProps = ThreeElements["group"] & {
  modelFile?: ModelFile;
};

function ShopsBuildingsContent({ modelFile, ...props }: ShopsBuildingsProps) {
  const modelPath = modelFile?.fileUrl || "/models/shops-buildings.glb";
  const { nodes, materials } = useGLTF(modelPath) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group
        position={[92.457, 2.767, 26.261]}
        rotation={[Math.PI, 0, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-restaurant001"].geometry}
          material={materials["17 GREY-DARKEST.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-restaurant001_1"].geometry}
          material={materials["26 RED-DARK.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-restaurant001_2"].geometry}
          material={materials["64 GLASS.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-restaurant001_3"].geometry}
          material={materials["20 GREY.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-restaurant001_4"].geometry}
          material={materials["61 EMISSION-ORANGE.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-restaurant001_5"].geometry}
          material={materials["21 GREY LIGHT.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-restaurant001_6"].geometry}
          material={materials["58 WHITE.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-restaurant001_7"].geometry}
          material={materials["15 BROWN-WHITE.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-restaurant001_8"].geometry}
          material={materials["5 SKIN-LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-restaurant001_9"].geometry}
          material={materials["9 BROWN-DARKEST.004"]}
        />
      </group>
      <group position={[105.044, 2.667, 2.604]} rotation={[0, -1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe"].geometry}
          material={materials["35 GREEN-MEDIUM.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_1"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_2"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_3"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_4"].geometry}
          material={materials["15 BROWN-WHITE"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_5"].geometry}
          material={materials["10 BROWN-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_6"].geometry}
          material={materials["64 GLASS.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_7"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
      </group>
      <group position={[92.199, 2.667, 2.995]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo"].geometry}
          material={materials["5 SKIN-LIGHT"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_1"].geometry}
          material={materials["10 BROWN-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_2"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_3"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_4"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_5"].geometry}
          material={materials["23 GREY-WHITE.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_6"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_7"].geometry}
          material={materials["61 EMISSION-ORANGE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_8"].geometry}
          material={materials["64 GLASS.002"]}
        />
      </group>
      <group
        position={[79.974, 2.667, 25.761]}
        rotation={[Math.PI, 0, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china"].geometry}
          material={materials["15 BROWN-WHITE"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_1"].geometry}
          material={materials["10 BROWN-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_2"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_3"].geometry}
          material={materials["26 RED-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_4"].geometry}
          material={materials["30 YELLOW"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_5"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_6"].geometry}
          material={materials["64 GLASS.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_7"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_8"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_9"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
      </group>
      <group
        position={[104.981, 2.906, 25.761]}
        rotation={[Math.PI, 0, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china"].geometry}
          material={materials["15 BROWN-WHITE"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_1"].geometry}
          material={materials["10 BROWN-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_2"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_3"].geometry}
          material={materials["26 RED-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_4"].geometry}
          material={materials["30 YELLOW"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_5"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_6"].geometry}
          material={materials["64 GLASS.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_7"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_8"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_9"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
      </group>
      <group position={[79.974, 2.906, 3.148]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china"].geometry}
          material={materials["15 BROWN-WHITE"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_1"].geometry}
          material={materials["10 BROWN-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_2"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_3"].geometry}
          material={materials["26 RED-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_4"].geometry}
          material={materials["30 YELLOW"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_5"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_6"].geometry}
          material={materials["64 GLASS.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_7"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_8"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-shop-china_9"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
      </group>
      <group position={[97.333, 2.667, -23.155]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-mall_1"].geometry}
          material={materials["64 GLASS.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-mall_2"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-mall_3"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-mall_4"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-mall_5"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-mall_6"].geometry}
          material={materials["4 SKIN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-mall_7"].geometry}
          material={materials["15 BROWN-WHITE"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-mall_8"].geometry}
          material={materials["48 TRANSPARENT-BLUE.001"]}
        />
      </group>
      <group position={[73.9, 2.667, -30.126]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe"].geometry}
          material={materials["35 GREEN-MEDIUM.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_1"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_2"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_3"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_4"].geometry}
          material={materials["15 BROWN-WHITE"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_5"].geometry}
          material={materials["10 BROWN-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_6"].geometry}
          material={materials["64 GLASS.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-cafe_7"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
      </group>
      <group position={[74.291, 2.667, -17.281]} rotation={[0, 1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo"].geometry}
          material={materials["5 SKIN-LIGHT"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_1"].geometry}
          material={materials["10 BROWN-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_2"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_3"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_4"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_5"].geometry}
          material={materials["23 GREY-WHITE.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_6"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_7"].geometry}
          material={materials["61 EMISSION-ORANGE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_8"].geometry}
          material={materials["64 GLASS.002"]}
        />
      </group>
    </group>
  );
}

function ShopsBuildings(props: ShopsBuildingsProps) {
  const modelPath = props.modelFile?.fileUrl || "/models/shops-buildings.glb";

  useEffect(() => {
    useGLTF.preload(modelPath);
  }, [modelPath]);

  return (
    <Suspense fallback={null}>
      <ShopsBuildingsContent {...props} />
    </Suspense>
  );
}

// Export both named and default
export { ShopsBuildings };
export default memo(ShopsBuildings);
