/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'
type GLTFResult = GLTF & {
  nodes: {
    ['tile-mainroad-road-intersection-t-nb']: THREE.Mesh
    ['tile-mainroad-road-intersection-t-nb_1']: THREE.Mesh
    ['tile-mainroad-road-intersection-t-nb_2']: THREE.Mesh
    ['tile-mainroad-road-intersection-t-nb_3']: THREE.Mesh
    ['tile-mainroad-road-intersection-t-nb_4']: THREE.Mesh
    ['tile-road-intersection-t-nb']: THREE.Mesh
    ['tile-road-intersection-t-nb_1']: THREE.Mesh
    ['tile-road-intersection-t-nb_2']: THREE.Mesh
    ['tile-road-intersection-t-nb_3']: THREE.Mesh
    ['tile-road-intersection-t-nb004']: THREE.Mesh
    ['tile-road-intersection-t-nb004_1']: THREE.Mesh
    ['tile-road-intersection-t-nb004_2']: THREE.Mesh
    ['tile-road-intersection-t-nb004_3']: THREE.Mesh
    ['tile-road-straight-nb001']: THREE.Mesh
    ['tile-road-straight-nb001_1']: THREE.Mesh
    ['tile-road-straight-nb001_2']: THREE.Mesh
    ['tile-road-straight-nb']: THREE.Mesh
    ['tile-road-straight-nb_1']: THREE.Mesh
    ['tile-road-straight-nb_2']: THREE.Mesh
    ['tile-road-straight-nb001']: THREE.Mesh
    ['tile-road-straight-nb001_1']: THREE.Mesh
    ['tile-road-straight-nb001_2']: THREE.Mesh
    ['tile-road-straight-nb']: THREE.Mesh
    ['tile-road-straight-nb_1']: THREE.Mesh
    ['tile-road-straight-nb_2']: THREE.Mesh
    ['tile-plain-nb073']: THREE.Mesh
    ['tile-plain-nb074']: THREE.Mesh
    ['tile-plain-nb075']: THREE.Mesh
    ['tile-plain-nb076']: THREE.Mesh
    ['tile-road-intersection-nb']: THREE.Mesh
    ['tile-road-intersection-nb_1']: THREE.Mesh
    ['tile-road-intersection-nb_2']: THREE.Mesh
    ['tile-road-intersection-nb_3']: THREE.Mesh
  }
  materials: {
    ['18 GREY-DARK.001']: THREE.MeshPhysicalMaterial
    ['21 GREY LIGHT.001']: THREE.MeshPhysicalMaterial
    ['23 GREY-WHITE.001']: THREE.MeshPhysicalMaterial
    ['30 YELLOW']: THREE.MeshPhysicalMaterial
    ['14 BROWN-LIGHTEST']: THREE.MeshPhysicalMaterial
    ['18 GREY-DARK']: THREE.MeshPhysicalMaterial
    ['21 GREY LIGHT']: THREE.MeshPhysicalMaterial
    ['23 GREY-WHITE']: THREE.MeshPhysicalMaterial
    ['14 BROWN-LIGHTEST.006']: THREE.MeshPhysicalMaterial
    ['14 BROWN-LIGHTEST.002']: THREE.MeshPhysicalMaterial
  }
}

export function GroundCompany(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/road-zone-company.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="tile-mainroad-road-intersection-t-nb002"
          position={[30, 2.667, 45]}
          rotation={[0, 1.571, 0]}>
          <mesh
            name="tile-mainroad-road-intersection-t-nb"
            castShadow
            receiveShadow
            geometry={nodes['tile-mainroad-road-intersection-t-nb'].geometry}
            material={materials['18 GREY-DARK.001']}
          />
          <mesh
            name="tile-mainroad-road-intersection-t-nb_1"
            castShadow
            receiveShadow
            geometry={nodes['tile-mainroad-road-intersection-t-nb_1'].geometry}
            material={materials['21 GREY LIGHT.001']}
          />
          <mesh
            name="tile-mainroad-road-intersection-t-nb_2"
            castShadow
            receiveShadow
            geometry={nodes['tile-mainroad-road-intersection-t-nb_2'].geometry}
            material={materials['23 GREY-WHITE.001']}
          />
          <mesh
            name="tile-mainroad-road-intersection-t-nb_3"
            castShadow
            receiveShadow
            geometry={nodes['tile-mainroad-road-intersection-t-nb_3'].geometry}
            material={materials['30 YELLOW']}
          />
          <mesh
            name="tile-mainroad-road-intersection-t-nb_4"
            castShadow
            receiveShadow
            geometry={nodes['tile-mainroad-road-intersection-t-nb_4'].geometry}
            material={materials['14 BROWN-LIGHTEST']}
          />
        </group>
        <group name="tile-road-intersection-t-nb002" position={[30, 2.667, -15]}>
          <mesh
            name="tile-road-intersection-t-nb"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-t-nb'].geometry}
            material={materials['18 GREY-DARK.001']}
          />
          <mesh
            name="tile-road-intersection-t-nb_1"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-t-nb_1'].geometry}
            material={materials['21 GREY LIGHT.001']}
          />
          <mesh
            name="tile-road-intersection-t-nb_2"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-t-nb_2'].geometry}
            material={materials['23 GREY-WHITE.001']}
          />
          <mesh
            name="tile-road-intersection-t-nb_3"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-t-nb_3'].geometry}
            material={materials['14 BROWN-LIGHTEST']}
          />
        </group>
        <group
          name="tile-road-intersection-t-nb003"
          position={[-60, 2.667, 15]}
          rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            name="tile-road-intersection-t-nb004"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-t-nb004'].geometry}
            material={materials['18 GREY-DARK']}
          />
          <mesh
            name="tile-road-intersection-t-nb004_1"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-t-nb004_1'].geometry}
            material={materials['21 GREY LIGHT']}
          />
          <mesh
            name="tile-road-intersection-t-nb004_2"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-t-nb004_2'].geometry}
            material={materials['23 GREY-WHITE']}
          />
          <mesh
            name="tile-road-intersection-t-nb004_3"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-t-nb004_3'].geometry}
            material={materials['14 BROWN-LIGHTEST']}
          />
        </group>
        <group
          name="tile-road-straight-nb004"
          position={[30, 2.667, 15]}
          rotation={[Math.PI, 0, Math.PI]}>
          <mesh
            name="tile-road-straight-nb001"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb001'].geometry}
            material={materials['14 BROWN-LIGHTEST']}
          />
          <mesh
            name="tile-road-straight-nb001_1"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb001_1'].geometry}
            material={materials['18 GREY-DARK.001']}
          />
          <mesh
            name="tile-road-straight-nb001_2"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb001_2'].geometry}
            material={materials['21 GREY LIGHT']}
          />
        </group>
        <group
          name="tile-road-straight-nb006"
          position={[-30, 2.667, -15]}
          rotation={[0, Math.PI / 2, 0]}>
          <mesh
            name="tile-road-straight-nb"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb'].geometry}
            material={materials['14 BROWN-LIGHTEST.006']}
          />
          <mesh
            name="tile-road-straight-nb_1"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb_1'].geometry}
            material={materials['18 GREY-DARK.001']}
          />
          <mesh
            name="tile-road-straight-nb_2"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb_2'].geometry}
            material={materials['21 GREY LIGHT.001']}
          />
        </group>
        <group
          name="tile-road-straight-nb007"
          position={[-60, 2.667, 45]}
          rotation={[Math.PI, 0, Math.PI]}>
          <mesh
            name="tile-road-straight-nb001"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb001'].geometry}
            material={materials['14 BROWN-LIGHTEST']}
          />
          <mesh
            name="tile-road-straight-nb001_1"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb001_1'].geometry}
            material={materials['18 GREY-DARK.001']}
          />
          <mesh
            name="tile-road-straight-nb001_2"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb001_2'].geometry}
            material={materials['21 GREY LIGHT']}
          />
        </group>
        <group
          name="tile-road-straight-nb013"
          position={[0, 2.667, -15]}
          rotation={[0, Math.PI / 2, 0]}>
          <mesh
            name="tile-road-straight-nb"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb'].geometry}
            material={materials['14 BROWN-LIGHTEST.006']}
          />
          <mesh
            name="tile-road-straight-nb_1"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb_1'].geometry}
            material={materials['18 GREY-DARK.001']}
          />
          <mesh
            name="tile-road-straight-nb_2"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-straight-nb_2'].geometry}
            material={materials['21 GREY LIGHT.001']}
          />
        </group>
        <mesh
          name="tile-plain-nb073"
          castShadow
          receiveShadow
          geometry={nodes['tile-plain-nb073'].geometry}
          material={materials['14 BROWN-LIGHTEST.002']}
          position={[-30, 2.667, 45]}
        />
        <mesh
          name="tile-plain-nb074"
          castShadow
          receiveShadow
          geometry={nodes['tile-plain-nb074'].geometry}
          material={materials['14 BROWN-LIGHTEST.002']}
          position={[-30, 2.667, 15]}
        />
        <mesh
          name="tile-plain-nb075"
          castShadow
          receiveShadow
          geometry={nodes['tile-plain-nb075'].geometry}
          material={materials['14 BROWN-LIGHTEST.002']}
          position={[0, 2.667, 45]}
        />
        <mesh
          name="tile-plain-nb076"
          castShadow
          receiveShadow
          geometry={nodes['tile-plain-nb076'].geometry}
          material={materials['14 BROWN-LIGHTEST.002']}
          position={[0, 2.667, 15]}
        />
        <group name="tile-road-intersection-nb003" position={[-60, 2.667, -15]}>
          <mesh
            name="tile-road-intersection-nb"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-nb'].geometry}
            material={materials['18 GREY-DARK.001']}
          />
          <mesh
            name="tile-road-intersection-nb_1"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-nb_1'].geometry}
            material={materials['21 GREY LIGHT.001']}
          />
          <mesh
            name="tile-road-intersection-nb_2"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-nb_2'].geometry}
            material={materials['23 GREY-WHITE.001']}
          />
          <mesh
            name="tile-road-intersection-nb_3"
            castShadow
            receiveShadow
            geometry={nodes['tile-road-intersection-nb_3'].geometry}
            material={materials['14 BROWN-LIGHTEST']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/road-zone-company.glb')
