/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";
import { useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    ["asphalt-single002"]: THREE.Mesh;
    ["tile-plain-nb095"]: THREE.Mesh;
    ["tile-plain-nb079"]: THREE.Mesh;
    ["tile-plain-nb082"]: THREE.Mesh;
    ["tile-plain-nb068"]: THREE.Mesh;
    ["tile-hill-valley-nb001"]: THREE.Mesh;
    ["tile-hill-valley-nb"]: THREE.Mesh;
    ["tile-hill-nb001"]: THREE.Mesh;
    ["tile-hill-nb"]: THREE.Mesh;
    ["tile-hill-curve-nb001"]: THREE.Mesh;
    ["tile-hill-curve-nb"]: THREE.Mesh;
    ["tile-hill-corner-nb002"]: THREE.Mesh;
    ["tile-hill-corner-nb001"]: THREE.Mesh;
    ["tile-hill-corner-nb"]: THREE.Mesh;
    ["tile-golf-sand-nb_1"]: THREE.Mesh;
    ["tile-golf-sand-nb_2"]: THREE.Mesh;
    ["tile-golf-green-nb_1"]: THREE.Mesh;
    ["tile-golf-green-nb_2"]: THREE.Mesh;
    ["tile-golf-green-nb_3"]: THREE.Mesh;
    ["tile-plain-nb026"]: THREE.Mesh;
  };
  materials: {
    ["18 GREY-DARK"]: THREE.MeshPhysicalMaterial;
    ["14 BROWN-LIGHTEST"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT"]: THREE.MeshPhysicalMaterial;
    ["36 GREEN.001"]: THREE.MeshPhysicalMaterial;
    ["14 BROWN-LIGHTEST.001"]: THREE.MeshPhysicalMaterial;
    ["9 BROWN-DARKEST.001"]: THREE.MeshPhysicalMaterial;
    ["37 GREEN-LIGHT.002"]: THREE.MeshPhysicalMaterial;
  };
};

export function GroundResort(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/road-zone-resort.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="asphalt-single002"
        castShadow
        receiveShadow
        geometry={nodes["asphalt-single002"].geometry}
        material={materials["18 GREY-DARK"]}
        position={[-90, 2.667, -15]}
      />
      <mesh
        name="tile-plain-nb095"
        castShadow
        receiveShadow
        geometry={nodes["tile-plain-nb095"].geometry}
        material={materials["14 BROWN-LIGHTEST"]}
        position={[-149.939, 2.667, -15]}
      />
      <mesh
        name="tile-plain-nb079"
        castShadow
        receiveShadow
        geometry={nodes["tile-plain-nb079"].geometry}
        material={materials["14 BROWN-LIGHTEST"]}
        position={[-90, 2.667, -45]}
      />
      <mesh
        name="tile-plain-nb082"
        castShadow
        receiveShadow
        geometry={nodes["tile-plain-nb082"].geometry}
        material={materials["21 GREY LIGHT"]}
        position={[-90, 2.667, -75]}
      />
      <mesh
        name="tile-plain-nb068"
        castShadow
        receiveShadow
        geometry={nodes["tile-plain-nb068"].geometry}
        material={materials["36 GREEN.001"]}
        position={[-90, 2.667, -105]}
      />
      <mesh
        name="tile-hill-valley-nb001"
        castShadow
        receiveShadow
        geometry={nodes["tile-hill-valley-nb001"].geometry}
        material={materials["36 GREEN.001"]}
        position={[-210, 2.68, -105]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="tile-hill-valley-nb"
        castShadow
        receiveShadow
        geometry={nodes["tile-hill-valley-nb"].geometry}
        material={materials["36 GREEN.001"]}
        position={[-150, 2.68, -105]}
      />
      <mesh
        name="tile-hill-nb001"
        castShadow
        receiveShadow
        geometry={nodes["tile-hill-nb001"].geometry}
        material={materials["36 GREEN.001"]}
        position={[-180, 2.68, -45]}
      />
      <mesh
        name="tile-hill-nb"
        castShadow
        receiveShadow
        geometry={nodes["tile-hill-nb"].geometry}
        material={materials["36 GREEN.001"]}
        position={[-150, 2.68, -45]}
      />
      <mesh
        name="tile-hill-curve-nb001"
        castShadow
        receiveShadow
        geometry={nodes["tile-hill-curve-nb001"].geometry}
        material={materials["36 GREEN.001"]}
        position={[-210, 2.68, -75]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        name="tile-hill-curve-nb"
        castShadow
        receiveShadow
        geometry={nodes["tile-hill-curve-nb"].geometry}
        material={materials["36 GREEN.001"]}
        position={[-150, 2.68, -75]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        name="tile-hill-corner-nb002"
        castShadow
        receiveShadow
        geometry={nodes["tile-hill-corner-nb002"].geometry}
        material={materials["36 GREEN.001"]}
        position={[-210, 2.68, -45]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        name="tile-hill-corner-nb001"
        castShadow
        receiveShadow
        geometry={nodes["tile-hill-corner-nb001"].geometry}
        material={materials["36 GREEN.001"]}
        position={[-120, 2.68, -45]}
      />
      <mesh
        name="tile-hill-corner-nb"
        castShadow
        receiveShadow
        geometry={nodes["tile-hill-corner-nb"].geometry}
        material={materials["36 GREEN.001"]}
        position={[-120, 2.68, -105]}
      />
      <group name="tile-golf-sand-nb" position={[-180, 8.68, -105]}>
        <mesh
          name="tile-golf-sand-nb_1"
          castShadow
          receiveShadow
          geometry={nodes["tile-golf-sand-nb_1"].geometry}
          material={materials["36 GREEN.001"]}
        />
        <mesh
          name="tile-golf-sand-nb_2"
          castShadow
          receiveShadow
          geometry={nodes["tile-golf-sand-nb_2"].geometry}
          material={materials["14 BROWN-LIGHTEST.001"]}
        />
      </group>
      <group name="tile-golf-green-nb" position={[-180, 8.68, -75]}>
        <mesh
          name="tile-golf-green-nb_1"
          castShadow
          receiveShadow
          geometry={nodes["tile-golf-green-nb_1"].geometry}
          material={materials["36 GREEN.001"]}
        />
        <mesh
          name="tile-golf-green-nb_2"
          castShadow
          receiveShadow
          geometry={nodes["tile-golf-green-nb_2"].geometry}
          material={materials["9 BROWN-DARKEST.001"]}
        />
        <mesh
          name="tile-golf-green-nb_3"
          castShadow
          receiveShadow
          geometry={nodes["tile-golf-green-nb_3"].geometry}
          material={materials["37 GREEN-LIGHT.002"]}
        />
      </group>
      <mesh
        name="tile-plain-nb026"
        castShadow
        receiveShadow
        geometry={nodes["tile-plain-nb026"].geometry}
        material={materials["14 BROWN-LIGHTEST"]}
        position={[-90, 2.667, -135]}
      />
    </group>
  );
}

useGLTF.preload("/models/road-zone-resort.glb");
