/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeElements } from "@react-three/fiber";
type GLTFResult = GLTF & {
  nodes: {
    ["tile-plain-nb069"]: THREE.Mesh;
    ["tile-plain-nb066"]: THREE.Mesh;
    ["tile-mainroad-straight-crosswalk-nb002"]: THREE.Mesh;
    ["tile-mainroad-straight-crosswalk-nb002_1"]: THREE.Mesh;
    ["tile-mainroad-straight-crosswalk-nb002_2"]: THREE.Mesh;
    ["tile-mainroad-straight-crosswalk-nb002_3"]: THREE.Mesh;
    ["tile-mainroad-straight-crosswalk-nb002_4"]: THREE.Mesh;
    ["tile-mainroad-straight-crosswalk-nb003_1"]: THREE.Mesh;
    ["tile-mainroad-straight-crosswalk-nb003_2"]: THREE.Mesh;
    ["tile-mainroad-straight-crosswalk-nb003_3"]: THREE.Mesh;
    ["tile-mainroad-straight-crosswalk-nb003_4"]: THREE.Mesh;
    ["tile-mainroad-straight-crosswalk-nb003_5"]: THREE.Mesh;
    ["tile-road-mainroad-intersection-t-nb"]: THREE.Mesh;
    ["tile-road-mainroad-intersection-t-nb_1"]: THREE.Mesh;
    ["tile-road-mainroad-intersection-t-nb_2"]: THREE.Mesh;
    ["tile-road-mainroad-intersection-t-nb_3"]: THREE.Mesh;
    ["tile-road-mainroad-intersection-t-nb_4"]: THREE.Mesh;
    ["tile-road-curve-nb"]: THREE.Mesh;
    ["tile-road-curve-nb_1"]: THREE.Mesh;
    ["tile-road-curve-nb_2"]: THREE.Mesh;
    ["tile-mainroad-straight-crosswalk-nb003"]: THREE.Mesh;
    ["tile-road-straight-nb"]: THREE.Mesh;
    ["tile-road-straight-nb_1"]: THREE.Mesh;
    ["tile-road-straight-nb_2"]: THREE.Mesh;
    ["tile-road-straight-nb"]: THREE.Mesh;
    ["tile-road-straight-nb_1"]: THREE.Mesh;
    ["tile-road-straight-nb_2"]: THREE.Mesh;
    ["tile-plain-nb"]: THREE.Mesh;
    Material2061: THREE.Mesh;
    Material2001: THREE.Mesh;
    Material2002: THREE.Mesh;
    Material2003: THREE.Mesh;
    Material2004: THREE.Mesh;
    Material2005: THREE.Mesh;
    Material2006: THREE.Mesh;
    Material2007: THREE.Mesh;
    Material2008: THREE.Mesh;
    Material2009: THREE.Mesh;
    Material2010: THREE.Mesh;
    Material2011: THREE.Mesh;
    Material2012: THREE.Mesh;
    Material2013: THREE.Mesh;
    Material2014: THREE.Mesh;
    Material2015: THREE.Mesh;
  };
  materials: {
    ["14 BROWN-LIGHTEST.002"]: THREE.MeshPhysicalMaterial;
    ["18 GREY-DARK.001"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.001"]: THREE.MeshPhysicalMaterial;
    ["23 GREY-WHITE.001"]: THREE.MeshPhysicalMaterial;
    ["30 YELLOW"]: THREE.MeshPhysicalMaterial;
    ["14 BROWN-LIGHTEST"]: THREE.MeshPhysicalMaterial;
    ["18 GREY-DARK"]: THREE.MeshPhysicalMaterial;
    ["14 BROWN-LIGHTEST.006"]: THREE.MeshPhysicalMaterial;
    ["material_3.002"]: THREE.MeshStandardMaterial;
  };
};

export function GroundShops(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/road-zone-shops.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="tile-plain-nb069"
          geometry={nodes["tile-plain-nb069"].geometry}
          material={materials["14 BROWN-LIGHTEST.002"]}
          position={[90, 2.667, 15]}
        />
        <mesh
          name="tile-plain-nb066"
          geometry={nodes["tile-plain-nb066"].geometry}
          material={materials["14 BROWN-LIGHTEST.002"]}
          position={[90, 2.667, -15]}
        />
        <group
          name="tile-mainroad-straight-crosswalk-nb010"
          position={[90, 2.667, 45]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <mesh
            name="tile-mainroad-straight-crosswalk-nb002"
            geometry={nodes["tile-mainroad-straight-crosswalk-nb002"].geometry}
            material={materials["18 GREY-DARK.001"]}
          />
          <mesh
            name="tile-mainroad-straight-crosswalk-nb002_1"
            geometry={
              nodes["tile-mainroad-straight-crosswalk-nb002_1"].geometry
            }
            material={materials["21 GREY LIGHT.001"]}
          />
          <mesh
            name="tile-mainroad-straight-crosswalk-nb002_2"
            geometry={
              nodes["tile-mainroad-straight-crosswalk-nb002_2"].geometry
            }
            material={materials["23 GREY-WHITE.001"]}
          />
          <mesh
            name="tile-mainroad-straight-crosswalk-nb002_3"
            geometry={
              nodes["tile-mainroad-straight-crosswalk-nb002_3"].geometry
            }
            material={materials["30 YELLOW"]}
          />
          <mesh
            name="tile-mainroad-straight-crosswalk-nb002_4"
            geometry={
              nodes["tile-mainroad-straight-crosswalk-nb002_4"].geometry
            }
            material={materials["14 BROWN-LIGHTEST"]}
          />
        </group>
        <group
          name="tile-mainroad-straight-crosswalk-nb001"
          position={[60, 2.667, 45]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <mesh
            name="tile-mainroad-straight-crosswalk-nb003_1"
            geometry={
              nodes["tile-mainroad-straight-crosswalk-nb003_1"].geometry
            }
            material={materials["18 GREY-DARK"]}
          />
          <mesh
            name="tile-mainroad-straight-crosswalk-nb003_2"
            geometry={
              nodes["tile-mainroad-straight-crosswalk-nb003_2"].geometry
            }
            material={materials["21 GREY LIGHT.001"]}
          />
          <mesh
            name="tile-mainroad-straight-crosswalk-nb003_3"
            geometry={
              nodes["tile-mainroad-straight-crosswalk-nb003_3"].geometry
            }
            material={materials["23 GREY-WHITE.001"]}
          />
          <mesh
            name="tile-mainroad-straight-crosswalk-nb003_4"
            geometry={
              nodes["tile-mainroad-straight-crosswalk-nb003_4"].geometry
            }
            material={materials["30 YELLOW"]}
          />
          <mesh
            name="tile-mainroad-straight-crosswalk-nb003_5"
            geometry={
              nodes["tile-mainroad-straight-crosswalk-nb003_5"].geometry
            }
            material={materials["14 BROWN-LIGHTEST"]}
          />
        </group>
        <group
          name="tile-road-mainroad-intersection-t-nb002"
          position={[120, 2.667, 45]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="tile-road-mainroad-intersection-t-nb"
            geometry={nodes["tile-road-mainroad-intersection-t-nb"].geometry}
            material={materials["18 GREY-DARK.001"]}
          />
          <mesh
            name="tile-road-mainroad-intersection-t-nb_1"
            geometry={nodes["tile-road-mainroad-intersection-t-nb_1"].geometry}
            material={materials["21 GREY LIGHT.001"]}
          />
          <mesh
            name="tile-road-mainroad-intersection-t-nb_2"
            geometry={nodes["tile-road-mainroad-intersection-t-nb_2"].geometry}
            material={materials["23 GREY-WHITE.001"]}
          />
          <mesh
            name="tile-road-mainroad-intersection-t-nb_3"
            geometry={nodes["tile-road-mainroad-intersection-t-nb_3"].geometry}
            material={materials["30 YELLOW"]}
          />
          <mesh
            name="tile-road-mainroad-intersection-t-nb_4"
            geometry={nodes["tile-road-mainroad-intersection-t-nb_4"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
        </group>
        <group
          name="tile-road-curve-nb003"
          position={[60, 2.667, -15]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="tile-road-curve-nb"
            geometry={nodes["tile-road-curve-nb"].geometry}
            material={materials["21 GREY LIGHT.001"]}
          />
          <mesh
            name="tile-road-curve-nb_1"
            geometry={nodes["tile-road-curve-nb_1"].geometry}
            material={materials["18 GREY-DARK.001"]}
          />
          <mesh
            name="tile-road-curve-nb_2"
            geometry={nodes["tile-road-curve-nb_2"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
        </group>
        <mesh
          name="tile-mainroad-straight-crosswalk-nb003"
          geometry={nodes["tile-mainroad-straight-crosswalk-nb003"].geometry}
          material={materials["21 GREY LIGHT.001"]}
          position={[60, 2.667, 45]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <group
          name="tile-road-straight-nb009"
          position={[120, 2.667, 15]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="tile-road-straight-nb"
            geometry={nodes["tile-road-straight-nb"].geometry}
            material={materials["14 BROWN-LIGHTEST.006"]}
          />
          <mesh
            name="tile-road-straight-nb_1"
            geometry={nodes["tile-road-straight-nb_1"].geometry}
            material={materials["18 GREY-DARK.001"]}
          />
          <mesh
            name="tile-road-straight-nb_2"
            geometry={nodes["tile-road-straight-nb_2"].geometry}
            material={materials["21 GREY LIGHT.001"]}
          />
        </group>
        <group
          name="tile-road-straight-nb010"
          position={[120, 2.667, -15]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="tile-road-straight-nb"
            geometry={nodes["tile-road-straight-nb"].geometry}
            material={materials["14 BROWN-LIGHTEST.006"]}
          />
          <mesh
            name="tile-road-straight-nb_1"
            geometry={nodes["tile-road-straight-nb_1"].geometry}
            material={materials["18 GREY-DARK.001"]}
          />
          <mesh
            name="tile-road-straight-nb_2"
            geometry={nodes["tile-road-straight-nb_2"].geometry}
            material={materials["21 GREY LIGHT.001"]}
          />
        </group>
        <mesh
          name="tile-plain-nb"
          geometry={nodes["tile-plain-nb"].geometry}
          material={materials["18 GREY-DARK"]}
          position={[60, 2.667, 15]}
        />
        <mesh
          name="Material2061"
          geometry={nodes.Material2061.geometry}
          material={materials["material_3.002"]}
          position={[46.89, 2.667, 18.82]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2001"
          geometry={nodes.Material2001.geometry}
          material={materials["material_3.002"]}
          position={[46.89, 2.667, 16.032]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2002"
          geometry={nodes.Material2002.geometry}
          material={materials["material_3.002"]}
          position={[46.89, 2.667, 13.244]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2003"
          geometry={nodes.Material2003.geometry}
          material={materials["material_3.002"]}
          position={[46.89, 2.667, 10.456]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2004"
          geometry={nodes.Material2004.geometry}
          material={materials["material_3.002"]}
          position={[46.89, 2.667, 7.668]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2005"
          geometry={nodes.Material2005.geometry}
          material={materials["material_3.002"]}
          position={[46.89, 2.667, 21.607]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2006"
          geometry={nodes.Material2006.geometry}
          material={materials["material_3.002"]}
          position={[46.89, 2.667, 4.88]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2007"
          geometry={nodes.Material2007.geometry}
          material={materials["material_3.002"]}
          position={[62.047, 2.667, 18.82]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2008"
          geometry={nodes.Material2008.geometry}
          material={materials["material_3.002"]}
          position={[62.047, 2.667, 16.032]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2009"
          geometry={nodes.Material2009.geometry}
          material={materials["material_3.002"]}
          position={[62.047, 2.667, 13.244]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2010"
          geometry={nodes.Material2010.geometry}
          material={materials["material_3.002"]}
          position={[62.047, 2.667, 10.456]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2011"
          geometry={nodes.Material2011.geometry}
          material={materials["material_3.002"]}
          position={[62.047, 2.667, 7.668]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2012"
          geometry={nodes.Material2012.geometry}
          material={materials["material_3.002"]}
          position={[62.047, 2.667, 21.607]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2013"
          geometry={nodes.Material2013.geometry}
          material={materials["material_3.002"]}
          position={[62.047, 2.667, 4.88]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2014"
          geometry={nodes.Material2014.geometry}
          material={materials["material_3.002"]}
          position={[46.89, 2.667, 24.395]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
        <mesh
          name="Material2015"
          geometry={nodes.Material2015.geometry}
          material={materials["material_3.002"]}
          position={[62.047, 2.667, 24.395]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.026}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/road-zone-shops.glb");
