/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeElements } from "@react-three/fiber";
type GLTFResult = GLTF & {
  nodes: {
    ["road-sign-green001_1"]: THREE.Mesh;
    ["road-sign-green001_2"]: THREE.Mesh;
    ["road-sign-green001_3"]: THREE.Mesh;
    ["palm-high"]: THREE.Mesh;
    ["palm-high_1"]: THREE.Mesh;
    ["palm-high"]: THREE.Mesh;
    ["palm-high_1"]: THREE.Mesh;
    ["palm-high"]: THREE.Mesh;
    ["palm-high_1"]: THREE.Mesh;
    ["palm-high"]: THREE.Mesh;
    ["palm-high_1"]: THREE.Mesh;
    ["palm-high"]: THREE.Mesh;
    ["palm-high_1"]: THREE.Mesh;
    ["palm-high"]: THREE.Mesh;
    ["palm-high_1"]: THREE.Mesh;
    ["palm-high"]: THREE.Mesh;
    ["palm-high_1"]: THREE.Mesh;
    ["palm-high"]: THREE.Mesh;
    ["palm-high_1"]: THREE.Mesh;
    ["palm-high"]: THREE.Mesh;
    ["palm-high_1"]: THREE.Mesh;
    ["industry-storage001_1"]: THREE.Mesh;
    ["industry-storage001_2"]: THREE.Mesh;
    ["industry-storage001_3"]: THREE.Mesh;
    ["industry-storage001_4"]: THREE.Mesh;
    ["industry-storage001_5"]: THREE.Mesh;
    ["industry-storage001_6"]: THREE.Mesh;
    ["industry-storage001_7"]: THREE.Mesh;
    ["building-policestation001_1"]: THREE.Mesh;
    ["building-policestation001_2"]: THREE.Mesh;
    ["building-policestation001_3"]: THREE.Mesh;
    ["building-policestation001_4"]: THREE.Mesh;
    ["building-policestation001_5"]: THREE.Mesh;
    ["building-policestation001_6"]: THREE.Mesh;
    ["building-policestation001_7"]: THREE.Mesh;
    ["building-policestation001_8"]: THREE.Mesh;
    ["building-policestation001_1"]: THREE.Mesh;
    ["building-policestation001_2"]: THREE.Mesh;
    ["building-policestation001_3"]: THREE.Mesh;
    ["building-policestation001_4"]: THREE.Mesh;
    ["building-policestation001_5"]: THREE.Mesh;
    ["building-policestation001_6"]: THREE.Mesh;
    ["building-policestation001_7"]: THREE.Mesh;
    ["building-policestation001_8"]: THREE.Mesh;
    ["building-policestation-garage001_1"]: THREE.Mesh;
    ["building-policestation-garage001_2"]: THREE.Mesh;
    ["building-policestation-garage001_3"]: THREE.Mesh;
    ["building-policestation-garage001_4"]: THREE.Mesh;
    ["building-policestation-garage001_5"]: THREE.Mesh;
    ["building-policestation-garage001_6"]: THREE.Mesh;
    ["building-policestation-garage001_1"]: THREE.Mesh;
    ["building-policestation-garage001_2"]: THREE.Mesh;
    ["building-policestation-garage001_3"]: THREE.Mesh;
    ["building-policestation-garage001_4"]: THREE.Mesh;
    ["building-policestation-garage001_5"]: THREE.Mesh;
    ["building-policestation-garage001_6"]: THREE.Mesh;
    ["building-policestation-garage001_1"]: THREE.Mesh;
    ["building-policestation-garage001_2"]: THREE.Mesh;
    ["building-policestation-garage001_3"]: THREE.Mesh;
    ["building-policestation-garage001_4"]: THREE.Mesh;
    ["building-policestation-garage001_5"]: THREE.Mesh;
    ["building-policestation-garage001_6"]: THREE.Mesh;
    ["building-carwash001"]: THREE.Mesh;
    ["building-carwash001_1"]: THREE.Mesh;
    ["building-carwash001_2"]: THREE.Mesh;
    ["building-carwash001_3"]: THREE.Mesh;
    ["building-carwash001_4"]: THREE.Mesh;
    ["building-carwash001_5"]: THREE.Mesh;
    ["building-carwash001_6"]: THREE.Mesh;
    ["industry-storage001_1"]: THREE.Mesh;
    ["industry-storage001_2"]: THREE.Mesh;
    ["industry-storage001_3"]: THREE.Mesh;
    ["industry-storage001_4"]: THREE.Mesh;
    ["industry-storage001_5"]: THREE.Mesh;
    ["industry-storage001_6"]: THREE.Mesh;
    ["industry-storage001_7"]: THREE.Mesh;
    ["building-policestation001_1"]: THREE.Mesh;
    ["building-policestation001_2"]: THREE.Mesh;
    ["building-policestation001_3"]: THREE.Mesh;
    ["building-policestation001_4"]: THREE.Mesh;
    ["building-policestation001_5"]: THREE.Mesh;
    ["building-policestation001_6"]: THREE.Mesh;
    ["building-policestation001_7"]: THREE.Mesh;
    ["building-policestation001_8"]: THREE.Mesh;
    ["building-policestation001_1"]: THREE.Mesh;
    ["building-policestation001_2"]: THREE.Mesh;
    ["building-policestation001_3"]: THREE.Mesh;
    ["building-policestation001_4"]: THREE.Mesh;
    ["building-policestation001_5"]: THREE.Mesh;
    ["building-policestation001_6"]: THREE.Mesh;
    ["building-policestation001_7"]: THREE.Mesh;
    ["building-policestation001_8"]: THREE.Mesh;
    ["palm-high"]: THREE.Mesh;
    ["palm-high_1"]: THREE.Mesh;
    ["rock-large"]: THREE.Mesh;
    ["cactus-big_1"]: THREE.Mesh;
    ["cactus-big_2"]: THREE.Mesh;
    ["rock-large001"]: THREE.Mesh;
    ["rock-large002"]: THREE.Mesh;
    ["cactus-big_1"]: THREE.Mesh;
    ["cactus-big_2"]: THREE.Mesh;
    Stage: THREE.Mesh;
    ["tile-road-straight-nb003_1"]: THREE.Mesh;
    ["tile-road-straight-nb003_2"]: THREE.Mesh;
    ["tile-road-straight-nb003_3"]: THREE.Mesh;
    ["tile-road-straight-nb004"]: THREE.Mesh;
    ["tile-road-straight-nb004_1"]: THREE.Mesh;
    ["tile-road-straight-nb004_2"]: THREE.Mesh;
    ["building-policestation002_1"]: THREE.Mesh;
    ["building-policestation002_2"]: THREE.Mesh;
    ["airport-hangar001"]: THREE.Mesh;
    ["airport-hangar001_1"]: THREE.Mesh;
    ["airport-hangar001_2"]: THREE.Mesh;
    ["airport-hangar001_3"]: THREE.Mesh;
    ["airport-hangar001_4"]: THREE.Mesh;
    ["airport-hangar001_5"]: THREE.Mesh;
    ["military-headquarters001_1"]: THREE.Mesh;
    ["military-headquarters001_2"]: THREE.Mesh;
    ["military-headquarters001_3"]: THREE.Mesh;
    ["military-headquarters001_4"]: THREE.Mesh;
    ["military-headquarters001_5"]: THREE.Mesh;
    ["military-headquarters001_6"]: THREE.Mesh;
    ["military-headquarters001_7"]: THREE.Mesh;
    ["building-policestation002_1"]: THREE.Mesh;
    ["building-policestation002_2"]: THREE.Mesh;
  };
  materials: {
    ["20 GREY.004"]: THREE.MeshPhysicalMaterial;
    ["59 EMISSION-WHITE.001"]: THREE.MeshStandardMaterial;
    ["58 WHITE.004"]: THREE.MeshPhysicalMaterial;
    ["BROWN-MEDIUM.001"]: THREE.MeshPhysicalMaterial;
    ["GREEN-LIGHT.001"]: THREE.MeshPhysicalMaterial;

    ["grey light"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.006"]: THREE.MeshPhysicalMaterial;
    ["18 GREY-DARK.003"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.004"]: THREE.MeshPhysicalMaterial;
    ["58 WHITE.005"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.004"]: THREE.MeshPhysicalMaterial;
    ["58 WHITE.005"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.006"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.004"]: THREE.MeshPhysicalMaterial;
    Green: THREE.MeshPhysicalMaterial;
    ["grey light"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK.003"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.004"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE.002"]: THREE.MeshPhysicalMaterial;
    ["35 GREEN-MEDIUM.001"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.007"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE.002"]: THREE.MeshPhysicalMaterial;
    ["14 BROWN-LIGHTEST"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK"]: THREE.MeshPhysicalMaterial;
    ["10 BROWN-DARK"]: THREE.MeshPhysicalMaterial;
    ["BROWN-LIGHTEST"]: THREE.MeshPhysicalMaterial;
    ["18 GREY-DARK"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT"]: THREE.MeshPhysicalMaterial;
    ["14 BROWN-LIGHTEST.002"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE.001"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.002"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.003"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.003"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.005"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.004"]: THREE.MeshPhysicalMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export function CompanySubSceneModel(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF("/models/POICompany.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="road-sign-green001"
          position={[5.314, 2.174, -4.249]}
          scale={0.205}
        >
          <mesh
            name="road-sign-green001_1"
            geometry={nodes["road-sign-green001_1"].geometry}
            material={materials["20 GREY.004"]}
          />
          <mesh
            name="road-sign-green001_2"
            geometry={nodes["road-sign-green001_2"].geometry}
            material={materials["59 EMISSION-WHITE.001"]}
          />
          <mesh
            name="road-sign-green001_3"
            geometry={nodes["road-sign-green001_3"].geometry}
            material={materials["58 WHITE.004"]}
          />
        </group>
        <group
          name="palm-high042"
          position={[-5.969, 1.524, -4.694]}
          scale={0.175}
        >
          <mesh
            name="palm-high"
            geometry={nodes["palm-high"].geometry}
            material={materials["BROWN-MEDIUM.001"]}
          />
          <mesh
            name="palm-high_1"
            geometry={nodes["palm-high_1"].geometry}
            material={materials["GREEN-LIGHT.001"]}
          />
        </group>
        <group
          name="palm-high037"
          position={[2.266, 1.524, -6.739]}
          scale={0.175}
        >
          <mesh
            name="palm-high"
            geometry={nodes["palm-high"].geometry}
            material={materials["BROWN-MEDIUM.001"]}
          />
          <mesh
            name="palm-high_1"
            geometry={nodes["palm-high_1"].geometry}
            material={materials["GREEN-LIGHT.001"]}
          />
        </group>
        <group
          name="palm-high036"
          position={[6.365, 1.524, -6.739]}
          scale={0.175}
        >
          <mesh
            name="palm-high"
            geometry={nodes["palm-high"].geometry}
            material={materials["BROWN-MEDIUM.001"]}
          />
          <mesh
            name="palm-high_1"
            geometry={nodes["palm-high_1"].geometry}
            material={materials["GREEN-LIGHT.001"]}
          />
        </group>
        <group
          name="palm-high035"
          position={[-5.969, 1.524, -6.739]}
          scale={0.175}
        >
          <mesh
            name="palm-high"
            geometry={nodes["palm-high"].geometry}
            material={materials["BROWN-MEDIUM.001"]}
          />
          <mesh
            name="palm-high_1"
            geometry={nodes["palm-high_1"].geometry}
            material={materials["GREEN-LIGHT.001"]}
          />
        </group>
        <group
          name="palm-high034"
          position={[-2.103, 1.524, -6.739]}
          scale={0.175}
        >
          <mesh
            name="palm-high"
            geometry={nodes["palm-high"].geometry}
            material={materials["BROWN-MEDIUM.001"]}
          />
          <mesh
            name="palm-high_1"
            geometry={nodes["palm-high_1"].geometry}
            material={materials["GREEN-LIGHT.001"]}
          />
        </group>
        <group
          name="palm-high033"
          position={[-6.97, 1.524, 5.234]}
          scale={0.175}
        >
          <mesh
            name="palm-high"
            geometry={nodes["palm-high"].geometry}
            material={materials["BROWN-MEDIUM.001"]}
          />
          <mesh
            name="palm-high_1"
            geometry={nodes["palm-high_1"].geometry}
            material={materials["GREEN-LIGHT.001"]}
          />
        </group>
        <group
          name="palm-high031"
          position={[-1.113, 1.524, 5.234]}
          scale={0.175}
        >
          <mesh
            name="palm-high"
            geometry={nodes["palm-high"].geometry}
            material={materials["BROWN-MEDIUM.001"]}
          />
          <mesh
            name="palm-high_1"
            geometry={nodes["palm-high_1"].geometry}
            material={materials["GREEN-LIGHT.001"]}
          />
        </group>
        <group
          name="palm-high025"
          position={[2.892, 1.524, 5.867]}
          scale={0.175}
        >
          <mesh
            name="palm-high"
            geometry={nodes["palm-high"].geometry}
            material={materials["BROWN-MEDIUM.001"]}
          />
          <mesh
            name="palm-high_1"
            geometry={nodes["palm-high_1"].geometry}
            material={materials["GREEN-LIGHT.001"]}
          />
        </group>
        <group
          name="palm-high024"
          position={[6.475, 1.524, 7.236]}
          scale={0.175}
        >
          <mesh
            name="palm-high"
            geometry={nodes["palm-high"].geometry}
            material={materials["BROWN-MEDIUM.001"]}
          />
          <mesh
            name="palm-high_1"
            geometry={nodes["palm-high_1"].geometry}
            material={materials["GREEN-LIGHT.001"]}
          />
        </group>
        <group
          name="industry-storage"
          position={[4.163, 1.524, 4.986]}
          scale={0.175}
        >
          <mesh
            name="industry-storage001_1"
            geometry={nodes["industry-storage001_1"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="industry-storage001_2"
            geometry={nodes["industry-storage001_2"].geometry}
            material={materials["grey light"]}
          />
          <mesh
            name="industry-storage001_3"
            geometry={nodes["industry-storage001_3"].geometry}
            material={materials["20 GREY.006"]}
          />
          <mesh
            name="industry-storage001_4"
            geometry={nodes["industry-storage001_4"].geometry}
            material={materials["18 GREY-DARK.003"]}
          />
          <mesh
            name="industry-storage001_5"
            geometry={nodes["industry-storage001_5"].geometry}
            material={materials["64 GLASS.004"]}
          />
          <mesh
            name="industry-storage001_6"
            geometry={nodes["industry-storage001_6"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="industry-storage001_7"
            geometry={nodes["industry-storage001_7"].geometry}
            material={materials["17 GREY-DARKEST.004"]}
          />
        </group>
        <group
          name="building-policestation006"
          position={[6.038, 1.524, 5.5]}
          rotation={[0, 1.571, 0]}
          scale={0.175}
        >
          <mesh
            name="building-policestation001_1"
            geometry={nodes["building-policestation001_1"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="building-policestation001_2"
            geometry={nodes["building-policestation001_2"].geometry}
            material={materials["20 GREY.006"]}
          />
          <mesh
            name="building-policestation001_3"
            geometry={nodes["building-policestation001_3"].geometry}
            material={materials["17 GREY-DARKEST.004"]}
          />
          <mesh
            name="building-policestation001_4"
            geometry={nodes["building-policestation001_4"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="building-policestation001_5"
            geometry={nodes["building-policestation001_5"].geometry}
            material={materials["grey light"]}
          />
          <mesh
            name="building-policestation001_6"
            geometry={nodes["building-policestation001_6"].geometry}
            material={materials["26 RED-DARK.003"]}
          />
          <mesh
            name="building-policestation001_7"
            geometry={nodes["building-policestation001_7"].geometry}
            material={materials["64 GLASS.004"]}
          />
          <mesh
            name="building-policestation001_8"
            geometry={nodes["building-policestation001_8"].geometry}
            material={materials["15 BROWN-WHITE.002"]}
          />
        </group>
        <group
          name="building-policestation005"
          position={[6.038, 1.524, 3.758]}
          rotation={[0, 1.571, 0]}
          scale={0.175}
        >
          <mesh
            name="building-policestation001_1"
            geometry={nodes["building-policestation001_1"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="building-policestation001_2"
            geometry={nodes["building-policestation001_2"].geometry}
            material={materials["20 GREY.006"]}
          />
          <mesh
            name="building-policestation001_3"
            geometry={nodes["building-policestation001_3"].geometry}
            material={materials["17 GREY-DARKEST.004"]}
          />
          <mesh
            name="building-policestation001_4"
            geometry={nodes["building-policestation001_4"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="building-policestation001_5"
            geometry={nodes["building-policestation001_5"].geometry}
            material={materials["grey light"]}
          />
          <mesh
            name="building-policestation001_6"
            geometry={nodes["building-policestation001_6"].geometry}
            material={materials["26 RED-DARK.003"]}
          />
          <mesh
            name="building-policestation001_7"
            geometry={nodes["building-policestation001_7"].geometry}
            material={materials["64 GLASS.004"]}
          />
          <mesh
            name="building-policestation001_8"
            geometry={nodes["building-policestation001_8"].geometry}
            material={materials["15 BROWN-WHITE.002"]}
          />
        </group>
        <group
          name="building-policestation-garage005"
          position={[4.388, 1.491, -4.363]}
          scale={0.205}
        >
          <mesh
            name="building-policestation-garage001_1"
            geometry={nodes["building-policestation-garage001_1"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="building-policestation-garage001_2"
            geometry={nodes["building-policestation-garage001_2"].geometry}
            material={materials["17 GREY-DARKEST.004"]}
          />
          <mesh
            name="building-policestation-garage001_3"
            geometry={nodes["building-policestation-garage001_3"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="building-policestation-garage001_4"
            geometry={nodes["building-policestation-garage001_4"].geometry}
            material={materials["grey light"]}
          />
          <mesh
            name="building-policestation-garage001_5"
            geometry={nodes["building-policestation-garage001_5"].geometry}
            material={materials["20 GREY.006"]}
          />
          <mesh
            name="building-policestation-garage001_6"
            geometry={nodes["building-policestation-garage001_6"].geometry}
            material={materials["64 GLASS.004"]}
          />
        </group>
        <group
          name="building-policestation-garage003"
          position={[-4.243, 1.524, -5.979]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.253}
        >
          <mesh
            name="building-policestation-garage001_1"
            geometry={nodes["building-policestation-garage001_1"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="building-policestation-garage001_2"
            geometry={nodes["building-policestation-garage001_2"].geometry}
            material={materials["17 GREY-DARKEST.004"]}
          />
          <mesh
            name="building-policestation-garage001_3"
            geometry={nodes["building-policestation-garage001_3"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="building-policestation-garage001_4"
            geometry={nodes["building-policestation-garage001_4"].geometry}
            material={materials["grey light"]}
          />
          <mesh
            name="building-policestation-garage001_5"
            geometry={nodes["building-policestation-garage001_5"].geometry}
            material={materials["20 GREY.006"]}
          />
          <mesh
            name="building-policestation-garage001_6"
            geometry={nodes["building-policestation-garage001_6"].geometry}
            material={materials["64 GLASS.004"]}
          />
        </group>
        <group
          name="building-policestation-garage001"
          position={[6.025, 1.491, -4.363]}
          scale={0.205}
        >
          <mesh
            name="building-policestation-garage001_1"
            geometry={nodes["building-policestation-garage001_1"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="building-policestation-garage001_2"
            geometry={nodes["building-policestation-garage001_2"].geometry}
            material={materials["17 GREY-DARKEST.004"]}
          />
          <mesh
            name="building-policestation-garage001_3"
            geometry={nodes["building-policestation-garage001_3"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="building-policestation-garage001_4"
            geometry={nodes["building-policestation-garage001_4"].geometry}
            material={materials["grey light"]}
          />
          <mesh
            name="building-policestation-garage001_5"
            geometry={nodes["building-policestation-garage001_5"].geometry}
            material={materials["20 GREY.006"]}
          />
          <mesh
            name="building-policestation-garage001_6"
            geometry={nodes["building-policestation-garage001_6"].geometry}
            material={materials["64 GLASS.004"]}
          />
        </group>
        <group
          name="building-carwash"
          position={[-5.694, 1.524, -2.341]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.175}
        >
          <mesh
            name="building-carwash001"
            geometry={nodes["building-carwash001"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="building-carwash001_1"
            geometry={nodes["building-carwash001_1"].geometry}
            material={materials["21 GREY LIGHT.007"]}
          />
          <mesh
            name="building-carwash001_2"
            geometry={nodes["building-carwash001_2"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="building-carwash001_3"
            geometry={nodes["building-carwash001_3"].geometry}
            material={materials["17 GREY-DARKEST.004"]}
          />
          <mesh
            name="building-carwash001_4"
            geometry={nodes["building-carwash001_4"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="building-carwash001_5"
            geometry={nodes["building-carwash001_5"].geometry}
            material={materials["64 GLASS.004"]}
          />
          <mesh
            name="building-carwash001_6"
            geometry={nodes["building-carwash001_6"].geometry}
            material={materials["15 BROWN-WHITE.002"]}
          />
        </group>
        <group
          name="industry-storage001"
          position={[4.163, 1.524, 4.986]}
          scale={0.175}
        >
          <mesh
            name="industry-storage001_1"
            geometry={nodes["industry-storage001_1"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="industry-storage001_2"
            geometry={nodes["industry-storage001_2"].geometry}
            material={materials["grey light"]}
          />
          <mesh
            name="industry-storage001_3"
            geometry={nodes["industry-storage001_3"].geometry}
            material={materials["20 GREY.006"]}
          />
          <mesh
            name="industry-storage001_4"
            geometry={nodes["industry-storage001_4"].geometry}
            material={materials["18 GREY-DARK.003"]}
          />
          <mesh
            name="industry-storage001_5"
            geometry={nodes["industry-storage001_5"].geometry}
            material={materials["64 GLASS.004"]}
          />
          <mesh
            name="industry-storage001_6"
            geometry={nodes["industry-storage001_6"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="industry-storage001_7"
            geometry={nodes["industry-storage001_7"].geometry}
            material={materials["17 GREY-DARKEST.004"]}
          />
        </group>
        <group
          name="building-policestation001"
          position={[-5.113, 1.524, 4.629]}
          scale={0.212}
        >
          <mesh
            name="building-policestation001_1"
            geometry={nodes["building-policestation001_1"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="building-policestation001_2"
            geometry={nodes["building-policestation001_2"].geometry}
            material={materials["20 GREY.006"]}
          />
          <mesh
            name="building-policestation001_3"
            geometry={nodes["building-policestation001_3"].geometry}
            material={materials["17 GREY-DARKEST.004"]}
          />
          <mesh
            name="building-policestation001_4"
            geometry={nodes["building-policestation001_4"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="building-policestation001_5"
            geometry={nodes["building-policestation001_5"].geometry}
            material={materials["grey light"]}
          />
          <mesh
            name="building-policestation001_6"
            geometry={nodes["building-policestation001_6"].geometry}
            material={materials["26 RED-DARK.003"]}
          />
          <mesh
            name="building-policestation001_7"
            geometry={nodes["building-policestation001_7"].geometry}
            material={materials["64 GLASS.004"]}
          />
          <mesh
            name="building-policestation001_8"
            geometry={nodes["building-policestation001_8"].geometry}
            material={materials["15 BROWN-WHITE.002"]}
          />
        </group>
        <group
          name="building-policestation003"
          position={[-3.004, 1.524, 4.629]}
          scale={0.212}
        >
          <mesh
            name="building-policestation001_1"
            geometry={nodes["building-policestation001_1"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="building-policestation001_2"
            geometry={nodes["building-policestation001_2"].geometry}
            material={materials["20 GREY.006"]}
          />
          <mesh
            name="building-policestation001_3"
            geometry={nodes["building-policestation001_3"].geometry}
            material={materials["17 GREY-DARKEST.004"]}
          />
          <mesh
            name="building-policestation001_4"
            geometry={nodes["building-policestation001_4"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="building-policestation001_5"
            geometry={nodes["building-policestation001_5"].geometry}
            material={materials["grey light"]}
          />
          <mesh
            name="building-policestation001_6"
            geometry={nodes["building-policestation001_6"].geometry}
            material={materials["26 RED-DARK.003"]}
          />
          <mesh
            name="building-policestation001_7"
            geometry={nodes["building-policestation001_7"].geometry}
            material={materials["64 GLASS.004"]}
          />
          <mesh
            name="building-policestation001_8"
            geometry={nodes["building-policestation001_8"].geometry}
            material={materials["15 BROWN-WHITE.002"]}
          />
        </group>
        <group
          name="palm-high001"
          position={[6.475, 1.524, 0.756]}
          scale={0.175}
        >
          <mesh
            name="palm-high"
            geometry={nodes["palm-high"].geometry}
            material={materials["BROWN-MEDIUM.001"]}
          />
          <mesh
            name="palm-high_1"
            geometry={nodes["palm-high_1"].geometry}
            material={materials["GREEN-LIGHT.001"]}
          />
        </group>
        <mesh
          name="rock-large"
          geometry={nodes["rock-large"].geometry}
          material={materials["14 BROWN-LIGHTEST"]}
          position={[-6.388, 1.71, 6.429]}
          scale={0.148}
        />
        <group
          name="cactus-big"
          position={[-6.851, 2.046, 6.816]}
          rotation={[0, 1.181, 0]}
          scale={0.312}
        >
          <mesh
            name="cactus-big_1"
            geometry={nodes["cactus-big_1"].geometry}
            material={materials["26 RED-DARK"]}
          />
          <mesh
            name="cactus-big_2"
            geometry={nodes["cactus-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
        </group>
        <mesh
          name="rock-large001"
          geometry={nodes["rock-large001"].geometry}
          material={materials["14 BROWN-LIGHTEST"]}
          position={[-5.94, 1.651, -5.933]}
          rotation={[Math.PI, -0.402, Math.PI]}
          scale={0.088}
        />
        <mesh
          name="rock-large002"
          geometry={nodes["rock-large002"].geometry}
          material={materials["14 BROWN-LIGHTEST"]}
          position={[2.569, 1.71, 5.937]}
          rotation={[0, -1.014, 0]}
          scale={0.148}
        />
        <group
          name="cactus-big001"
          position={[4.569, 2.046, 1.351]}
          rotation={[0, -0.389, 0]}
          scale={0.312}
        >
          <mesh
            name="cactus-big_1"
            geometry={nodes["cactus-big_1"].geometry}
            material={materials["26 RED-DARK"]}
          />
          <mesh
            name="cactus-big_2"
            geometry={nodes["cactus-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
        </group>
        <mesh
          name="Stage"
          geometry={nodes.Stage.geometry}
          material={materials["10 BROWN-DARK"]}
          position={[0.006, 0.762, 0.006]}
          scale={[25, 2.5, 25]}
        />
        <group
          name="tile-road-straight-nb003"
          position={[0.006, 1.564, 5.082]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.169}
        >
          <mesh
            name="tile-road-straight-nb003_1"
            geometry={nodes["tile-road-straight-nb003_1"].geometry}
            material={materials["BROWN-LIGHTEST"]}
          />
          <mesh
            name="tile-road-straight-nb003_2"
            geometry={nodes["tile-road-straight-nb003_2"].geometry}
            material={materials["18 GREY-DARK"]}
          />
          <mesh
            name="tile-road-straight-nb003_3"
            geometry={nodes["tile-road-straight-nb003_3"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="tile-road-straight-nb001"
          position={[5.082, 1.564, -1.14]}
          rotation={[0, 1.571, 0]}
          scale={0.169}
        >
          <mesh
            name="tile-road-straight-nb004"
            geometry={nodes["tile-road-straight-nb004"].geometry}
            material={materials["BROWN-LIGHTEST"]}
          />
          <mesh
            name="tile-road-straight-nb004_1"
            geometry={nodes["tile-road-straight-nb004_1"].geometry}
            material={materials["18 GREY-DARK"]}
          />
          <mesh
            name="tile-road-straight-nb004_2"
            geometry={nodes["tile-road-straight-nb004_2"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="building-policestation004"
          position={[0.022, 2.814, -2.949]}
          scale={0.255}
        >
          <mesh
            name="building-policestation002_1"
            geometry={nodes["building-policestation002_1"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="building-policestation002_2"
            geometry={nodes["building-policestation002_2"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
        </group>
        <group
          name="airport-hangar"
          position={[0.022, 1.524, -5.042]}
          scale={0.079}
        >
          <mesh
            name="airport-hangar001"
            geometry={nodes["airport-hangar001"].geometry}
            material={materials["58 WHITE.005"]}
          />
          <mesh
            name="airport-hangar001_1"
            geometry={nodes["airport-hangar001_1"].geometry}
            material={materials["20 GREY.006"]}
          />
          <mesh
            name="airport-hangar001_2"
            geometry={nodes["airport-hangar001_2"].geometry}
            material={materials["35 GREEN-MEDIUM.001"]}
          />
          <mesh
            name="airport-hangar001_3"
            geometry={nodes["airport-hangar001_3"].geometry}
            material={materials["14 BROWN-LIGHTEST.002"]}
          />
          <mesh
            name="airport-hangar001_4"
            geometry={nodes["airport-hangar001_4"].geometry}
            material={materials["64 GLASS.004"]}
          />
          <mesh
            name="airport-hangar001_5"
            geometry={nodes["airport-hangar001_5"].geometry}
            material={materials["17 GREY-DARKEST.004"]}
          />
        </group>
        <group
          name="military-headquarters001"
          position={[1.196, 1.533, 1.397]}
          scale={0.199}
        >
          <mesh
            name="military-headquarters001_1"
            geometry={nodes["military-headquarters001_1"].geometry}
            material={materials["15 BROWN-WHITE.001"]}
          />
          <mesh
            name="military-headquarters001_2"
            geometry={nodes["military-headquarters001_2"].geometry}
            material={materials["17 GREY-DARKEST.002"]}
          />
          <mesh
            name="military-headquarters001_3"
            geometry={nodes["military-headquarters001_3"].geometry}
            material={materials["17 GREY-DARKEST.003"]}
          />
          <mesh
            name="military-headquarters001_4"
            geometry={nodes["military-headquarters001_4"].geometry}
            material={materials["64 GLASS.003"]}
          />
          <mesh
            name="military-headquarters001_5"
            geometry={nodes["military-headquarters001_5"].geometry}
            material={materials["20 GREY.005"]}
          />
          <mesh
            name="military-headquarters001_6"
            geometry={nodes["military-headquarters001_6"].geometry}
            material={materials["21 GREY LIGHT.004"]}
          />
          <mesh
            name="military-headquarters001_7"
            geometry={nodes["military-headquarters001_7"].geometry}
            material={materials["Material.001"]}
          />
          <group
            name="building-policestation002"
            position={[0.04, 5.469, 4.117]}
          >
            <mesh
              name="building-policestation002_1"
              geometry={nodes["building-policestation002_1"].geometry}
              material={materials["58 WHITE.005"]}
            />
            <mesh
              name="building-policestation002_2"
              geometry={nodes["building-policestation002_2"].geometry}
              material={materials["35 GREEN-MEDIUM.001"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/POICompany.glb");
