/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type * as THREE from "three";
import type { ThreeElements } from "@react-three/fiber";
import React from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["building-tattoo_1"]: THREE.Mesh;
    ["building-tattoo_2"]: THREE.Mesh;
    ["building-tattoo_3"]: THREE.Mesh;
    ["building-tattoo_4"]: THREE.Mesh;
    ["building-tattoo_5"]: THREE.Mesh;
    ["building-tattoo_6"]: THREE.Mesh;
    ["building-tattoo_7"]: THREE.Mesh;
    ["building-tattoo_8"]: THREE.Mesh;
    ["building-tattoo_9"]: THREE.Mesh;
    ["industry-factory-hall_1"]: THREE.Mesh;
    ["industry-factory-hall_2"]: THREE.Mesh;
    ["industry-factory-hall_3"]: THREE.Mesh;
    ["industry-factory-hall_4"]: THREE.Mesh;
    ["industry-factory-hall_5"]: THREE.Mesh;
    ["industry-factory-hall_6"]: THREE.Mesh;
    ["farm-silo_1"]: THREE.Mesh;
    ["farm-silo_2"]: THREE.Mesh;
    ["farm-silo_1"]: THREE.Mesh;
    ["farm-silo_2"]: THREE.Mesh;
  };
  materials: {
    ["5 SKIN-LIGHT"]: THREE.MeshPhysicalMaterial;
    ["10 BROWN-DARK"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.009"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.002"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.001"]: THREE.MeshPhysicalMaterial;
    ["23 GREY-WHITE.001"]: THREE.MeshPhysicalMaterial;
    ["58 WHITE.003"]: THREE.MeshPhysicalMaterial;
    ["61 EMISSION-ORANGE.003"]: THREE.MeshStandardMaterial;
    ["64 GLASS.002"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE.005"]: THREE.MeshPhysicalMaterial;
    ["14 BROWN-LIGHTEST"]: THREE.MeshPhysicalMaterial;
    ["19 GREY-MEDIUM"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.008"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.008"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.009"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.002"]: THREE.MeshPhysicalMaterial;
  };
};

export function FarmBuildings(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/farm-buildings.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-87.321, 2.667, 44.582]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_1"].geometry}
          material={materials["5 SKIN-LIGHT"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_2"].geometry}
          material={materials["10 BROWN-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_3"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_4"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_5"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_6"].geometry}
          material={materials["23 GREY-WHITE.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_7"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_8"].geometry}
          material={materials["61 EMISSION-ORANGE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-tattoo_9"].geometry}
          material={materials["64 GLASS.002"]}
        />
      </group>
      <group
        position={[-118.891, 2.667, 15.062]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-factory-hall_1"].geometry}
          material={materials["15 BROWN-WHITE.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-factory-hall_2"].geometry}
          material={materials["14 BROWN-LIGHTEST"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-factory-hall_3"].geometry}
          material={materials["19 GREY-MEDIUM"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-factory-hall_4"].geometry}
          material={materials["64 GLASS.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-factory-hall_5"].geometry}
          material={materials["17 GREY-DARKEST.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-factory-hall_6"].geometry}
          material={materials["20 GREY.009"]}
        />
      </group>
      <group position={[-179.469, 2.667, 56.783]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["farm-silo_1"].geometry}
          material={materials["26 RED-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["farm-silo_2"].geometry}
          material={materials["20 GREY.002"]}
        />
      </group>
      <group position={[-179.423, 2.667, 65.057]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["farm-silo_1"].geometry}
          material={materials["26 RED-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["farm-silo_2"].geometry}
          material={materials["20 GREY.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/farm-buildings.glb");
