/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";
import { ThreeElements } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    ["military-headquarters_1"]: THREE.Mesh;
    ["military-headquarters_2"]: THREE.Mesh;
    ["military-headquarters_3"]: THREE.Mesh;
    ["military-headquarters_4"]: THREE.Mesh;
    ["military-headquarters_5"]: THREE.Mesh;
    ["military-headquarters_6"]: THREE.Mesh;
    ["military-headquarters_7"]: THREE.Mesh;
    ["building-policestation-garage"]: THREE.Mesh;
    ["building-policestation-garage_1"]: THREE.Mesh;
    ["building-policestation-garage_2"]: THREE.Mesh;
    ["building-policestation-garage_3"]: THREE.Mesh;
    ["building-policestation-garage_4"]: THREE.Mesh;
    ["building-policestation-garage_5"]: THREE.Mesh;
    ["building-policestation-garage"]: THREE.Mesh;
    ["building-policestation-garage_1"]: THREE.Mesh;
    ["building-policestation-garage_2"]: THREE.Mesh;
    ["building-policestation-garage_3"]: THREE.Mesh;
    ["building-policestation-garage_4"]: THREE.Mesh;
    ["building-policestation-garage_5"]: THREE.Mesh;
    ["building-policestation-garage"]: THREE.Mesh;
    ["building-policestation-garage_1"]: THREE.Mesh;
    ["building-policestation-garage_2"]: THREE.Mesh;
    ["building-policestation-garage_3"]: THREE.Mesh;
    ["building-policestation-garage_4"]: THREE.Mesh;
    ["building-policestation-garage_5"]: THREE.Mesh;
    ["building-policestation-garage"]: THREE.Mesh;
    ["building-policestation-garage_1"]: THREE.Mesh;
    ["building-policestation-garage_2"]: THREE.Mesh;
    ["building-policestation-garage_3"]: THREE.Mesh;
    ["building-policestation-garage_4"]: THREE.Mesh;
    ["building-policestation-garage_5"]: THREE.Mesh;
    ["building-policestation"]: THREE.Mesh;
    ["building-policestation_1"]: THREE.Mesh;
    ["building-policestation_2"]: THREE.Mesh;
    ["building-policestation_3"]: THREE.Mesh;
    ["building-policestation_4"]: THREE.Mesh;
    ["building-policestation_5"]: THREE.Mesh;
    ["building-policestation_6"]: THREE.Mesh;
    ["building-policestation_7"]: THREE.Mesh;
    ["building-policestation-garage"]: THREE.Mesh;
    ["building-policestation-garage_1"]: THREE.Mesh;
    ["building-policestation-garage_2"]: THREE.Mesh;
    ["building-policestation-garage_3"]: THREE.Mesh;
    ["building-policestation-garage_4"]: THREE.Mesh;
    ["building-policestation-garage_5"]: THREE.Mesh;
    ["building-policestation-garage"]: THREE.Mesh;
    ["building-policestation-garage_1"]: THREE.Mesh;
    ["building-policestation-garage_2"]: THREE.Mesh;
    ["building-policestation-garage_3"]: THREE.Mesh;
    ["building-policestation-garage_4"]: THREE.Mesh;
    ["building-policestation-garage_5"]: THREE.Mesh;
    ["building-policestation"]: THREE.Mesh;
    ["building-policestation_1"]: THREE.Mesh;
    ["building-policestation_2"]: THREE.Mesh;
    ["building-policestation_3"]: THREE.Mesh;
    ["building-policestation_4"]: THREE.Mesh;
    ["building-policestation_5"]: THREE.Mesh;
    ["building-policestation_6"]: THREE.Mesh;
    ["building-policestation_7"]: THREE.Mesh;
    ["airport-hangar_1"]: THREE.Mesh;
    ["airport-hangar_2"]: THREE.Mesh;
    ["airport-hangar_3"]: THREE.Mesh;
    ["airport-hangar_4"]: THREE.Mesh;
    ["airport-hangar_5"]: THREE.Mesh;
    ["airport-hangar_6"]: THREE.Mesh;
    ["building-carwash_1"]: THREE.Mesh;
    ["building-carwash_2"]: THREE.Mesh;
    ["building-carwash_3"]: THREE.Mesh;
    ["building-carwash_4"]: THREE.Mesh;
    ["building-carwash_5"]: THREE.Mesh;
    ["building-carwash_6"]: THREE.Mesh;
    ["building-carwash_7"]: THREE.Mesh;
    ["industry-storage_1"]: THREE.Mesh;
    ["industry-storage_2"]: THREE.Mesh;
    ["industry-storage_3"]: THREE.Mesh;
    ["industry-storage_4"]: THREE.Mesh;
    ["industry-storage_5"]: THREE.Mesh;
    ["industry-storage_6"]: THREE.Mesh;
    ["industry-storage_7"]: THREE.Mesh;
  };
  materials: {
    ["15 BROWN-WHITE.006"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.011"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.009"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.011"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.005"]: THREE.MeshPhysicalMaterial;
    Material: THREE.MeshStandardMaterial;
    ["58 WHITE.003"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.009"]: THREE.MeshPhysicalMaterial;
    ["36 GREEN"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.001"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.002"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.002"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE"]: THREE.MeshPhysicalMaterial;
    ["58 WHITE.003"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.002"]: THREE.MeshPhysicalMaterial;
    ["36 GREEN"]: THREE.MeshPhysicalMaterial;
    ["14 BROWN-LIGHTEST"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.002"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.009"]: THREE.MeshPhysicalMaterial;
    ["35 GREEN-MEDIUM"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.001"]: THREE.MeshPhysicalMaterial;
    ["18 GREY-DARK.001"]: THREE.MeshPhysicalMaterial;
  };
};

export function CompanyBuildings(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/company-buildings.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-14.668, 2.717, 45.169]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["military-headquarters_1"].geometry}
          material={materials["15 BROWN-WHITE.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["military-headquarters_2"].geometry}
          material={materials["17 GREY-DARKEST"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["military-headquarters_3"].geometry}
          material={materials["17 GREY-DARKEST.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["military-headquarters_4"].geometry}
          material={materials["64 GLASS.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["military-headquarters_5"].geometry}
          material={materials["20 GREY.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["military-headquarters_6"].geometry}
          material={materials["21 GREY LIGHT.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["military-headquarters_7"].geometry}
          material={materials.Material}
        />
      </group>
      <group position={[6.049, 2.667, 15.361]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_1"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_2"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_3"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_4"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_5"].geometry}
          material={materials["64 GLASS.002"]}
        />
      </group>
      <group position={[-45.613, 2.667, 20.73]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_1"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_2"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_3"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_4"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_5"].geometry}
          material={materials["64 GLASS.002"]}
        />
      </group>
      <group
        position={[-45.613, 2.667, 10.83]}
        rotation={[Math.PI, 0, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_1"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_2"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_3"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_4"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_5"].geometry}
          material={materials["64 GLASS.002"]}
        />
      </group>
      <group
        position={[14.049, 2.667, 15.361]}
        rotation={[Math.PI, 0, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_1"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_2"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_3"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_4"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_5"].geometry}
          material={materials["64 GLASS.002"]}
        />
      </group>
      <group position={[12.768, 2.667, 37.972]} rotation={[0, 1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_1"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_2"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_3"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_4"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_5"].geometry}
          material={materials["26 RED-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_6"].geometry}
          material={materials["64 GLASS.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_7"].geometry}
          material={materials["15 BROWN-WHITE"]}
        />
      </group>
      <group position={[-37.613, 2.667, 20.73]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_1"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_2"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_3"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_4"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_5"].geometry}
          material={materials["64 GLASS.002"]}
        />
      </group>
      <group
        position={[-37.613, 2.667, 10.83]}
        rotation={[Math.PI, 0, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_1"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_2"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_3"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_4"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation-garage_5"].geometry}
          material={materials["64 GLASS.002"]}
        />
      </group>
      <group position={[12.768, 2.667, 47.92]} rotation={[0, 1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_1"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_2"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_3"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_4"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_5"].geometry}
          material={materials["26 RED-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_6"].geometry}
          material={materials["64 GLASS.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-policestation_7"].geometry}
          material={materials["15 BROWN-WHITE"]}
        />
      </group>
      <group position={[-15.389, 2.667, 15.992]} scale={0.454}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["airport-hangar_1"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["airport-hangar_2"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["airport-hangar_3"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["airport-hangar_4"].geometry}
          material={materials["14 BROWN-LIGHTEST"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["airport-hangar_5"].geometry}
          material={materials["64 GLASS.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["airport-hangar_6"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
      </group>
      <group
        position={[-40.347, 2.667, 43.689]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-carwash_1"].geometry}
          material={materials["35 GREEN-MEDIUM"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-carwash_2"].geometry}
          material={materials["21 GREY LIGHT"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-carwash_3"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-carwash_4"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-carwash_5"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-carwash_6"].geometry}
          material={materials["64 GLASS.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-carwash_7"].geometry}
          material={materials["15 BROWN-WHITE"]}
        />
      </group>
      <group position={[2.056, 2.667, 41.371]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-storage_1"].geometry}
          material={materials["36 GREEN"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-storage_2"].geometry}
          material={materials["21 GREY LIGHT.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-storage_3"].geometry}
          material={materials["20 GREY.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-storage_4"].geometry}
          material={materials["18 GREY-DARK.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-storage_5"].geometry}
          material={materials["64 GLASS.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-storage_6"].geometry}
          material={materials["58 WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["industry-storage_7"].geometry}
          material={materials["17 GREY-DARKEST.009"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/company-buildings.glb");
