/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { createContext, useMemo, ReactElement } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Merged } from "@react-three/drei";
import { NatureInstances } from "./types";

type GLTFResult = GLTF & {
  nodes: {
    ["rock-large002"]: THREE.Mesh;
    ["cactus-big"]: THREE.Mesh;
    ["cactus-big_1"]: THREE.Mesh;
    ["cactus-basic"]: THREE.Mesh;
    ["rock-terrasse_1"]: THREE.Mesh;
    ["rock-terrasse_2"]: THREE.Mesh;
    ["rock-terrasse_3"]: THREE.Mesh;
    ["stone-big-tall"]: THREE.Mesh;
    ["stone-flat"]: THREE.Mesh;
    ["rocks-small"]: THREE.Mesh;
    ["cactus-medium_1"]: THREE.Mesh;
    ["cactus-medium_2"]: THREE.Mesh;
  };
  materials: {
    ["14 BROWN-LIGHTEST.002"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK"]: THREE.MeshPhysicalMaterial;
    ["36 GREEN"]: THREE.MeshPhysicalMaterial;
    ["36 GREEN.001"]: THREE.MeshPhysicalMaterial;
    ["14 BROWN-LIGHTEST"]: THREE.MeshPhysicalMaterial;
    ["35 GREEN-MEDIUM.001"]: THREE.MeshPhysicalMaterial;
    ["10 BROWN-DARK"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK.001"]: THREE.MeshPhysicalMaterial;
  };
};

interface InstancesProps {
  children: React.ReactNode;
}

export const context = createContext<NatureInstances | null>(null);

export function Instances({ children, ...props }: InstancesProps) {
  const { nodes } = useGLTF("/models/nature_group.glb") as GLTFResult;

  const instanceMeshes = useMemo(
    () => ({
      RockLarge: nodes["rock-large002"],
      CactusBig: nodes["cactus-big"],
      CactusBigGreen: nodes["cactus-big_1"],
      CactusBasic: nodes["cactus-basic"],
      RockTerrasse1: nodes["rock-terrasse_1"],
      RockTerrasse2: nodes["rock-terrasse_2"],
      RockTerrasse3: nodes["rock-terrasse_3"],
      StoneBigTall: nodes["stone-big-tall"],
      StoneFlat: nodes["stone-flat"],
      RocksSmall: nodes["rocks-small"],
      CactusMedium1: nodes["cactus-medium_1"],
      CactusMedium2: nodes["cactus-medium_2"],
    }),
    [nodes]
  );

  return (
    <Merged meshes={instanceMeshes} {...props}>
      {(instances: NatureInstances) => (
        <context.Provider value={instances}>{children}</context.Provider>
      )}
    </Merged>
  );
}

useGLTF.preload("/models/nature_group.glb");
