/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeElements } from "@react-three/fiber";
type GLTFResult = GLTF & {
  nodes: {
    ["tile-plain-nb"]: THREE.Mesh;
    ["palm-high"]: THREE.Mesh;
    ["palm-high_1"]: THREE.Mesh;
    Material2061: THREE.Mesh;
    Material2015: THREE.Mesh;
    Material2014: THREE.Mesh;
    Material2013: THREE.Mesh;
    Material2012: THREE.Mesh;
    Material2011: THREE.Mesh;
    Material2010: THREE.Mesh;
    Material2009: THREE.Mesh;
    Material2008: THREE.Mesh;
    Material2007: THREE.Mesh;
    Material2006: THREE.Mesh;
    Material2005: THREE.Mesh;
    Material2004: THREE.Mesh;
    Material2003: THREE.Mesh;
    Material2002: THREE.Mesh;
    Material2001: THREE.Mesh;
    ["lamp-road-double_1"]: THREE.Mesh;
    ["lamp-road-double_2"]: THREE.Mesh;
    ["lamp-road-double_3"]: THREE.Mesh;
    ["lamp-road-double_1"]: THREE.Mesh;
    ["lamp-road-double_2"]: THREE.Mesh;
    ["lamp-road-double_3"]: THREE.Mesh;
    ["lamp-road-double_1"]: THREE.Mesh;
    ["lamp-road-double_2"]: THREE.Mesh;
    ["lamp-road-double_3"]: THREE.Mesh;
    ["lamp-road-double_1"]: THREE.Mesh;
    ["lamp-road-double_2"]: THREE.Mesh;
    ["lamp-road-double_3"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    fountain_1: THREE.Mesh;
    fountain_2: THREE.Mesh;
    fountain_3: THREE.Mesh;
    ["building-tattoo"]: THREE.Mesh;
    ["building-tattoo_1"]: THREE.Mesh;
    ["building-tattoo_2"]: THREE.Mesh;
    ["building-tattoo_3"]: THREE.Mesh;
    ["building-tattoo_4"]: THREE.Mesh;
    ["building-tattoo_5"]: THREE.Mesh;
    ["building-tattoo_6"]: THREE.Mesh;
    ["building-tattoo_7"]: THREE.Mesh;
    ["building-tattoo_8"]: THREE.Mesh;
    ["building-tattoo"]: THREE.Mesh;
    ["building-tattoo_1"]: THREE.Mesh;
    ["building-tattoo_2"]: THREE.Mesh;
    ["building-tattoo_3"]: THREE.Mesh;
    ["building-tattoo_4"]: THREE.Mesh;
    ["building-tattoo_5"]: THREE.Mesh;
    ["building-tattoo_6"]: THREE.Mesh;
    ["building-tattoo_7"]: THREE.Mesh;
    ["building-tattoo_8"]: THREE.Mesh;
    ["building-shop-china"]: THREE.Mesh;
    ["building-shop-china_1"]: THREE.Mesh;
    ["building-shop-china_2"]: THREE.Mesh;
    ["building-shop-china_3"]: THREE.Mesh;
    ["building-shop-china_4"]: THREE.Mesh;
    ["building-shop-china_5"]: THREE.Mesh;
    ["building-shop-china_6"]: THREE.Mesh;
    ["building-shop-china_7"]: THREE.Mesh;
    ["building-shop-china_8"]: THREE.Mesh;
    ["building-shop-china_9"]: THREE.Mesh;
    ["building-shop-china"]: THREE.Mesh;
    ["building-shop-china_1"]: THREE.Mesh;
    ["building-shop-china_2"]: THREE.Mesh;
    ["building-shop-china_3"]: THREE.Mesh;
    ["building-shop-china_4"]: THREE.Mesh;
    ["building-shop-china_5"]: THREE.Mesh;
    ["building-shop-china_6"]: THREE.Mesh;
    ["building-shop-china_7"]: THREE.Mesh;
    ["building-shop-china_8"]: THREE.Mesh;
    ["building-shop-china_9"]: THREE.Mesh;
    ["building-shop-china"]: THREE.Mesh;
    ["building-shop-china_1"]: THREE.Mesh;
    ["building-shop-china_2"]: THREE.Mesh;
    ["building-shop-china_3"]: THREE.Mesh;
    ["building-shop-china_4"]: THREE.Mesh;
    ["building-shop-china_5"]: THREE.Mesh;
    ["building-shop-china_6"]: THREE.Mesh;
    ["building-shop-china_7"]: THREE.Mesh;
    ["building-shop-china_8"]: THREE.Mesh;
    ["building-shop-china_9"]: THREE.Mesh;
    ["building-restaurant001"]: THREE.Mesh;
    ["building-restaurant001_1"]: THREE.Mesh;
    ["building-restaurant001_2"]: THREE.Mesh;
    ["building-restaurant001_3"]: THREE.Mesh;
    ["building-restaurant001_4"]: THREE.Mesh;
    ["building-restaurant001_5"]: THREE.Mesh;
    ["building-restaurant001_6"]: THREE.Mesh;
    ["building-restaurant001_7"]: THREE.Mesh;
    ["building-restaurant001_8"]: THREE.Mesh;
    ["building-restaurant001_9"]: THREE.Mesh;
    ["building-mall_1"]: THREE.Mesh;
    ["building-mall_2"]: THREE.Mesh;
    ["building-mall_3"]: THREE.Mesh;
    ["building-mall_4"]: THREE.Mesh;
    ["building-mall_5"]: THREE.Mesh;
    ["building-mall_6"]: THREE.Mesh;
    ["building-mall_7"]: THREE.Mesh;
    ["building-mall_8"]: THREE.Mesh;
    ["building-cafe"]: THREE.Mesh;
    ["building-cafe_1"]: THREE.Mesh;
    ["building-cafe_2"]: THREE.Mesh;
    ["building-cafe_3"]: THREE.Mesh;
    ["building-cafe_4"]: THREE.Mesh;
    ["building-cafe_5"]: THREE.Mesh;
    ["building-cafe_6"]: THREE.Mesh;
    ["building-cafe_7"]: THREE.Mesh;
    ["building-cafe"]: THREE.Mesh;
    ["building-cafe_1"]: THREE.Mesh;
    ["building-cafe_2"]: THREE.Mesh;
    ["building-cafe_3"]: THREE.Mesh;
    ["building-cafe_4"]: THREE.Mesh;
    ["building-cafe_5"]: THREE.Mesh;
    ["building-cafe_6"]: THREE.Mesh;
    ["building-cafe_7"]: THREE.Mesh;
    ["building-shop-china"]: THREE.Mesh;
    ["building-shop-china_1"]: THREE.Mesh;
    ["building-shop-china_2"]: THREE.Mesh;
    ["building-shop-china_3"]: THREE.Mesh;
    ["building-shop-china_4"]: THREE.Mesh;
    ["building-shop-china_5"]: THREE.Mesh;
    ["building-shop-china_6"]: THREE.Mesh;
    ["building-shop-china_7"]: THREE.Mesh;
    ["building-shop-china_8"]: THREE.Mesh;
    ["building-shop-china_9"]: THREE.Mesh;
    ["building-shop-china"]: THREE.Mesh;
    ["building-shop-china_1"]: THREE.Mesh;
    ["building-shop-china_2"]: THREE.Mesh;
    ["building-shop-china_3"]: THREE.Mesh;
    ["building-shop-china_4"]: THREE.Mesh;
    ["building-shop-china_5"]: THREE.Mesh;
    ["building-shop-china_6"]: THREE.Mesh;
    ["building-shop-china_7"]: THREE.Mesh;
    ["building-shop-china_8"]: THREE.Mesh;
    ["building-shop-china_9"]: THREE.Mesh;
    ["building-shop-china"]: THREE.Mesh;
    ["building-shop-china_1"]: THREE.Mesh;
    ["building-shop-china_2"]: THREE.Mesh;
    ["building-shop-china_3"]: THREE.Mesh;
    ["building-shop-china_4"]: THREE.Mesh;
    ["building-shop-china_5"]: THREE.Mesh;
    ["building-shop-china_6"]: THREE.Mesh;
    ["building-shop-china_7"]: THREE.Mesh;
    ["building-shop-china_8"]: THREE.Mesh;
    ["building-shop-china_9"]: THREE.Mesh;
    ["building-shop-china"]: THREE.Mesh;
    ["building-shop-china_1"]: THREE.Mesh;
    ["building-shop-china_2"]: THREE.Mesh;
    ["building-shop-china_3"]: THREE.Mesh;
    ["building-shop-china_4"]: THREE.Mesh;
    ["building-shop-china_5"]: THREE.Mesh;
    ["building-shop-china_6"]: THREE.Mesh;
    ["building-shop-china_7"]: THREE.Mesh;
    ["building-shop-china_8"]: THREE.Mesh;
    ["building-shop-china_9"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    Cube_1: THREE.Mesh;
    Cube_2: THREE.Mesh;
    Cube_3: THREE.Mesh;
  };
  materials: {
    ["18 GREY-DARK"]: THREE.MeshPhysicalMaterial;
    ["SBW_11 BROWN-MEDIUM.004"]: THREE.MeshPhysicalMaterial;
    ["SBW_37 GREEN-LIGHT.001"]: THREE.MeshPhysicalMaterial;
    ["material_3.002"]: THREE.MeshStandardMaterial;
    ["20 GREY.002"]: THREE.MeshPhysicalMaterial;
    Street_Lights: THREE.MeshStandardMaterial;
    ["21 GREY LIGHT"]: THREE.MeshPhysicalMaterial;
    Lamp: THREE.MeshPhysicalMaterial;
    ["48 TRANSPARENT-BLUE.001"]: THREE.MeshPhysicalMaterial;
    ["58 WHITE.003"]: THREE.MeshPhysicalMaterial;
    ["5 SKIN-LIGHT"]: THREE.MeshPhysicalMaterial;
    ["10 BROWN-DARK"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.009"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.002"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT"]: THREE.MeshPhysicalMaterial;
    ["23 GREY-WHITE.001"]: THREE.MeshPhysicalMaterial;
    ["58 WHITE.003"]: THREE.MeshPhysicalMaterial;
    ["61 EMISSION-ORANGE.003"]: THREE.MeshStandardMaterial;
    ["64 GLASS.002"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK"]: THREE.MeshPhysicalMaterial;
    ["30 YELLOW"]: THREE.MeshPhysicalMaterial;
    ["36 GREEN"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.007"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK.006"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.007"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.008"]: THREE.MeshPhysicalMaterial;
    ["61 EMISSION-ORANGE.002"]: THREE.MeshStandardMaterial;
    ["21 GREY LIGHT.004"]: THREE.MeshPhysicalMaterial;
    ["58 WHITE.006"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE.004"]: THREE.MeshPhysicalMaterial;
    ["5 SKIN-LIGHT.001"]: THREE.MeshPhysicalMaterial;
    ["9 BROWN-DARKEST.004"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.002"]: THREE.MeshPhysicalMaterial;
    ["17 GREY-DARKEST.009"]: THREE.MeshPhysicalMaterial;
    ["4 SKIN"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE"]: THREE.MeshPhysicalMaterial;
    ["35 GREEN-MEDIUM.002"]: THREE.MeshPhysicalMaterial;
    ["10 BROWN-DARK"]: THREE.MeshPhysicalMaterial;
  };
};

export function ShopsSubSceneModel(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF("/models/POIShops.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="tile-plain-nb"
          geometry={nodes["tile-plain-nb"].geometry}
          material={materials["18 GREY-DARK"]}
          position={[-3.503, 3.267, -2.783]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.189}
        />
        <group
          name="palm-high051"
          position={[3.635, 3.267, 6.772]}
          scale={0.189}
        >
          <mesh
            name="palm-high"
            geometry={nodes["palm-high"].geometry}
            material={materials["SBW_11 BROWN-MEDIUM.004"]}
          />
          <mesh
            name="palm-high_1"
            geometry={nodes["palm-high_1"].geometry}
            material={materials["SBW_37 GREEN-LIGHT.001"]}
          />
        </group>
        <mesh
          name="Material2061"
          geometry={nodes.Material2061.geometry}
          material={materials["material_3.002"]}
          position={[-4.224, 3.267, -5.261]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2015"
          geometry={nodes.Material2015.geometry}
          material={materials["material_3.002"]}
          position={[-5.278, 3.267, -2.397]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2014"
          geometry={nodes.Material2014.geometry}
          material={materials["material_3.002"]}
          position={[-5.278, 3.267, -5.261]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2013"
          geometry={nodes.Material2013.geometry}
          material={materials["material_3.002"]}
          position={[-1.59, 3.267, -2.397]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2012"
          geometry={nodes.Material2012.geometry}
          material={materials["material_3.002"]}
          position={[-4.751, 3.267, -2.397]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2011"
          geometry={nodes.Material2011.geometry}
          material={materials["material_3.002"]}
          position={[-2.117, 3.267, -2.397]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2010"
          geometry={nodes.Material2010.geometry}
          material={materials["material_3.002"]}
          position={[-2.644, 3.267, -2.397]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2009"
          geometry={nodes.Material2009.geometry}
          material={materials["material_3.002"]}
          position={[-3.171, 3.267, -2.397]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2008"
          geometry={nodes.Material2008.geometry}
          material={materials["material_3.002"]}
          position={[-3.698, 3.267, -2.397]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2007"
          geometry={nodes.Material2007.geometry}
          material={materials["material_3.002"]}
          position={[-4.224, 3.267, -2.397]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2006"
          geometry={nodes.Material2006.geometry}
          material={materials["material_3.002"]}
          position={[-1.59, 3.267, -5.261]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2005"
          geometry={nodes.Material2005.geometry}
          material={materials["material_3.002"]}
          position={[-4.751, 3.267, -5.261]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2004"
          geometry={nodes.Material2004.geometry}
          material={materials["material_3.002"]}
          position={[-2.117, 3.267, -5.261]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2003"
          geometry={nodes.Material2003.geometry}
          material={materials["material_3.002"]}
          position={[-2.644, 3.267, -5.261]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2002"
          geometry={nodes.Material2002.geometry}
          material={materials["material_3.002"]}
          position={[-3.171, 3.267, -5.261]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <mesh
          name="Material2001"
          geometry={nodes.Material2001.geometry}
          material={materials["material_3.002"]}
          position={[-3.698, 3.267, -5.261]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.005}
        />
        <group
          name="lamp-road-double003"
          position={[-4.766, 3.267, -1.35]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="lamp-road-double_1"
            geometry={nodes["lamp-road-double_1"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-road-double_2"
            geometry={nodes["lamp-road-double_2"].geometry}
            material={materials.Street_Lights}
          />
          <mesh
            name="lamp-road-double_3"
            geometry={nodes["lamp-road-double_3"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="lamp-road-double002"
          position={[-2.652, 3.267, -1.35]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="lamp-road-double_1"
            geometry={nodes["lamp-road-double_1"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-road-double_2"
            geometry={nodes["lamp-road-double_2"].geometry}
            material={materials.Street_Lights}
          />
          <mesh
            name="lamp-road-double_3"
            geometry={nodes["lamp-road-double_3"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="lamp-road-double001"
          position={[-4.766, 3.267, -4.211]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="lamp-road-double_1"
            geometry={nodes["lamp-road-double_1"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-road-double_2"
            geometry={nodes["lamp-road-double_2"].geometry}
            material={materials.Street_Lights}
          />
          <mesh
            name="lamp-road-double_3"
            geometry={nodes["lamp-road-double_3"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="lamp-road-double"
          position={[-2.652, 3.267, -4.211]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="lamp-road-double_1"
            geometry={nodes["lamp-road-double_1"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-road-double_2"
            geometry={nodes["lamp-road-double_2"].geometry}
            material={materials.Street_Lights}
          />
          <mesh
            name="lamp-road-double_3"
            geometry={nodes["lamp-road-double_3"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="lamp-city018"
          position={[1.195, 3.267, 3.677]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city017"
          position={[1.195, 3.267, 2.209]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city016"
          position={[1.195, 3.267, 0.796]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city015"
          position={[1.195, 3.267, 6.522]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city014"
          position={[-3.416, 3.267, 2.444]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city013"
          position={[-3.416, 3.267, 0.796]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city012"
          position={[-3.416, 3.267, 6.522]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city011"
          position={[1.195, 3.267, 5.184]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city010"
          position={[-3.416, 3.267, 5.184]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="fountain"
          position={[-3.384, 3.267, 3.894]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="fountain_1"
            geometry={nodes.fountain_1.geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="fountain_2"
            geometry={nodes.fountain_2.geometry}
            material={materials["48 TRANSPARENT-BLUE.001"]}
          />
          <mesh
            name="fountain_3"
            geometry={nodes.fountain_3.geometry}
            material={materials["58 WHITE.003"]}
          />
        </group>
        <group
          name="building-tattoo002"
          position={[1.169, 3.213, -0.749]}
          scale={0.189}
        >
          <mesh
            name="building-tattoo"
            geometry={nodes["building-tattoo"].geometry}
            material={materials["5 SKIN-LIGHT"]}
          />
          <mesh
            name="building-tattoo_1"
            geometry={nodes["building-tattoo_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="building-tattoo_2"
            geometry={nodes["building-tattoo_2"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-tattoo_3"
            geometry={nodes["building-tattoo_3"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-tattoo_4"
            geometry={nodes["building-tattoo_4"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
          <mesh
            name="building-tattoo_5"
            geometry={nodes["building-tattoo_5"].geometry}
            material={materials["23 GREY-WHITE.001"]}
          />
          <mesh
            name="building-tattoo_6"
            geometry={nodes["building-tattoo_6"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-tattoo_7"
            geometry={nodes["building-tattoo_7"].geometry}
            material={materials["61 EMISSION-ORANGE.003"]}
          />
          <mesh
            name="building-tattoo_8"
            geometry={nodes["building-tattoo_8"].geometry}
            material={materials["64 GLASS.002"]}
          />
        </group>
        <group
          name="building-tattoo001"
          position={[-1.234, 3.259, 3.301]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="building-tattoo"
            geometry={nodes["building-tattoo"].geometry}
            material={materials["5 SKIN-LIGHT"]}
          />
          <mesh
            name="building-tattoo_1"
            geometry={nodes["building-tattoo_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="building-tattoo_2"
            geometry={nodes["building-tattoo_2"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-tattoo_3"
            geometry={nodes["building-tattoo_3"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-tattoo_4"
            geometry={nodes["building-tattoo_4"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
          <mesh
            name="building-tattoo_5"
            geometry={nodes["building-tattoo_5"].geometry}
            material={materials["23 GREY-WHITE.001"]}
          />
          <mesh
            name="building-tattoo_6"
            geometry={nodes["building-tattoo_6"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-tattoo_7"
            geometry={nodes["building-tattoo_7"].geometry}
            material={materials["61 EMISSION-ORANGE.003"]}
          />
          <mesh
            name="building-tattoo_8"
            geometry={nodes["building-tattoo_8"].geometry}
            material={materials["64 GLASS.002"]}
          />
        </group>
        <group
          name="building-shop-china005"
          position={[-1.263, 3.259, 0.991]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="building-shop-china"
            geometry={nodes["building-shop-china"].geometry}
            material={materials["15 BROWN-WHITE"]}
          />
          <mesh
            name="building-shop-china_1"
            geometry={nodes["building-shop-china_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="building-shop-china_2"
            geometry={nodes["building-shop-china_2"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-shop-china_3"
            geometry={nodes["building-shop-china_3"].geometry}
            material={materials["26 RED-DARK"]}
          />
          <mesh
            name="building-shop-china_4"
            geometry={nodes["building-shop-china_4"].geometry}
            material={materials["30 YELLOW"]}
          />
          <mesh
            name="building-shop-china_5"
            geometry={nodes["building-shop-china_5"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-shop-china_6"
            geometry={nodes["building-shop-china_6"].geometry}
            material={materials["64 GLASS.002"]}
          />
          <mesh
            name="building-shop-china_7"
            geometry={nodes["building-shop-china_7"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-shop-china_8"
            geometry={nodes["building-shop-china_8"].geometry}
            material={materials["36 GREEN"]}
          />
          <mesh
            name="building-shop-china_9"
            geometry={nodes["building-shop-china_9"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="building-shop-china004"
          position={[-5.536, 3.237, 5.717]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="building-shop-china"
            geometry={nodes["building-shop-china"].geometry}
            material={materials["15 BROWN-WHITE"]}
          />
          <mesh
            name="building-shop-china_1"
            geometry={nodes["building-shop-china_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="building-shop-china_2"
            geometry={nodes["building-shop-china_2"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-shop-china_3"
            geometry={nodes["building-shop-china_3"].geometry}
            material={materials["26 RED-DARK"]}
          />
          <mesh
            name="building-shop-china_4"
            geometry={nodes["building-shop-china_4"].geometry}
            material={materials["30 YELLOW"]}
          />
          <mesh
            name="building-shop-china_5"
            geometry={nodes["building-shop-china_5"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-shop-china_6"
            geometry={nodes["building-shop-china_6"].geometry}
            material={materials["64 GLASS.002"]}
          />
          <mesh
            name="building-shop-china_7"
            geometry={nodes["building-shop-china_7"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-shop-china_8"
            geometry={nodes["building-shop-china_8"].geometry}
            material={materials["36 GREEN"]}
          />
          <mesh
            name="building-shop-china_9"
            geometry={nodes["building-shop-china_9"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="building-shop-china001"
          position={[-5.536, 3.259, 0.991]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="building-shop-china"
            geometry={nodes["building-shop-china"].geometry}
            material={materials["15 BROWN-WHITE"]}
          />
          <mesh
            name="building-shop-china_1"
            geometry={nodes["building-shop-china_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="building-shop-china_2"
            geometry={nodes["building-shop-china_2"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-shop-china_3"
            geometry={nodes["building-shop-china_3"].geometry}
            material={materials["26 RED-DARK"]}
          />
          <mesh
            name="building-shop-china_4"
            geometry={nodes["building-shop-china_4"].geometry}
            material={materials["30 YELLOW"]}
          />
          <mesh
            name="building-shop-china_5"
            geometry={nodes["building-shop-china_5"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-shop-china_6"
            geometry={nodes["building-shop-china_6"].geometry}
            material={materials["64 GLASS.002"]}
          />
          <mesh
            name="building-shop-china_7"
            geometry={nodes["building-shop-china_7"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-shop-china_8"
            geometry={nodes["building-shop-china_8"].geometry}
            material={materials["36 GREEN"]}
          />
          <mesh
            name="building-shop-china_9"
            geometry={nodes["building-shop-china_9"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="building-restaurant"
          position={[-5.631, 3.278, 3.35]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="building-restaurant001"
            geometry={nodes["building-restaurant001"].geometry}
            material={materials["17 GREY-DARKEST.007"]}
          />
          <mesh
            name="building-restaurant001_1"
            geometry={nodes["building-restaurant001_1"].geometry}
            material={materials["26 RED-DARK.006"]}
          />
          <mesh
            name="building-restaurant001_2"
            geometry={nodes["building-restaurant001_2"].geometry}
            material={materials["64 GLASS.007"]}
          />
          <mesh
            name="building-restaurant001_3"
            geometry={nodes["building-restaurant001_3"].geometry}
            material={materials["20 GREY.008"]}
          />
          <mesh
            name="building-restaurant001_4"
            geometry={nodes["building-restaurant001_4"].geometry}
            material={materials["61 EMISSION-ORANGE.002"]}
          />
          <mesh
            name="building-restaurant001_5"
            geometry={nodes["building-restaurant001_5"].geometry}
            material={materials["21 GREY LIGHT.004"]}
          />
          <mesh
            name="building-restaurant001_6"
            geometry={nodes["building-restaurant001_6"].geometry}
            material={materials["58 WHITE.006"]}
          />
          <mesh
            name="building-restaurant001_7"
            geometry={nodes["building-restaurant001_7"].geometry}
            material={materials["15 BROWN-WHITE.004"]}
          />
          <mesh
            name="building-restaurant001_8"
            geometry={nodes["building-restaurant001_8"].geometry}
            material={materials["5 SKIN-LIGHT.001"]}
          />
          <mesh
            name="building-restaurant001_9"
            geometry={nodes["building-restaurant001_9"].geometry}
            material={materials["9 BROWN-DARKEST.004"]}
          />
        </group>
        <group
          name="building-mall"
          position={[5.701, 3.267, 4.272]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="building-mall_1"
            geometry={nodes["building-mall_1"].geometry}
            material={materials["64 GLASS.002"]}
          />
          <mesh
            name="building-mall_2"
            geometry={nodes["building-mall_2"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-mall_3"
            geometry={nodes["building-mall_3"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-mall_4"
            geometry={nodes["building-mall_4"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-mall_5"
            geometry={nodes["building-mall_5"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
          <mesh
            name="building-mall_6"
            geometry={nodes["building-mall_6"].geometry}
            material={materials["4 SKIN"]}
          />
          <mesh
            name="building-mall_7"
            geometry={nodes["building-mall_7"].geometry}
            material={materials["15 BROWN-WHITE"]}
          />
          <mesh
            name="building-mall_8"
            geometry={nodes["building-mall_8"].geometry}
            material={materials["48 TRANSPARENT-BLUE.001"]}
          />
        </group>
        <group
          name="building-cafe002"
          position={[5.59, 3.267, -0.823]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="building-cafe"
            geometry={nodes["building-cafe"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="building-cafe_1"
            geometry={nodes["building-cafe_1"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-cafe_2"
            geometry={nodes["building-cafe_2"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-cafe_3"
            geometry={nodes["building-cafe_3"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-cafe_4"
            geometry={nodes["building-cafe_4"].geometry}
            material={materials["15 BROWN-WHITE"]}
          />
          <mesh
            name="building-cafe_5"
            geometry={nodes["building-cafe_5"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="building-cafe_6"
            geometry={nodes["building-cafe_6"].geometry}
            material={materials["64 GLASS.002"]}
          />
          <mesh
            name="building-cafe_7"
            geometry={nodes["building-cafe_7"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="building-cafe001"
          position={[-1.16, 3.259, 5.729]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.189}
        >
          <mesh
            name="building-cafe"
            geometry={nodes["building-cafe"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="building-cafe_1"
            geometry={nodes["building-cafe_1"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-cafe_2"
            geometry={nodes["building-cafe_2"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-cafe_3"
            geometry={nodes["building-cafe_3"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-cafe_4"
            geometry={nodes["building-cafe_4"].geometry}
            material={materials["15 BROWN-WHITE"]}
          />
          <mesh
            name="building-cafe_5"
            geometry={nodes["building-cafe_5"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="building-cafe_6"
            geometry={nodes["building-cafe_6"].geometry}
            material={materials["64 GLASS.002"]}
          />
          <mesh
            name="building-cafe_7"
            geometry={nodes["building-cafe_7"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="building-shop-china002"
          position={[1.165, 3.259, -3.74]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="building-shop-china"
            geometry={nodes["building-shop-china"].geometry}
            material={materials["15 BROWN-WHITE"]}
          />
          <mesh
            name="building-shop-china_1"
            geometry={nodes["building-shop-china_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="building-shop-china_2"
            geometry={nodes["building-shop-china_2"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-shop-china_3"
            geometry={nodes["building-shop-china_3"].geometry}
            material={materials["26 RED-DARK"]}
          />
          <mesh
            name="building-shop-china_4"
            geometry={nodes["building-shop-china_4"].geometry}
            material={materials["30 YELLOW"]}
          />
          <mesh
            name="building-shop-china_5"
            geometry={nodes["building-shop-china_5"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-shop-china_6"
            geometry={nodes["building-shop-china_6"].geometry}
            material={materials["64 GLASS.002"]}
          />
          <mesh
            name="building-shop-china_7"
            geometry={nodes["building-shop-china_7"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-shop-china_8"
            geometry={nodes["building-shop-china_8"].geometry}
            material={materials["36 GREEN"]}
          />
          <mesh
            name="building-shop-china_9"
            geometry={nodes["building-shop-china_9"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="building-shop-china003"
          position={[1.165, 3.259, -6.658]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="building-shop-china"
            geometry={nodes["building-shop-china"].geometry}
            material={materials["15 BROWN-WHITE"]}
          />
          <mesh
            name="building-shop-china_1"
            geometry={nodes["building-shop-china_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="building-shop-china_2"
            geometry={nodes["building-shop-china_2"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-shop-china_3"
            geometry={nodes["building-shop-china_3"].geometry}
            material={materials["26 RED-DARK"]}
          />
          <mesh
            name="building-shop-china_4"
            geometry={nodes["building-shop-china_4"].geometry}
            material={materials["30 YELLOW"]}
          />
          <mesh
            name="building-shop-china_5"
            geometry={nodes["building-shop-china_5"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-shop-china_6"
            geometry={nodes["building-shop-china_6"].geometry}
            material={materials["64 GLASS.002"]}
          />
          <mesh
            name="building-shop-china_7"
            geometry={nodes["building-shop-china_7"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-shop-china_8"
            geometry={nodes["building-shop-china_8"].geometry}
            material={materials["36 GREEN"]}
          />
          <mesh
            name="building-shop-china_9"
            geometry={nodes["building-shop-china_9"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="building-shop-china006"
          position={[6.127, 3.312, -6.658]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="building-shop-china"
            geometry={nodes["building-shop-china"].geometry}
            material={materials["15 BROWN-WHITE"]}
          />
          <mesh
            name="building-shop-china_1"
            geometry={nodes["building-shop-china_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="building-shop-china_2"
            geometry={nodes["building-shop-china_2"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-shop-china_3"
            geometry={nodes["building-shop-china_3"].geometry}
            material={materials["26 RED-DARK"]}
          />
          <mesh
            name="building-shop-china_4"
            geometry={nodes["building-shop-china_4"].geometry}
            material={materials["30 YELLOW"]}
          />
          <mesh
            name="building-shop-china_5"
            geometry={nodes["building-shop-china_5"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-shop-china_6"
            geometry={nodes["building-shop-china_6"].geometry}
            material={materials["64 GLASS.002"]}
          />
          <mesh
            name="building-shop-china_7"
            geometry={nodes["building-shop-china_7"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-shop-china_8"
            geometry={nodes["building-shop-china_8"].geometry}
            material={materials["36 GREEN"]}
          />
          <mesh
            name="building-shop-china_9"
            geometry={nodes["building-shop-china_9"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="building-shop-china007"
          position={[6.127, 3.267, -3.74]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.189}
        >
          <mesh
            name="building-shop-china"
            geometry={nodes["building-shop-china"].geometry}
            material={materials["15 BROWN-WHITE"]}
          />
          <mesh
            name="building-shop-china_1"
            geometry={nodes["building-shop-china_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="building-shop-china_2"
            geometry={nodes["building-shop-china_2"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="building-shop-china_3"
            geometry={nodes["building-shop-china_3"].geometry}
            material={materials["26 RED-DARK"]}
          />
          <mesh
            name="building-shop-china_4"
            geometry={nodes["building-shop-china_4"].geometry}
            material={materials["30 YELLOW"]}
          />
          <mesh
            name="building-shop-china_5"
            geometry={nodes["building-shop-china_5"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="building-shop-china_6"
            geometry={nodes["building-shop-china_6"].geometry}
            material={materials["64 GLASS.002"]}
          />
          <mesh
            name="building-shop-china_7"
            geometry={nodes["building-shop-china_7"].geometry}
            material={materials["17 GREY-DARKEST.009"]}
          />
          <mesh
            name="building-shop-china_8"
            geometry={nodes["building-shop-china_8"].geometry}
            material={materials["36 GREEN"]}
          />
          <mesh
            name="building-shop-china_9"
            geometry={nodes["building-shop-china_9"].geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
        <group
          name="lamp-city001"
          position={[3.734, 3.267, -0.05]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city002"
          position={[3.734, 3.267, -5.663]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city003"
          position={[3.734, 3.267, -2.798]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city004"
          position={[3.734, 3.267, 2.674]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="lamp-city005"
          position={[3.734, 3.267, 5.469]}
          scale={0.189}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp}
          />
        </group>
        <group
          name="Cube"
          position={[-0.05, 2.314, -0.105]}
          scale={[0.151, 0.019, 0.151]}
        >
          <mesh
            name="Cube_1"
            geometry={nodes.Cube_1.geometry}
            material={materials["18 GREY-DARK"]}
          />
          <mesh
            name="Cube_2"
            geometry={nodes.Cube_2.geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="Cube_3"
            geometry={nodes.Cube_3.geometry}
            material={materials["21 GREY LIGHT"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/POIShops.glb");
