/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeElements } from "@react-three/fiber";
type GLTFResult = GLTF & {
  nodes: {
    ["water-tower-big_1"]: THREE.Mesh;
    ["water-tower-big_2"]: THREE.Mesh;
    ["water-tower-big_3"]: THREE.Mesh;
    ["water-tower-big_4"]: THREE.Mesh;
    ["water-tower-big_5"]: THREE.Mesh;
    Plane034_blue_0: THREE.Mesh;
    Plane035_white_0: THREE.Mesh;
    Box172_blue2_0: THREE.Mesh;
    Box173_purple2_0: THREE.Mesh;
    Box175_purple2_0: THREE.Mesh;
    Box177_purple2_0: THREE.Mesh;
    Box178_purple2_0: THREE.Mesh;
    Box179_purple2_0: THREE.Mesh;
    Box180_purple2_0: THREE.Mesh;
    Box181_purple2_0: THREE.Mesh;
    Box182_purple2_0: THREE.Mesh;
    Box183_purple2_0: THREE.Mesh;
    Box184_purple2_0: THREE.Mesh;
    Box185_purple2_0: THREE.Mesh;
    Box186_purple2_0: THREE.Mesh;
    Box187_purple2_0: THREE.Mesh;
    Box188_purple2_0: THREE.Mesh;
    Box189_purple2_0: THREE.Mesh;
    Box190_purple2_0: THREE.Mesh;
    ["tile-pool-small_1"]: THREE.Mesh;
    ["tile-pool-small_2"]: THREE.Mesh;
    ["tile-pool-small_3"]: THREE.Mesh;
    ["tile-pool-small_4"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["fence-picket"]: THREE.Mesh;
    ["fence-picket001"]: THREE.Mesh;
    ["fence-picket002"]: THREE.Mesh;
    ["fence-picket003"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["fence-picket004"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["fence-picket005"]: THREE.Mesh;
    ["fence-picket006"]: THREE.Mesh;
    ["fence-picket007"]: THREE.Mesh;
    ["fence-picket008"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["bush-big_1"]: THREE.Mesh;
    ["bush-big_2"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-metal"]: THREE.Mesh;
    ["fence-stone-metal_1"]: THREE.Mesh;
    ["fence-stone-tower001"]: THREE.Mesh;
    ["fence-stone-tower002"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_1"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_2"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_3"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_4"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_5"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_1"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_2"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_3"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_4"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_5"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_1"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_2"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_3"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_4"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_5"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_1"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_2"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_3"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_4"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_5"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_1"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_2"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_3"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_4"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_5"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_1"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_2"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_3"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_4"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_5"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_1"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_2"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_3"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_4"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_5"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_1"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_2"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_3"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_4"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_5"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_1"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_2"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_3"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_4"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_5"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_1"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_2"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_3"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_4"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_5"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_1"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_2"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_3"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_4"]: THREE.Mesh;
    ["house-wall-wood-green-2x3m_5"]: THREE.Mesh;
    ["scifi-pot-low-palm_1"]: THREE.Mesh;
    ["scifi-pot-low-palm_2"]: THREE.Mesh;
    ["scifi-pot-low-palm_3"]: THREE.Mesh;
    ["scifi-pot-low-palm_4"]: THREE.Mesh;
    ["scifi-pot-low-palm_5"]: THREE.Mesh;
    ["scifi-pot-low-palm_6"]: THREE.Mesh;
    ["scifi-pot-low-palm_7"]: THREE.Mesh;
    ["scifi-pot-low-palm_8"]: THREE.Mesh;
    ["scifi-pot-low-palm_9"]: THREE.Mesh;
    ["scifi-pot-low-palm_10"]: THREE.Mesh;
    ["scifi-pot-low-palm_1"]: THREE.Mesh;
    ["scifi-pot-low-palm_2"]: THREE.Mesh;
    ["scifi-pot-low-palm_3"]: THREE.Mesh;
    ["scifi-pot-low-palm_4"]: THREE.Mesh;
    ["scifi-pot-low-palm_5"]: THREE.Mesh;
    ["scifi-pot-low-palm_6"]: THREE.Mesh;
    ["scifi-pot-low-palm_7"]: THREE.Mesh;
    ["scifi-pot-low-palm_8"]: THREE.Mesh;
    ["scifi-pot-low-palm_9"]: THREE.Mesh;
    ["scifi-pot-low-palm_10"]: THREE.Mesh;
    ["lamp-city"]: THREE.Mesh;
    ["lamp-city_1"]: THREE.Mesh;
    polySurface635_phong1_0: THREE.Mesh;
  };
  materials: {
    ["18 GREY-DARK.001"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.002"]: THREE.MeshPhysicalMaterial;
    ["23 GREY-WHITE.001"]: THREE.MeshPhysicalMaterial;
    ["43 BLUE-MEDIUM"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.002"]: THREE.MeshPhysicalMaterial;
    blue: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    blue2: THREE.MeshStandardMaterial;
    purple2: THREE.MeshStandardMaterial;
    ["58 WHITE.003"]: THREE.MeshPhysicalMaterial;
    ["43 BLUE-MEDIUM"]: THREE.MeshPhysicalMaterial;
    ["48 TRANSPARENT-BLUE.001"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.002"]: THREE.MeshPhysicalMaterial;
    ["10 BROWN-DARK"]: THREE.MeshPhysicalMaterial;
    ["35 GREEN-MEDIUM.002"]: THREE.MeshPhysicalMaterial;
    ["22 GREY-LIGHTEST.002"]: THREE.MeshPhysicalMaterial;
    ["9 BROWN-DARKEST.002"]: THREE.MeshPhysicalMaterial;
    ["BROWN-MEDIUM"]: THREE.MeshPhysicalMaterial;
    ["14 BROWN-LIGHTEST"]: THREE.MeshPhysicalMaterial;
    ["36 GREEN"]: THREE.MeshPhysicalMaterial;
    ["18 GREY-DARK.001"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.001"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK"]: THREE.MeshPhysicalMaterial;
    ["28 ORANGE"]: THREE.MeshPhysicalMaterial;
    ["42 BLUE-DARK.001"]: THREE.MeshPhysicalMaterial;
    ["51 PINK-MEDIUM"]: THREE.MeshPhysicalMaterial;
    ["55 EMISSION-PURPLE"]: THREE.MeshStandardMaterial;
    ["62 EMISSION-YELLOW"]: THREE.MeshStandardMaterial;
    GREY: THREE.MeshPhysicalMaterial;
    Lamp_Light: THREE.MeshPhysicalMaterial;
    ["9 BROWN-DARKEST"]: THREE.MeshPhysicalMaterial;
  };
};

export function ResidentialProps(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/gated_residential_full_props.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="water-tower-big"
          position={[191.003, 2.667, 59.486]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.484}
        >
          <mesh
            name="water-tower-big_1"
            geometry={nodes["water-tower-big_1"].geometry}
            material={materials["18 GREY-DARK.001"]}
          />
          <mesh
            name="water-tower-big_2"
            geometry={nodes["water-tower-big_2"].geometry}
            material={materials["20 GREY.002"]}
          />
          <mesh
            name="water-tower-big_3"
            geometry={nodes["water-tower-big_3"].geometry}
            material={materials["23 GREY-WHITE.001"]}
          />
          <mesh
            name="water-tower-big_4"
            geometry={nodes["water-tower-big_4"].geometry}
            material={materials["43 BLUE-MEDIUM"]}
          />
          <mesh
            name="water-tower-big_5"
            geometry={nodes["water-tower-big_5"].geometry}
            material={materials["64 GLASS.002"]}
          />
        </group>
        <mesh
          name="Plane034_blue_0"
          geometry={nodes.Plane034_blue_0.geometry}
          material={materials.blue}
          position={[157.308, 2.762, 89.676]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Plane035_white_0"
          geometry={nodes.Plane035_white_0.geometry}
          material={materials.white}
          position={[157.306, 3.535, 89.756]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box172_blue2_0"
          geometry={nodes.Box172_blue2_0.geometry}
          material={materials.blue2}
          position={[157.296, 2.469, 89.748]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box173_purple2_0"
          geometry={nodes.Box173_purple2_0.geometry}
          material={materials.purple2}
          position={[162.233, 2.945, 96.662]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box175_purple2_0"
          geometry={nodes.Box175_purple2_0.geometry}
          material={materials.purple2}
          position={[162.214, 2.945, 82.813]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box177_purple2_0"
          geometry={nodes.Box177_purple2_0.geometry}
          material={materials.purple2}
          position={[160.299, 2.899, 95.674]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box178_purple2_0"
          geometry={nodes.Box178_purple2_0.geometry}
          material={materials.purple2}
          position={[161.234, 2.972, 95.718]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box179_purple2_0"
          geometry={nodes.Box179_purple2_0.geometry}
          material={materials.purple2}
          position={[159.257, 2.899, 95.702]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box180_purple2_0"
          geometry={nodes.Box180_purple2_0.geometry}
          material={materials.purple2}
          position={[154.324, 2.899, 95.77]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box181_purple2_0"
          geometry={nodes.Box181_purple2_0.geometry}
          material={materials.purple2}
          position={[153.389, 2.972, 95.727]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box182_purple2_0"
          geometry={nodes.Box182_purple2_0.geometry}
          material={materials.purple2}
          position={[155.366, 2.899, 95.742]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box183_purple2_0"
          geometry={nodes.Box183_purple2_0.geometry}
          material={materials.purple2}
          position={[160.299, 2.899, 83.574]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box184_purple2_0"
          geometry={nodes.Box184_purple2_0.geometry}
          material={materials.purple2}
          position={[161.234, 2.972, 83.618]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box185_purple2_0"
          geometry={nodes.Box185_purple2_0.geometry}
          material={materials.purple2}
          position={[159.257, 2.899, 83.602]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box186_purple2_0"
          geometry={nodes.Box186_purple2_0.geometry}
          material={materials.purple2}
          position={[154.324, 2.899, 83.67]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box187_purple2_0"
          geometry={nodes.Box187_purple2_0.geometry}
          material={materials.purple2}
          position={[153.389, 2.972, 83.627]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box188_purple2_0"
          geometry={nodes.Box188_purple2_0.geometry}
          material={materials.purple2}
          position={[155.366, 2.899, 83.642]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box189_purple2_0"
          geometry={nodes.Box189_purple2_0.geometry}
          material={materials.purple2}
          position={[152.351, 2.945, 96.662]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <mesh
          name="Box190_purple2_0"
          geometry={nodes.Box190_purple2_0.geometry}
          material={materials.purple2}
          position={[152.332, 2.945, 82.813]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.009}
        />
        <group
          name="tile-pool-small"
          position={[166.336, 2.686, 71.334]}
          scale={2.693}
        >
          <mesh
            name="tile-pool-small_1"
            geometry={nodes["tile-pool-small_1"].geometry}
            material={materials["58 WHITE.003"]}
          />
          <mesh
            name="tile-pool-small_2"
            geometry={nodes["tile-pool-small_2"].geometry}
            material={materials["43 BLUE-MEDIUM"]}
          />
          <mesh
            name="tile-pool-small_3"
            geometry={nodes["tile-pool-small_3"].geometry}
            material={materials["48 TRANSPARENT-BLUE.001"]}
          />
          <mesh
            name="tile-pool-small_4"
            geometry={nodes["tile-pool-small_4"].geometry}
            material={materials["20 GREY.002"]}
          />
        </group>
        <group
          name="bush-big"
          position={[168.757, 2.668, 80.861]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big005"
          position={[164.261, 2.668, 80.861]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big006"
          position={[173.537, 2.668, 57.505]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={1.574}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big007"
          position={[173.504, 2.668, 60.202]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big008"
          position={[171.961, 2.668, 55.526]}
          rotation={[Math.PI, -1.277, Math.PI]}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="fence-stone-metal004"
          position={[172.74, 2.667, 83.934]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="fence-stone-metal005"
          position={[172.74, 2.667, 88.11]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="fence-stone-metal006"
          position={[172.74, 2.667, 92.276]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big009"
          position={[172.173, 2.668, 95.113]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big010"
          position={[168.866, 2.668, 99.539]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal008" position={[149.055, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal009" position={[153.246, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal010" position={[157.455, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal011" position={[161.623, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big011"
          position={[170.178, 2.668, 97.147]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={1.504}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="fence-stone-metal012"
          position={[172.74, 2.667, 71.417]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="fence-stone-metal013"
          position={[172.74, 2.667, 75.593]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="fence-stone-metal014"
          position={[172.74, 2.667, 79.758]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="fence-stone-metal016"
          position={[172.74, 2.667, 63.115]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="fence-stone-metal017"
          position={[172.74, 2.667, 67.28]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal015" position={[152.71, 2.667, 55.652]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal018" position={[156.886, 2.667, 55.652]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal019" position={[161.077, 2.667, 55.652]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal020" position={[165.286, 2.667, 55.652]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal021" position={[169.454, 2.667, 55.652]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal024" position={[140.179, 2.667, 55.652]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal025" position={[144.388, 2.667, 55.652]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal026" position={[148.555, 2.667, 55.652]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big001"
          position={[137.462, 2.668, 55.497]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={1.574}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big002"
          position={[134.835, 2.668, 55.526]}
          rotation={[Math.PI, -1.277, Math.PI]}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big003"
          position={[159.644, 2.668, 76.155]}
          scale={0.543}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big004"
          position={[159.644, 2.668, 78.598]}
          scale={0.543}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big012"
          position={[159.644, 2.668, 71.279]}
          scale={0.543}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big013"
          position={[159.644, 2.668, 73.094]}
          scale={0.543}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big014"
          position={[159.644, 2.668, 66.134]}
          scale={0.543}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big015"
          position={[159.644, 2.668, 69.532]}
          scale={0.543}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big017"
          position={[159.644, 2.668, 63.48]}
          scale={0.543}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <mesh
          name="fence-picket"
          geometry={nodes["fence-picket"].geometry}
          material={materials["58 WHITE.003"]}
          position={[134.132, 2.666, 57.432]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.485}
        />
        <mesh
          name="fence-picket001"
          geometry={nodes["fence-picket001"].geometry}
          material={materials["58 WHITE.003"]}
          position={[134.132, 2.666, 60.319]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.485}
        />
        <mesh
          name="fence-picket002"
          geometry={nodes["fence-picket002"].geometry}
          material={materials["58 WHITE.003"]}
          position={[134.132, 2.666, 63.25]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.485}
        />
        <mesh
          name="fence-picket003"
          geometry={nodes["fence-picket003"].geometry}
          material={materials["58 WHITE.003"]}
          position={[134.132, 2.666, 66.253]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.485}
        />
        <group
          name="bush-big016"
          position={[134.244, 2.668, 69.017]}
          rotation={[Math.PI, -1.277, Math.PI]}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <mesh
          name="fence-picket004"
          geometry={nodes["fence-picket004"].geometry}
          material={materials["58 WHITE.003"]}
          position={[132.286, 2.666, 55.489]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={1.485}
        />
        <group
          name="bush-big019"
          position={[134.835, 2.668, 81.515]}
          rotation={[Math.PI, -1.277, Math.PI]}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <mesh
          name="fence-picket005"
          geometry={nodes["fence-picket005"].geometry}
          material={materials["58 WHITE.003"]}
          position={[134.132, 2.666, 83.422]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.485}
        />
        <mesh
          name="fence-picket006"
          geometry={nodes["fence-picket006"].geometry}
          material={materials["58 WHITE.003"]}
          position={[134.132, 2.666, 86.309]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.485}
        />
        <mesh
          name="fence-picket007"
          geometry={nodes["fence-picket007"].geometry}
          material={materials["58 WHITE.003"]}
          position={[134.132, 2.666, 89.24]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.485}
        />
        <mesh
          name="fence-picket008"
          geometry={nodes["fence-picket008"].geometry}
          material={materials["58 WHITE.003"]}
          position={[134.132, 2.666, 92.243]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.485}
        />
        <group
          name="bush-big020"
          position={[134.244, 2.668, 95.007]}
          rotation={[Math.PI, -1.277, Math.PI]}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group
          name="bush-big021"
          position={[71.449, 2.668, 58.241]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={1.297}
        >
          <mesh
            name="bush-big_1"
            geometry={nodes["bush-big_1"].geometry}
            material={materials["10 BROWN-DARK"]}
          />
          <mesh
            name="bush-big_2"
            geometry={nodes["bush-big_2"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal001" position={[90.549, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal022" position={[94.725, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal023" position={[98.916, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal027" position={[103.125, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal028" position={[107.292, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal029" position={[78.018, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal030" position={[82.227, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal031" position={[86.394, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal032" position={[111.416, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal033" position={[115.607, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal034" position={[119.815, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal035" position={[123.983, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal036" position={[128.177, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal037" position={[132.358, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal038" position={[136.493, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal002" position={[144.879, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal003" position={[140.682, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <group name="fence-stone-metal007" position={[165.826, 2.667, 100.093]}>
          <mesh
            name="fence-stone-metal"
            geometry={nodes["fence-stone-metal"].geometry}
            material={materials["22 GREY-LIGHTEST.002"]}
          />
          <mesh
            name="fence-stone-metal_1"
            geometry={nodes["fence-stone-metal_1"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
        </group>
        <mesh
          name="fence-stone-tower001"
          geometry={nodes["fence-stone-tower001"].geometry}
          material={materials["22 GREY-LIGHTEST.002"]}
          position={[66.403, 2.667, 82.069]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.93}
        />
        <mesh
          name="fence-stone-tower002"
          geometry={nodes["fence-stone-tower002"].geometry}
          material={materials["22 GREY-LIGHTEST.002"]}
          position={[66.403, 2.667, 67.869]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.93}
        />
        <group
          name="house-wall-wood-green-2x3m"
          position={[66.998, 2.667, 88.704]}
        >
          <mesh
            name="house-wall-wood-green-2x3m_1"
            geometry={nodes["house-wall-wood-green-2x3m_1"].geometry}
            material={materials["9 BROWN-DARKEST.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_2"
            geometry={nodes["house-wall-wood-green-2x3m_2"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_3"
            geometry={nodes["house-wall-wood-green-2x3m_3"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_4"
            geometry={nodes["house-wall-wood-green-2x3m_4"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_5"
            geometry={nodes["house-wall-wood-green-2x3m_5"].geometry}
            material={materials["36 GREEN"]}
          />
        </group>
        <group
          name="house-wall-wood-green-2x3m001"
          position={[66.983, 2.667, 82.666]}
          rotation={[0, -1.571, 0]}
        >
          <mesh
            name="house-wall-wood-green-2x3m_1"
            geometry={nodes["house-wall-wood-green-2x3m_1"].geometry}
            material={materials["9 BROWN-DARKEST.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_2"
            geometry={nodes["house-wall-wood-green-2x3m_2"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_3"
            geometry={nodes["house-wall-wood-green-2x3m_3"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_4"
            geometry={nodes["house-wall-wood-green-2x3m_4"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_5"
            geometry={nodes["house-wall-wood-green-2x3m_5"].geometry}
            material={materials["36 GREEN"]}
          />
        </group>
        <group
          name="house-wall-wood-green-2x3m002"
          position={[66.983, 2.667, 84.684]}
          rotation={[0, -1.571, 0]}
        >
          <mesh
            name="house-wall-wood-green-2x3m_1"
            geometry={nodes["house-wall-wood-green-2x3m_1"].geometry}
            material={materials["9 BROWN-DARKEST.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_2"
            geometry={nodes["house-wall-wood-green-2x3m_2"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_3"
            geometry={nodes["house-wall-wood-green-2x3m_3"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_4"
            geometry={nodes["house-wall-wood-green-2x3m_4"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_5"
            geometry={nodes["house-wall-wood-green-2x3m_5"].geometry}
            material={materials["36 GREEN"]}
          />
        </group>
        <group
          name="house-wall-wood-green-2x3m003"
          position={[69.016, 2.667, 88.704]}
        >
          <mesh
            name="house-wall-wood-green-2x3m_1"
            geometry={nodes["house-wall-wood-green-2x3m_1"].geometry}
            material={materials["9 BROWN-DARKEST.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_2"
            geometry={nodes["house-wall-wood-green-2x3m_2"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_3"
            geometry={nodes["house-wall-wood-green-2x3m_3"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_4"
            geometry={nodes["house-wall-wood-green-2x3m_4"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_5"
            geometry={nodes["house-wall-wood-green-2x3m_5"].geometry}
            material={materials["36 GREEN"]}
          />
        </group>
        <group
          name="house-wall-wood-green-2x3m005"
          position={[66.983, 2.667, 86.702]}
          rotation={[0, -1.571, 0]}
        >
          <mesh
            name="house-wall-wood-green-2x3m_1"
            geometry={nodes["house-wall-wood-green-2x3m_1"].geometry}
            material={materials["9 BROWN-DARKEST.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_2"
            geometry={nodes["house-wall-wood-green-2x3m_2"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_3"
            geometry={nodes["house-wall-wood-green-2x3m_3"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_4"
            geometry={nodes["house-wall-wood-green-2x3m_4"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_5"
            geometry={nodes["house-wall-wood-green-2x3m_5"].geometry}
            material={materials["36 GREEN"]}
          />
        </group>
        <group
          name="house-wall-wood-green-2x3m006"
          position={[66.522, 2.667, 61.229]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="house-wall-wood-green-2x3m_1"
            geometry={nodes["house-wall-wood-green-2x3m_1"].geometry}
            material={materials["9 BROWN-DARKEST.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_2"
            geometry={nodes["house-wall-wood-green-2x3m_2"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_3"
            geometry={nodes["house-wall-wood-green-2x3m_3"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_4"
            geometry={nodes["house-wall-wood-green-2x3m_4"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_5"
            geometry={nodes["house-wall-wood-green-2x3m_5"].geometry}
            material={materials["36 GREEN"]}
          />
        </group>
        <group
          name="house-wall-wood-green-2x3m007"
          position={[72.56, 2.667, 61.213]}
          rotation={[-Math.PI, 0, -Math.PI]}
        >
          <mesh
            name="house-wall-wood-green-2x3m_1"
            geometry={nodes["house-wall-wood-green-2x3m_1"].geometry}
            material={materials["9 BROWN-DARKEST.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_2"
            geometry={nodes["house-wall-wood-green-2x3m_2"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_3"
            geometry={nodes["house-wall-wood-green-2x3m_3"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_4"
            geometry={nodes["house-wall-wood-green-2x3m_4"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_5"
            geometry={nodes["house-wall-wood-green-2x3m_5"].geometry}
            material={materials["36 GREEN"]}
          />
        </group>
        <group
          name="house-wall-wood-green-2x3m008"
          position={[70.542, 2.667, 61.213]}
          rotation={[-Math.PI, 0, -Math.PI]}
        >
          <mesh
            name="house-wall-wood-green-2x3m_1"
            geometry={nodes["house-wall-wood-green-2x3m_1"].geometry}
            material={materials["9 BROWN-DARKEST.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_2"
            geometry={nodes["house-wall-wood-green-2x3m_2"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_3"
            geometry={nodes["house-wall-wood-green-2x3m_3"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_4"
            geometry={nodes["house-wall-wood-green-2x3m_4"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_5"
            geometry={nodes["house-wall-wood-green-2x3m_5"].geometry}
            material={materials["36 GREEN"]}
          />
        </group>
        <group
          name="house-wall-wood-green-2x3m009"
          position={[66.522, 2.667, 63.247]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="house-wall-wood-green-2x3m_1"
            geometry={nodes["house-wall-wood-green-2x3m_1"].geometry}
            material={materials["9 BROWN-DARKEST.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_2"
            geometry={nodes["house-wall-wood-green-2x3m_2"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_3"
            geometry={nodes["house-wall-wood-green-2x3m_3"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_4"
            geometry={nodes["house-wall-wood-green-2x3m_4"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_5"
            geometry={nodes["house-wall-wood-green-2x3m_5"].geometry}
            material={materials["36 GREEN"]}
          />
        </group>
        <group
          name="house-wall-wood-green-2x3m010"
          position={[66.522, 2.667, 65.265]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="house-wall-wood-green-2x3m_1"
            geometry={nodes["house-wall-wood-green-2x3m_1"].geometry}
            material={materials["9 BROWN-DARKEST.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_2"
            geometry={nodes["house-wall-wood-green-2x3m_2"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_3"
            geometry={nodes["house-wall-wood-green-2x3m_3"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_4"
            geometry={nodes["house-wall-wood-green-2x3m_4"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_5"
            geometry={nodes["house-wall-wood-green-2x3m_5"].geometry}
            material={materials["36 GREEN"]}
          />
        </group>
        <group
          name="house-wall-wood-green-2x3m011"
          position={[68.524, 2.667, 61.213]}
          rotation={[-Math.PI, 0, -Math.PI]}
        >
          <mesh
            name="house-wall-wood-green-2x3m_1"
            geometry={nodes["house-wall-wood-green-2x3m_1"].geometry}
            material={materials["9 BROWN-DARKEST.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_2"
            geometry={nodes["house-wall-wood-green-2x3m_2"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_3"
            geometry={nodes["house-wall-wood-green-2x3m_3"].geometry}
            material={materials["14 BROWN-LIGHTEST"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_4"
            geometry={nodes["house-wall-wood-green-2x3m_4"].geometry}
            material={materials["35 GREEN-MEDIUM.002"]}
          />
          <mesh
            name="house-wall-wood-green-2x3m_5"
            geometry={nodes["house-wall-wood-green-2x3m_5"].geometry}
            material={materials["36 GREEN"]}
          />
        </group>
        <group
          name="scifi-pot-low-palm"
          position={[63.923, 2.667, 62.051]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.558}
        >
          <mesh
            name="scifi-pot-low-palm_1"
            geometry={nodes["scifi-pot-low-palm_1"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="scifi-pot-low-palm_2"
            geometry={nodes["scifi-pot-low-palm_2"].geometry}
            material={materials["18 GREY-DARK.001"]}
          />
          <mesh
            name="scifi-pot-low-palm_3"
            geometry={nodes["scifi-pot-low-palm_3"].geometry}
            material={materials["21 GREY LIGHT.001"]}
          />
          <mesh
            name="scifi-pot-low-palm_4"
            geometry={nodes["scifi-pot-low-palm_4"].geometry}
            material={materials["26 RED-DARK"]}
          />
          <mesh
            name="scifi-pot-low-palm_5"
            geometry={nodes["scifi-pot-low-palm_5"].geometry}
            material={materials["28 ORANGE"]}
          />
          <mesh
            name="scifi-pot-low-palm_6"
            geometry={nodes["scifi-pot-low-palm_6"].geometry}
            material={materials["36 GREEN"]}
          />
          <mesh
            name="scifi-pot-low-palm_7"
            geometry={nodes["scifi-pot-low-palm_7"].geometry}
            material={materials["42 BLUE-DARK.001"]}
          />
          <mesh
            name="scifi-pot-low-palm_8"
            geometry={nodes["scifi-pot-low-palm_8"].geometry}
            material={materials["51 PINK-MEDIUM"]}
          />
          <mesh
            name="scifi-pot-low-palm_9"
            geometry={nodes["scifi-pot-low-palm_9"].geometry}
            material={materials["55 EMISSION-PURPLE"]}
          />
          <mesh
            name="scifi-pot-low-palm_10"
            geometry={nodes["scifi-pot-low-palm_10"].geometry}
            material={materials["62 EMISSION-YELLOW"]}
          />
        </group>
        <group
          name="scifi-pot-low-palm002"
          position={[63.731, 2.667, 88.193]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.558}
        >
          <mesh
            name="scifi-pot-low-palm_1"
            geometry={nodes["scifi-pot-low-palm_1"].geometry}
            material={materials["BROWN-MEDIUM"]}
          />
          <mesh
            name="scifi-pot-low-palm_2"
            geometry={nodes["scifi-pot-low-palm_2"].geometry}
            material={materials["18 GREY-DARK.001"]}
          />
          <mesh
            name="scifi-pot-low-palm_3"
            geometry={nodes["scifi-pot-low-palm_3"].geometry}
            material={materials["21 GREY LIGHT.001"]}
          />
          <mesh
            name="scifi-pot-low-palm_4"
            geometry={nodes["scifi-pot-low-palm_4"].geometry}
            material={materials["26 RED-DARK"]}
          />
          <mesh
            name="scifi-pot-low-palm_5"
            geometry={nodes["scifi-pot-low-palm_5"].geometry}
            material={materials["28 ORANGE"]}
          />
          <mesh
            name="scifi-pot-low-palm_6"
            geometry={nodes["scifi-pot-low-palm_6"].geometry}
            material={materials["36 GREEN"]}
          />
          <mesh
            name="scifi-pot-low-palm_7"
            geometry={nodes["scifi-pot-low-palm_7"].geometry}
            material={materials["42 BLUE-DARK.001"]}
          />
          <mesh
            name="scifi-pot-low-palm_8"
            geometry={nodes["scifi-pot-low-palm_8"].geometry}
            material={materials["51 PINK-MEDIUM"]}
          />
          <mesh
            name="scifi-pot-low-palm_9"
            geometry={nodes["scifi-pot-low-palm_9"].geometry}
            material={materials["55 EMISSION-PURPLE"]}
          />
          <mesh
            name="scifi-pot-low-palm_10"
            geometry={nodes["scifi-pot-low-palm_10"].geometry}
            material={materials["62 EMISSION-YELLOW"]}
          />
        </group>
        <group
          name="lamp-city019"
          position={[156.902, 2.667, 74.915]}
          rotation={[0, 1.571, 0]}
        >
          <mesh
            name="lamp-city"
            geometry={nodes["lamp-city"].geometry}
            material={materials.GREY}
          />
          <mesh
            name="lamp-city_1"
            geometry={nodes["lamp-city_1"].geometry}
            material={materials.Lamp_Light}
          />
        </group>
        <mesh
          name="polySurface635_phong1_0"
          geometry={nodes.polySurface635_phong1_0.geometry}
          material={materials["9 BROWN-DARKEST"]}
          position={[66.431, 2.467, 75.704]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.061}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/gated_residential_full_props.glb");
