/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";
import { useGLTF } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    ["building-hotel_1"]: THREE.Mesh;
    ["building-hotel_2"]: THREE.Mesh;
    ["building-hotel_3"]: THREE.Mesh;
    ["building-hotel_4"]: THREE.Mesh;
    ["building-hotel_5"]: THREE.Mesh;
    ["building-hotel_6"]: THREE.Mesh;
    ["building-hotel_7"]: THREE.Mesh;
    ["building-hotel_8"]: THREE.Mesh;
    ["building-hotel_9"]: THREE.Mesh;
    ["building-hotel_10"]: THREE.Mesh;
    ["building-casino001_1"]: THREE.Mesh;
    ["building-casino001_2"]: THREE.Mesh;
    ["building-casino001_3"]: THREE.Mesh;
    ["building-casino001_4"]: THREE.Mesh;
    ["building-casino001_5"]: THREE.Mesh;
    ["building-casino001_6"]: THREE.Mesh;
    ["building-casino001_7"]: THREE.Mesh;
    ["building-casino001_8"]: THREE.Mesh;
    ["building-casino001_9"]: THREE.Mesh;
    ["building-casino001_10"]: THREE.Mesh;
  };
  materials: {
    ["17 GREY-DARKEST.006"]: THREE.MeshPhysicalMaterial;
    ["48 TRANSPARENT-BLUE"]: THREE.MeshPhysicalMaterial;
    ["58 WHITE.005"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS"]: THREE.MeshPhysicalMaterial;
    ["20 GREY.006"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.002"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE.002"]: THREE.MeshPhysicalMaterial;
    ["14 BROWN-LIGHTEST.001"]: THREE.MeshPhysicalMaterial;
    ["11 BROWN-MEDIUM.001"]: THREE.MeshPhysicalMaterial;
    ["35 GREEN-MEDIUM"]: THREE.MeshPhysicalMaterial;
    ["50 PINK-DARK"]: THREE.MeshPhysicalMaterial;
    ["26 RED-DARK.005"]: THREE.MeshPhysicalMaterial;
    ["23 GREY-WHITE.003"]: THREE.MeshPhysicalMaterial;
    ["64 GLASS.006"]: THREE.MeshPhysicalMaterial;
    ["61 EMISSION-ORANGE.001"]: THREE.MeshStandardMaterial;
    ["20 GREY.007"]: THREE.MeshPhysicalMaterial;
    ["11 BROWN-MEDIUM.002"]: THREE.MeshPhysicalMaterial;
    ["35 GREEN-MEDIUM.001"]: THREE.MeshPhysicalMaterial;
    ["21 GREY LIGHT.003"]: THREE.MeshPhysicalMaterial;
    ["15 BROWN-WHITE.003"]: THREE.MeshPhysicalMaterial;
  };
};

export function ResortBuildings(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/resort-buildings.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-98.1, 2.68, -75.254]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-hotel_1"].geometry}
          material={materials["17 GREY-DARKEST.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-hotel_2"].geometry}
          material={materials["48 TRANSPARENT-BLUE"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-hotel_3"].geometry}
          material={materials["58 WHITE.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-hotel_4"].geometry}
          material={materials["64 GLASS"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-hotel_5"].geometry}
          material={materials["20 GREY.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-hotel_6"].geometry}
          material={materials["21 GREY LIGHT.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-hotel_7"].geometry}
          material={materials["15 BROWN-WHITE.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-hotel_8"].geometry}
          material={materials["14 BROWN-LIGHTEST.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-hotel_9"].geometry}
          material={materials["11 BROWN-MEDIUM.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-hotel_10"].geometry}
          material={materials["35 GREEN-MEDIUM"]}
        />
      </group>
      <group position={[-83.734, 2.667, -97.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-casino001_1"].geometry}
          material={materials["50 PINK-DARK"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-casino001_2"].geometry}
          material={materials["26 RED-DARK.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-casino001_3"].geometry}
          material={materials["23 GREY-WHITE.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-casino001_4"].geometry}
          material={materials["64 GLASS.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-casino001_5"].geometry}
          material={materials["61 EMISSION-ORANGE.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-casino001_6"].geometry}
          material={materials["20 GREY.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-casino001_7"].geometry}
          material={materials["11 BROWN-MEDIUM.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-casino001_8"].geometry}
          material={materials["35 GREEN-MEDIUM.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-casino001_9"].geometry}
          material={materials["21 GREY LIGHT.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["building-casino001_10"].geometry}
          material={materials["15 BROWN-WHITE.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/resort-buildings.glb");
